// src/features/project-console/secret-stores/external-secret-list.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router-dom';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { Dropdown } from 'primereact/dropdown';
import { Toast } from 'primereact/toast';
import {
  externalSecretApi,
  type ExternalSecret,
  type ExternalSecretRequest,
  type ExternalSecretDataRef,
  type ExternalSecretStatusDetail,
} from '../../../core/api/external-secret-api';
import { secretStoreApi, type SecretStore } from '../../../core/api/secret-store-api';
import { apiErrorMessage, formatMediumDateTime } from '../services/service-utils';
import { statusTone } from './secret-status';
import { StatusTag } from '../../../shared/components/status-tag';
import { StatusDialog } from './status-dialog';
import { usePolledResources } from '../../../shared/hooks/use-polled-resources';
import { useStatusDialog } from './use-status-dialog';
import { SECTION_TITLE_CLASS, DIVIDER_CLASS } from './constants';
import SearchFilter from '../../../shared/components/search-filter';
import { PageHeader } from '../../../shared/components/page-header';
import { useToastMessages } from '../../../shared/hooks/use-toast-messages';
import { useRowActionsMenu } from '../../../shared/hooks/use-row-actions-menu';
import { k8sNameError } from '../../../shared/utils/k8s-names';
import { DialogFooter } from '../../../shared/components/dialog-footer';
import {
  describeCheck,
  describeCheckFailure,
  applyCheckResults,
  groupByRemoteRef,
  CHECKING,
  type CheckDisplay,
} from './remote-key-check';
import { describeSyncOutcome, waitForSyncOutcome } from './sync-outcome';
import DeleteConfirmDialog from '../../../shared/components/delete-confirm-dialog';

const REFRESH_OPTIONS = [
  { label: '1 minute', value: '1m' },
  { label: '5 minutes', value: '5m' },
  { label: '15 minutes', value: '15m' },
  { label: '30 minutes', value: '30m' },
  { label: '1 hour', value: '1h' },
  { label: '6 hours', value: '6h' },
  { label: '24 hours', value: '24h' },
];

// An unverifiable answer is neither green nor red: the control plane could not
// ask, so nothing about the key was established.
const CHECK_TONE_CLASS: Record<CheckDisplay['tone'], string> = {
  found: 'text-success',
  absent: 'text-danger',
  unknown: 'text-fg-secondary',
  checking: 'text-fg-secondary',
};

const CHECK_TONE_ICON: Record<CheckDisplay['tone'], string> = {
  found: 'pi pi-check-circle',
  absent: 'pi pi-times-circle',
  unknown: 'pi pi-info-circle',
  checking: 'pi pi-spin pi-spinner',
};

const EMPTY_MAPPING = (): ExternalSecretDataRef => ({
  secretKey: '',
  remoteRef: { key: '', property: '' },
});

const getStatusTone = (status: string) => statusTone(status, 'Synced');

const isSecretChanged = (s: ExternalSecret, c: ExternalSecret) =>
  s.name !== c.name ||
  s.status !== c.status ||
  s.lastSyncedAt !== c.lastSyncedAt ||
  s.lastError !== c.lastError;

const toSecretFallbackDetail = (es: ExternalSecret): ExternalSecretStatusDetail => ({
  status: es.status,
  conditions: [],
  lastSyncedAt: es.lastSyncedAt,
  lastError: es.lastError,
});

export function ExternalSecretList() {
  const { projectId = '' } = useParams<{ projectId: string }>();
  const { toast, showSuccess, showError } = useToastMessages();

  const [readyStores, setReadyStores] = useState<SecretStore[]>([]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<ExternalSecret | null>(null);

  // Dialog state
  const [dialogVisible, setDialogVisible] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [saving, setSaving] = useState(false);

  // Form fields
  const [secretName, setSecretName] = useState('');
  const [selectedStoreRefName, setSelectedStoreRefName] = useState('');
  const [targetName, setTargetName] = useState('');
  const [refreshInterval, setRefreshInterval] = useState('1h');
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [dataMappings, setDataMappings] = useState<ExternalSecretDataRef[]>([EMPTY_MAPPING()]);
  // Keyed by mapping index. A result is dropped as soon as its row changes,
  // so a stale green never sits under a key that has since been edited.
  const [keyChecks, setKeyChecks] = useState<Record<number, CheckDisplay>>({});
  const [checkingKeys, setCheckingKeys] = useState(false);
  // The store currently selected, read by the in-flight checks when their
  // answers come back: an answer about the store that was selected when the
  // question left says nothing about the one selected now.
  const storeAtAnswerRef = useRef(selectedStoreRefName);
  storeAtAnswerRef.current = selectedStoreRefName;

  const {
    items: secrets,
    loading,
    unavailable,
    reload: loadSecrets,
    merge: mergeSecrets,
  } = usePolledResources(projectId, externalSecretApi.list, isSecretChanged, () =>
    showError('Failed to load external secrets'),
  );

  const listAndMerge = useCallback(
    () =>
      externalSecretApi.list(projectId).then((data) => {
        mergeSecrets(data);
        return data;
      }),
    [projectId, mergeSecrets],
  );

  const statusDialog = useStatusDialog({
    projectId,
    getStatus: externalSecretApi.getStatus,
    listAndMerge,
    toFallbackDetail: toSecretFallbackDetail,
    showError,
  });

  const loadReadyStores = useCallback(() => {
    if (!projectId) return;
    secretStoreApi
      .list(projectId)
      .then((stores) => setReadyStores(stores.filter((s) => s.status === 'Ready')))
      .catch(() => undefined);
  }, [projectId]);

  useEffect(() => {
    loadReadyStores();
  }, [loadReadyStores]);

  // --- Name validation ---
  const nameError = k8sNameError(secretName);

  const hasKeyToCheck = dataMappings.some((m) => m.remoteRef.key.trim() !== '');

  const formValid = (() => {
    if (!secretName || !selectedStoreRefName) return false;
    if (nameError) return false;
    return dataMappings.some((m) => m.secretKey && m.remoteRef.key);
  })();

  // --- Dialog ---
  const resetForm = () => {
    setSecretName('');
    setSelectedStoreRefName('');
    setTargetName('');
    setRefreshInterval('1h');
    setShowAdvanced(false);
    setDataMappings([EMPTY_MAPPING()]);
    setKeyChecks({});
  };

  const showCreateDialog = () => {
    loadReadyStores();
    resetForm();
    setEditMode(false);
    setDialogVisible(true);
  };

  const showEditDialog = (es: ExternalSecret) => {
    loadReadyStores();
    setEditMode(true);
    setSecretName(es.name);
    setSelectedStoreRefName(es.secretStoreRef);
    setTargetName(es.target?.name ?? '');
    setRefreshInterval(es.refreshInterval || '1h');
    setShowAdvanced(!!es.target?.name && es.target.name !== es.name);
    setDataMappings(
      es.data?.length
        ? es.data.map((d) => ({
            secretKey: d.secretKey,
            remoteRef: { key: d.remoteRef.key, property: d.remoteRef.property || '' },
          }))
        : [EMPTY_MAPPING()],
    );
    setKeyChecks({});
    setDialogVisible(true);
  };

  const addMapping = () => setDataMappings((list) => [...list, EMPTY_MAPPING()]);

  const removeMapping = (index: number) => {
    setDataMappings((list) => {
      const next = list.filter((_, i) => i !== index);
      return next.length === 0 ? [EMPTY_MAPPING()] : next;
    });
    // The results are held by index, so removing a row would leave every
    // result below it under the wrong key.
    setKeyChecks({});
  };

  const patchMapping = (index: number, patch: Partial<ExternalSecretDataRef>) => {
    setDataMappings((list) =>
      list.map((m, i) =>
        i === index ? { ...m, ...patch, remoteRef: { ...m.remoteRef, ...patch.remoteRef } } : m,
      ),
    );
    // Editing a row answers a question that was asked about its previous
    // value, so its result goes.
    setKeyChecks((checks) => {
      if (!(index in checks)) return checks;
      const next = { ...checks };
      delete next[index];
      return next;
    });
  };

  /**
   * Asks the server about every remote key in the form, before anything is
   * created. Without it the only way to learn that a key is wrong is to create
   * the import and wait for the controller to fail its first sync.
   */
  const checkKeys = () => {
    const rows = dataMappings
      .map((m, index) => ({ m, index }))
      .filter(({ m }) => m.remoteRef.key.trim() !== '');
    if (rows.length === 0) return;

    const askedOf = selectedStoreRefName;
    setCheckingKeys(true);
    // Each row is marked as being checked up front, and a result is only kept
    // for a row that still carries that mark. Without it an edit made while
    // the requests are in flight would have its entry deleted by patchMapping
    // and then put back by the answer, showing a verdict on a value that has
    // since changed.
    setKeyChecks(Object.fromEntries(rows.map(({ index }) => [index, CHECKING])));

    // One request per distinct remote reference rather than per row: rows
    // sharing one share an answer, and each request costs the server a
    // credentials read and a Vault round trip.
    const groups = groupByRemoteRef(
      rows.map(({ m, index }) => ({ index, key: m.remoteRef.key, property: m.remoteRef.property || undefined })),
    );

    Promise.all(
      groups.map((g) =>
        externalSecretApi
          .checkRemoteKey(projectId, {
            secretStoreRef: selectedStoreRefName,
            remoteRef: { key: g.key, property: g.property },
          })
          .then((result) => ({ indexes: g.indexes, display: describeCheck(result) }))
          .catch((err) => ({
            indexes: g.indexes,
            display: describeCheckFailure(apiErrorMessage(err, 'The key could not be checked')),
          })),
      ),
    ).then((results) => {
      // The store can change while the requests are in flight, and an answer
      // about the previous one says nothing about this one.
      if (askedOf !== storeAtAnswerRef.current) {
        setCheckingKeys(false);
        return;
      }
      setKeyChecks((current) => applyCheckResults(current, results));
      setCheckingKeys(false);
    });
  };

  const buildRequest = (): ExternalSecretRequest => ({
    name: secretName,
    secretStoreRef: selectedStoreRefName,
    target: { name: targetName || secretName },
    refreshInterval,
    data: dataMappings
      .filter((m) => m.secretKey && m.remoteRef.key)
      .map((m) => ({
        secretKey: m.secretKey,
        remoteRef: {
          key: m.remoteRef.key,
          property: m.remoteRef.property || undefined,
        },
      })),
  });

  const saveSecret = async () => {
    setSaving(true);
    const request = buildRequest();
    const wasEdit = editMode;

    // Read immediately before the write, not when the dialog opened. The list
    // refreshes every ten seconds, so a status copied at opening can be stale
    // by the time Save is pressed, and the first read afterwards would differ
    // from it and be taken as the outcome of an edit it actually precedes.
    const previous = wasEdit
      ? await externalSecretApi.getStatus(projectId, secretName).catch(() => 'unknown' as const)
      : null;

    const save = wasEdit
      ? externalSecretApi.update(projectId, secretName, request)
      : externalSecretApi.create(projectId, request);

    save
      // Scoped to the write itself. Covering the wait as well reported a
      // failure to create for an object that was created, and the caller then
      // tried again and hit a conflict.
      .catch((err) => {
        setSaving(false);
        showError(apiErrorMessage(err, `Failed to ${wasEdit ? 'update' : 'create'} external secret`));
        throw err;
      })
      .then(async () => {
        setSaving(false);
        setDialogVisible(false);
        loadSecrets();

        // A 201 says the object was written, not that it can read its key: the
        // controller finds that out on its first sync. Announcing success on
        // the write alone is what let a broken import look created and fine.
        // This is also the only honest report for a store the key check cannot
        // question ahead of time.
        //
        // On an update the previous status is already settled, so it is handed
        // over to be skipped: taken as the answer, it would report the failure
        // the edit has just fixed.
        const detail = await waitForSyncOutcome(
          () => externalSecretApi.getStatus(projectId, secretName),
          { ignoreUntilChanged: previous === 'unknown' ? null : previous },
        );
        const outcome = describeSyncOutcome(secretName, detail, wasEdit ? 'updated' : 'created', previous);
        loadSecrets();
        if (outcome.settled && !outcome.synced) {
          showError(outcome.message);
        } else {
          showSuccess(outcome.message);
        }
      })
      .catch(() => {
        // Already reported above, or raised by the wait after a successful
        // write. Either way the object's row now carries the truth.
      });
  };

  const confirmDelete = (es: ExternalSecret) => setDeleteTarget(es);

  const deleteSecret = (es: ExternalSecret) => {
    externalSecretApi
      .delete(projectId, es.name)
      .then(() => {
        showSuccess(`External secret "${es.name}" deleted successfully`);
        loadSecrets();
      })
      .catch((err) => {
        showError(apiErrorMessage(err, 'Failed to delete external secret'));
      });
  };

  const { menuElement, openMenu } = useRowActionsMenu<ExternalSecret>([
    { label: 'View Status', icon: 'pi pi-info-circle', command: statusDialog.open },
    { label: 'Edit', icon: 'pi pi-pencil', command: showEditDialog },
    { label: 'Delete', icon: 'pi pi-trash', command: confirmDelete },
  ]);

  const dialogFooter = (
    <DialogFooter
      onCancel={() => setDialogVisible(false)}
      onConfirm={saveSecret}
      confirmLabel={editMode ? 'Save' : 'Create'}
      confirmDisabled={!formValid || checkingKeys}
      busy={saving}
      leading={
        <Button
          severity="secondary"
          outlined
          icon={checkingKeys ? 'pi pi-spin pi-spinner' : 'pi pi-search'}
          label="Check keys"
          disabled={saving || checkingKeys || !selectedStoreRefName || !hasKeyToCheck}
          onClick={checkKeys}
        />
      }
    />
  );

  return (
    <div>
      {/* Top Bar */}
      <PageHeader
        title="External Secrets"
        actions={
          <button className="create-btn" onClick={showCreateDialog}>
            <i className="pi pi-plus"></i>
            <span>Add external secret</span>
          </button>
        }
      />

      <SearchFilter
        value={globalFilter}
        onChange={setGlobalFilter}
        placeholder="Filter secrets..."
      />

      {/* Data Table */}
      <div className="table-wrapper">
        <DataTable paginator rows={25} paginatorTemplate="PrevPageLink PageLinks NextPageLink" alwaysShowPaginator={false}
          value={secrets}
          loading={loading}
          globalFilter={globalFilter}
          globalFilterFields={['name', 'secretStoreRef', 'target.name', 'status']}
          className="minimal-table"
          dataKey="name"
          rowClassName={() => 'cluster-row'}
          emptyMessage={
            <div className="flex items-center justify-center gap-2 p-8 text-[14px] text-fg-secondary">
              <i className="pi pi-key text-[1.2rem] opacity-50"></i>
              <span>
                {unavailable ? (
                  <>
                    Vault integration is not installed on this cluster ({unavailable}), so external
                    secrets cannot be created from here.
                  </>
                ) : (
                  <>
                    No external secrets configured. Click <strong>Add external secret</strong> to
                    create one.
                  </>
                )}
              </span>
            </div>
          }
        >
          <Column
            header="Name"
            field="name"
            style={{ width: '20%' }}
            body={(es: ExternalSecret) => <span className="font-medium">{es.name}</span>}
          />
          <Column
            header="Secret Store"
            field="secretStoreRef"
            style={{ width: '16%' }}
            body={(es: ExternalSecret) => (
              <span className="inline-flex items-center gap-1.5 rounded-xs border border-border-light bg-surface-secondary px-2 py-[3px] text-[12px] font-medium text-fg-secondary">
                <i className="pi pi-database text-[11px]"></i>
                {es.secretStoreRef}
              </span>
            )}
          />
          <Column
            header="Target Secret"
            style={{ width: '20%' }}
            body={(es: ExternalSecret) => (
              <span className="text-[13px] text-fg-secondary mono">{es.target?.name || '-'}</span>
            )}
          />
          <Column
            header="Status"
            field="status"
            style={{ width: '10%' }}
            body={(es: ExternalSecret) => (
              <span title={es.lastError || ''}>
                <StatusTag
                  value={es.status}
                  tone={getStatusTone(es.status)}
                  pulse={es.status === 'Pending'}
                />
              </span>
            )}
          />
          <Column
            header="Last Synced"
            style={{ width: '22%' }}
            className="text-[13px] whitespace-nowrap text-fg-secondary"
            body={(es: ExternalSecret) =>
              es.lastSyncedAt ? formatMediumDateTime(es.lastSyncedAt) : '-'
            }
          />
          <Column
            style={{ width: '12%', textAlign: 'right' }}
            body={(es: ExternalSecret) => (
              <div className="actions">
                <Button
                  icon="pi pi-info-circle"
                  text
                  rounded
                  onClick={() => statusDialog.open(es)}
                  title="View status"
                  aria-label={`View status for ${es.name}`}
                />
                <Button
                  icon="pi pi-ellipsis-v"
                  text
                  rounded
                  aria-label={`Actions for ${es.name}`}
                  onClick={(e) => openMenu(es, e)}
                />
              </div>
            )}
          />
        </DataTable>
        {menuElement}
      </div>

      {/* Create / Edit Dialog */}
      <Dialog
        header={editMode ? 'Edit external secret' : 'Add external secret'}
        visible={dialogVisible}
        modal
        draggable={false}
        resizable={false}
        style={{ width: '650px' }}
        className="db-dialog"
        closable
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
      >
        <div className="dialog-content">
          {/* Name */}
          <div className="field">
            <label htmlFor="esName">Name</label>
            <InputText
              id="esName"
              value={secretName}
              onChange={(e) => setSecretName(e.target.value)}
              className={`w-full dialog-input${nameError ? ' border-danger!' : ''}`}
              placeholder="e.g., db-credentials"
              disabled={editMode}
            />
            {nameError && <small className="mt-1 block text-[12px] text-danger">{nameError}</small>}
          </div>

          <hr className={DIVIDER_CLASS} />
          <h4 className={SECTION_TITLE_CLASS}>Source</h4>

          {/* Secret Store */}
          <div className="field">
            <label htmlFor="storeRef">Secret Store</label>
            {readyStores.length === 0 ? (
              <div className="alert-warn flex items-center gap-2 rounded-md border px-3 py-2.5 text-[13px]">
                <i className="pi pi-info-circle shrink-0 text-[14px]"></i>
                <span>
                  No ready secret stores available. Create and connect a secret store first.
                </span>
              </div>
            ) : (
              <Dropdown
                id="storeRef"
                options={readyStores}
                value={selectedStoreRefName}
                onChange={(e) => {
                  setSelectedStoreRefName(e.value);
                  // A verdict belongs to the store it was asked of. Left on screen it
                  // would sit under another store as a green nobody established, and
                  // an import could be created on the strength of it.
                  setKeyChecks({});
                }}
                optionLabel="name"
                optionValue="name"
                placeholder="Select a secret store"
                className="w-full"
                appendTo={document.body}
                itemTemplate={(store: SecretStore) => (
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{store.name}</span>
                    <span className="text-[12px] text-fg-secondary capitalize">
                      {store.provider}
                    </span>
                  </div>
                )}
              />
            )}
          </div>

          {/* Refresh Interval */}
          <div className="field">
            <label htmlFor="refreshInterval">Refresh interval</label>
            <Dropdown
              id="refreshInterval"
              options={REFRESH_OPTIONS}
              value={refreshInterval}
              onChange={(e) => setRefreshInterval(e.value)}
              optionLabel="label"
              optionValue="value"
              className="w-full"
              appendTo={document.body}
            />
          </div>

          <hr className={DIVIDER_CLASS} />
          <h4 className={SECTION_TITLE_CLASS}>Data Mappings</h4>
          <p className="m-0 mb-3 text-[13px] text-fg-secondary">
            Map keys from the remote secret store to keys in the Kubernetes Secret.
          </p>

          <div className="flex flex-col gap-2">
            {dataMappings.map((mapping, index) => (
              <div
                key={index}
                className="rounded-md border border-border-light bg-surface-secondary px-3 py-2.5"
              >
                <div className="flex items-end gap-2">
                  <div className="flex flex-1 flex-col gap-1">
                    <label className="text-[11px] font-semibold tracking-[0.5px] text-fg-secondary uppercase">
                      Secret Key
                    </label>
                    <InputText
                      value={mapping.secretKey}
                      onChange={(e) => patchMapping(index, { secretKey: e.target.value })}
                      className="dialog-input text-[13px]!"
                      placeholder="e.g., DB_PASSWORD"
                    />
                  </div>
                  <div className="flex flex-1 flex-col gap-1">
                    <label className="text-[11px] font-semibold tracking-[0.5px] text-fg-secondary uppercase">
                      Remote Key
                    </label>
                    <InputText
                      value={mapping.remoteRef.key}
                      onChange={(e) =>
                        patchMapping(index, {
                          remoteRef: { ...mapping.remoteRef, key: e.target.value },
                        })
                      }
                      className="dialog-input text-[13px]!"
                      placeholder="e.g., myapp/db"
                    />
                  </div>
                  <div className="flex flex-[0.8] flex-col gap-1">
                    <label className="text-[11px] font-semibold tracking-[0.5px] text-fg-secondary uppercase">
                      Property <span className="optional">(opt.)</span>
                    </label>
                    <InputText
                      value={mapping.remoteRef.property ?? ''}
                      onChange={(e) =>
                        patchMapping(index, {
                          remoteRef: { ...mapping.remoteRef, property: e.target.value },
                        })
                      }
                      className="dialog-input text-[13px]!"
                      placeholder="e.g., password"
                    />
                  </div>
                  <Button
                    icon="pi pi-times"
                    text
                    severity="danger"
                    onClick={() => removeMapping(index)}
                    disabled={dataMappings.length <= 1}
                    aria-label="Remove mapping"
                  />
                </div>
                {keyChecks[index] && (
                  <div
                    className={`mt-1.5 flex items-start gap-1.5 text-[12px] ${CHECK_TONE_CLASS[keyChecks[index].tone]}`}
                    role="status"
                  >
                    <i className={`${CHECK_TONE_ICON[keyChecks[index].tone]} mt-0.5 text-[11px]`}></i>
                    <span>
                      {keyChecks[index].message}
                      {keyChecks[index].properties.length > 0 && (
                        <>
                          {' '}
                          <span className="text-fg-muted">
                            Available: {keyChecks[index].properties.join(', ')}
                          </span>
                        </>
                      )}
                    </span>
                  </div>
                )}
              </div>
            ))}
          </div>
          <Button icon="pi pi-plus" text label="Add mapping" onClick={addMapping} />

          {/* Advanced */}
          <hr className={DIVIDER_CLASS} />
          <button
            className="inline-flex cursor-pointer items-center gap-1.5 border-none bg-transparent px-0 py-1 text-[13px] font-semibold text-fg-secondary transition-colors duration-150 hover:text-fg"
            onClick={() => setShowAdvanced((v) => !v)}
            type="button"
          >
            <i
              className={`${showAdvanced ? 'pi pi-chevron-down' : 'pi pi-chevron-right'} text-[12px] transition-transform duration-150`}
            ></i>
            <span>Advanced</span>
            {!showAdvanced && targetName && targetName !== secretName && (
              <span className="ml-2 text-[12px] font-normal text-fg-secondary opacity-70">
                Target: {targetName}
              </span>
            )}
          </button>

          {showAdvanced && (
            <div className="pt-3">
              <div className="field">
                <label htmlFor="targetName">Kubernetes Secret name</label>
                <InputText
                  id="targetName"
                  value={targetName}
                  onChange={(e) => setTargetName(e.target.value)}
                  className="w-full dialog-input"
                  placeholder={secretName || 'Same as name'}
                />
                <small className="mt-1 block text-[12px] text-fg-secondary">
                  Defaults to the external secret name. Override to use a different name for the
                  Kubernetes Secret.
                </small>
              </div>
            </div>
          )}
        </div>
      </Dialog>

      <StatusDialog
        visible={statusDialog.visible}
        selectedName={statusDialog.selectedName}
        loading={statusDialog.loading}
        detail={statusDialog.detail}
        tone={statusDialog.detail ? getStatusTone(statusDialog.detail.status) : 'info'}
        checkedLabel="Last synced"
        checkedAt={statusDialog.detail?.lastSyncedAt}
        onHide={statusDialog.close}
        onRefresh={statusDialog.refresh}
      />

      <DeleteConfirmDialog
        resourceName={deleteTarget?.name ?? null}
        resourceKind="external secret"
        message={
          deleteTarget && (
            <>
              This will remove <strong>{deleteTarget.name}</strong>. The associated Kubernetes
              secret will also be removed.
            </>
          )
        }
        onHide={() => setDeleteTarget(null)}
        onConfirm={() => {
          if (deleteTarget) deleteSecret(deleteTarget);
          setDeleteTarget(null);
        }}
      />

      <Toast ref={toast} position="bottom-right" />
    </div>
  );
}

// src/app/features/project-console/secret-stores/external-secret-list.component.ts
import { Component, inject, signal, effect, DestroyRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Subscription } from 'rxjs';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { ToastModule } from 'primeng/toast';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { TooltipModule } from 'primeng/tooltip';
import { MenuModule } from 'primeng/menu';
import { SelectModule } from 'primeng/select';
import { TagModule } from 'primeng/tag';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';
import { MessageService, ConfirmationService, MenuItem } from 'primeng/api';
import {
    ExternalSecret,
    ExternalSecretApiService,
    ExternalSecretRequest,
    ExternalSecretDataRef,
    ExternalSecretStatusDetail,
    ExternalSecretCondition
} from '../../../core/api/external-secret-api.service';
import { SecretStoreApiService, SecretStore } from '../../../core/api/secret-store-api.service';
import { ProjectContextService } from '../../../core/context/project-context.service';

const NAME_PATTERN = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

@Component({
    selector: 'app-external-secret-list',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        TableModule,
        ButtonModule,
        DialogModule,
        InputTextModule,
        ToastModule,
        ConfirmDialogModule,
        TooltipModule,
        MenuModule,
        SelectModule,
        TagModule,
        IconFieldModule,
        InputIconModule
    ],
    providers: [MessageService, ConfirmationService],
    templateUrl: './external-secret-list.component.html',
    styleUrls: ['./external-secret-list.component.css']
})
export class ExternalSecretListComponent {
    private readonly api = inject(ExternalSecretApiService);
    private readonly storeApi = inject(SecretStoreApiService);
    private readonly context = inject(ProjectContextService);
    private readonly messageService = inject(MessageService);
    private readonly confirmationService = inject(ConfirmationService);
    private readonly destroyRef = inject(DestroyRef);

    secrets = signal<ExternalSecret[]>([]);
    loading = signal(true);
    readyStores = signal<SecretStore[]>([]);

    private pollTimer: ReturnType<typeof setInterval> | null = null;
    private readonly POLL_INTERVAL_MS = 10_000;
    private activeSub: Subscription | null = null;

    constructor() {
        effect(() => {
            const project = this.context.currentProject();
            if (project) {
                this.loadSecrets();
                this.loadReadyStores();
                this.startPolling();
            } else {
                this.stopPolling();
            }
        });

        this.destroyRef.onDestroy(() => this.stopPolling());
    }

    private startPolling() {
        this.stopPolling();
        this.pollTimer = setInterval(() => {
            if (!this.projectId) return;
            this.activeSub?.unsubscribe();
            this.activeSub = this.api.list(this.projectId).pipe(
                takeUntilDestroyed(this.destroyRef)
            ).subscribe({
                next: (data) => this.mergeSecrets(data),
                error: () => {}
            });
        }, this.POLL_INTERVAL_MS);
    }

    private stopPolling() {
        if (this.pollTimer) {
            clearInterval(this.pollTimer);
            this.pollTimer = null;
        }
        this.activeSub?.unsubscribe();
        this.activeSub = null;
    }

    private mergeSecrets(incoming: ExternalSecret[]) {
        const current = this.secrets();
        if (current.length !== incoming.length) {
            this.secrets.set(incoming);
            return;
        }
        const changed = incoming.some((s, i) => {
            const c = current[i];
            return s.name !== c.name
                || s.status !== c.status
                || s.lastSyncedAt !== c.lastSyncedAt
                || s.lastError !== c.lastError;
        });
        if (changed) {
            this.secrets.set(incoming);
        }
    }

    trackByName(_index: number, es: ExternalSecret): string {
        return es.name;
    }

    // --- Dialog state ---
    dialogVisible = false;
    editMode = false;
    saving = false;

    // --- Status detail ---
    statusDialogVisible = false;
    statusDetail = signal<ExternalSecretStatusDetail | null>(null);
    statusLoading = false;
    selectedSecretName = '';
    private statusPollTimer: ReturnType<typeof setInterval> | null = null;

    // --- Form fields ---
    secretName = '';
    selectedStoreRef = '';
    targetName = '';
    refreshInterval = '1h';
    showAdvanced = false;
    dataMappings: ExternalSecretDataRef[] = [{ secretKey: '', remoteRef: { key: '', property: '' } }];

    readonly refreshOptions = [
        { label: '1 minute', value: '1m' },
        { label: '5 minutes', value: '5m' },
        { label: '15 minutes', value: '15m' },
        { label: '30 minutes', value: '30m' },
        { label: '1 hour', value: '1h' },
        { label: '6 hours', value: '6h' },
        { label: '24 hours', value: '24h' }
    ];

    selectedSecret: ExternalSecret | null = null;

    menuItems: MenuItem[] = [
        {
            label: 'View Status',
            icon: 'pi pi-info-circle',
            command: () => {
                if (this.selectedSecret) this.showStatusDetail(this.selectedSecret);
            }
        },
        {
            label: 'Edit',
            icon: 'pi pi-pencil',
            command: () => {
                if (this.selectedSecret) this.showEditDialog(this.selectedSecret);
            }
        },
        {
            label: 'Delete',
            icon: 'pi pi-trash',
            command: () => {
                if (this.selectedSecret) this.confirmDelete(this.selectedSecret);
            }
        }
    ];

    private get projectId(): string {
        return this.context.currentProject()?.name ?? '';
    }

    loadSecrets() {
        if (!this.projectId) return;
        this.loading.set(true);
        this.api.list(this.projectId).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (data) => {
                this.secrets.set(data);
                this.loading.set(false);
            },
            error: () => {
                this.showError('Failed to load external secrets');
                this.loading.set(false);
            }
        });
    }

    loadReadyStores() {
        if (!this.projectId) return;
        this.storeApi.list(this.projectId).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (stores) => {
                this.readyStores.set(stores.filter(s => s.status === 'Ready'));
            },
            error: () => {}
        });
    }

    // --- Name validation ---

    get nameError(): string {
        if (!this.secretName) return '';
        if (this.secretName.length > 63) return 'Maximum 63 characters';
        if (!NAME_PATTERN.test(this.secretName)) {
            return 'Lowercase letters, numbers and hyphens only (must start/end with alphanumeric)';
        }
        return '';
    }

    // --- Dialog ---

    showCreateDialog() {
        this.loadReadyStores();
        this.resetForm();
        this.editMode = false;
        this.dialogVisible = true;
    }

    showEditDialog(es: ExternalSecret) {
        this.loadReadyStores();
        this.editMode = true;
        this.secretName = es.name;
        this.selectedStoreRef = es.secretStoreRef;
        this.targetName = es.target?.name ?? '';
        this.refreshInterval = es.refreshInterval || '1h';
        this.showAdvanced = this.targetName !== '' && this.targetName !== es.name;
        this.dataMappings = es.data?.length
            ? es.data.map(d => ({
                secretKey: d.secretKey,
                remoteRef: { key: d.remoteRef.key, property: d.remoteRef.property || '' }
            }))
            : [{ secretKey: '', remoteRef: { key: '', property: '' } }];
        this.dialogVisible = true;
    }

    private resetForm() {
        this.secretName = '';
        this.selectedStoreRef = '';
        this.targetName = '';
        this.refreshInterval = '1h';
        this.showAdvanced = false;
        this.dataMappings = [{ secretKey: '', remoteRef: { key: '', property: '' } }];
    }

    addMapping() {
        this.dataMappings = [...this.dataMappings, { secretKey: '', remoteRef: { key: '', property: '' } }];
    }

    removeMapping(index: number) {
        this.dataMappings = this.dataMappings.filter((_, i) => i !== index);
        if (this.dataMappings.length === 0) {
            this.addMapping();
        }
    }

    private buildRequest(): ExternalSecretRequest {
        return {
            name: this.secretName,
            secretStoreRef: this.selectedStoreRef,
            target: { name: this.targetName || this.secretName },
            refreshInterval: this.refreshInterval,
            data: this.dataMappings
                .filter(m => m.secretKey && m.remoteRef.key)
                .map(m => ({
                    secretKey: m.secretKey,
                    remoteRef: {
                        key: m.remoteRef.key,
                        property: m.remoteRef.property || undefined
                    }
                }))
        };
    }

    get formValid(): boolean {
        if (!this.secretName || !this.selectedStoreRef) return false;
        if (this.nameError) return false;
        const validMappings = this.dataMappings.filter(m => m.secretKey && m.remoteRef.key);
        return validMappings.length > 0;
    }

    saveSecret() {
        this.saving = true;
        const request = this.buildRequest();
        const obs = this.editMode
            ? this.api.update(this.projectId, this.secretName, request)
            : this.api.create(this.projectId, request);

        obs.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
            next: () => {
                this.saving = false;
                this.dialogVisible = false;
                this.showSuccess(`External secret "${this.secretName}" ${this.editMode ? 'updated' : 'created'} successfully`);
                this.loadSecrets();
            },
            error: (err) => {
                this.saving = false;
                const detail = err?.error?.error || err?.error?.message || `Failed to ${this.editMode ? 'update' : 'create'} external secret`;
                this.showError(detail);
            }
        });
    }

    confirmDelete(es: ExternalSecret) {
        this.confirmationService.confirm({
            message: `Are you sure you want to delete <strong>${es.name}</strong>? The associated Kubernetes secret will also be removed.`,
            header: 'Delete external secret?',
            icon: 'pi pi-exclamation-triangle',
            acceptLabel: 'Delete',
            rejectLabel: 'Cancel',
            accept: () => {
                this.api.delete(this.projectId, es.name).pipe(
                    takeUntilDestroyed(this.destroyRef)
                ).subscribe({
                    next: () => {
                        this.showSuccess(`External secret "${es.name}" deleted successfully`);
                        this.loadSecrets();
                    },
                    error: (err) => {
                        const detail = err?.error?.error || err?.error?.message || 'Failed to delete external secret';
                        this.showError(detail);
                    }
                });
            }
        });
    }

    // --- Status detail ---

    showStatusDetail(es: ExternalSecret) {
        this.selectedSecretName = es.name;
        this.statusLoading = true;
        this.statusDetail.set(null);
        this.statusDialogVisible = true;

        this.fetchStatusDetail(es.name, es);
        this.startStatusPolling();
    }

    onStatusDialogHide() {
        this.stopStatusPolling();
    }

    private startStatusPolling() {
        this.stopStatusPolling();
        this.statusPollTimer = setInterval(() => {
            if (!this.selectedSecretName || !this.projectId || this.statusLoading) return;
            this.fetchStatusDetail(this.selectedSecretName);
        }, this.POLL_INTERVAL_MS);
    }

    private stopStatusPolling() {
        if (this.statusPollTimer) {
            clearInterval(this.statusPollTimer);
            this.statusPollTimer = null;
        }
    }

    private fetchStatusDetail(name: string, fallback?: ExternalSecret) {
        this.api.getStatus(this.projectId, name).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (detail) => {
                this.statusDetail.set(detail);
                this.statusLoading = false;
            },
            error: () => {
                if (fallback) {
                    this.statusDetail.set({
                        status: fallback.status,
                        conditions: [],
                        lastSyncedAt: fallback.lastSyncedAt,
                        lastError: fallback.lastError
                    });
                }
                this.statusLoading = false;
            }
        });
    }

    refreshStatus() {
        if (!this.selectedSecretName || !this.projectId) return;
        this.statusLoading = true;

        this.api.list(this.projectId).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (data) => {
                this.mergeSecrets(data);
                const fresh = data.find(s => s.name === this.selectedSecretName);
                if (fresh) {
                    this.statusDetail.set({
                        status: fresh.status,
                        conditions: [],
                        lastSyncedAt: fresh.lastSyncedAt,
                        lastError: fresh.lastError
                    });
                    this.fetchStatusDetail(fresh.name);
                } else {
                    this.statusLoading = false;
                }
            },
            error: () => {
                this.showError('Failed to refresh status');
                this.statusLoading = false;
            }
        });
    }

    // --- Helpers ---

    getStatusSeverity(status: string): 'success' | 'danger' | 'warn' | 'info' {
        switch (status) {
            case 'Synced': return 'success';
            case 'Error': return 'danger';
            case 'Pending': return 'warn';
            default: return 'info';
        }
    }

    getConditionIcon(condition: ExternalSecretCondition): string {
        return condition.status === 'True' ? 'pi pi-check-circle' : 'pi pi-times-circle';
    }

    getConditionClass(condition: ExternalSecretCondition): string {
        return condition.status === 'True' ? 'condition-ok' : 'condition-error';
    }

    private showSuccess(detail: string) {
        this.messageService.add({ severity: 'success', summary: 'Success', detail, life: 3000 });
    }

    private showError(detail: string) {
        this.messageService.add({ severity: 'error', summary: 'Error', detail, life: 5000 });
    }
}

<div class="cluster-container">
    <!-- Top Bar -->
    <div class="top-bar">
        <div class="left-group">
            <h1>External Secrets</h1>
            <p-iconfield>
                <p-inputicon styleClass="pi pi-search" />
                <input type="text" pInputText placeholder="Filter secrets..."
                    (input)="dt.filterGlobal($any($event.target).value, 'contains')" />
            </p-iconfield>
        </div>

        <p-button label="Add external secret" (onClick)="showCreateDialog()" styleClass="create-btn">
        </p-button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
        <p-table #dt [value]="secrets()" [loading]="loading()"
            [globalFilterFields]="['name', 'secretStoreRef', 'target.name', 'status']"
            styleClass="minimal-table" dataKey="name">

            <ng-template pTemplate="header">
                <tr>
                    <th style="width: 20%">Name</th>
                    <th style="width: 16%">Secret Store</th>
                    <th style="width: 20%">Target Secret</th>
                    <th style="width: 10%">Status</th>
                    <th style="width: 22%">Last Synced</th>
                    <th style="width: 12%"></th>
                </tr>
            </ng-template>

            <ng-template pTemplate="body" let-es>
                <tr class="cluster-row">
                    <td>
                        <span class="es-name">{{ es.name }}</span>
                    </td>
                    <td>
                        <span class="store-ref-badge">
                            <i class="pi pi-database"></i>
                            {{ es.secretStoreRef }}
                        </span>
                    </td>
                    <td>
                        <span class="target-name">{{ es.target?.name || '-' }}</span>
                    </td>
                    <td>
                        <p-tag [value]="es.status" [severity]="getStatusSeverity(es.status)"
                            [pTooltip]="es.lastError || ''" tooltipPosition="top">
                        </p-tag>
                    </td>
                    <td class="date-cell">
                        @if (es.lastSyncedAt) {
                            {{ es.lastSyncedAt | date:'MMM d, yyyy, h:mm:ss a' }}
                        } @else {
                            -
                        }
                    </td>
                    <td style="text-align: right">
                        <div class="actions">
                            <p-button icon="pi pi-info-circle" [text]="true" [rounded]="true"
                                (onClick)="showStatusDetail(es)"
                                title="View status" aria-label="View status for {{ es.name }}">
                            </p-button>
                            <p-button icon="pi pi-ellipsis-v" [text]="true" [rounded]="true"
                                (onClick)="menu.toggle($event); selectedSecret = es"
                                aria-label="Actions for {{ es.name }}">
                            </p-button>
                            <p-menu #menu [model]="menuItems" [popup]="true" appendTo="body"></p-menu>
                        </div>
                    </td>
                </tr>
            </ng-template>

            <ng-template pTemplate="emptymessage">
                <tr>
                    <td colspan="6" class="empty-message">
                        <div class="empty-state-inline">
                            <i class="pi pi-key"></i>
                            <span>No external secrets configured. Click <strong>Add external secret</strong> to create one.</span>
                        </div>
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>

    <!-- Create / Edit Dialog -->
    <p-dialog [header]="editMode ? 'Edit external secret' : 'Add external secret'" [(visible)]="dialogVisible"
        [modal]="true" [draggable]="false" [resizable]="false" [style]="{ width: '650px' }"
        styleClass="db-dialog" [closable]="true">

        <div class="dialog-content">
            <!-- Name -->
            <div class="field">
                <label for="esName">Name</label>
                <input pInputText id="esName" [(ngModel)]="secretName" class="w-full dialog-input"
                    placeholder="e.g., db-credentials" [disabled]="editMode"
                    [class.input-error]="nameError" />
                @if (nameError) {
                    <small class="field-error">{{ nameError }}</small>
                }
            </div>

            <hr class="divider" />
            <h4 class="section-title">Source</h4>

            <!-- Secret Store -->
            <div class="field">
                <label for="storeRef">Secret Store</label>
                @if (readyStores().length === 0) {
                    <div class="no-stores-hint">
                        <i class="pi pi-info-circle"></i>
                        <span>No ready secret stores available. Create and connect a secret store first.</span>
                    </div>
                } @else {
                    <p-select id="storeRef" [options]="readyStores()" [(ngModel)]="selectedStoreRef"
                        optionLabel="name" optionValue="name" placeholder="Select a secret store"
                        styleClass="w-full" appendTo="body">
                        <ng-template pTemplate="item" let-store>
                            <div class="store-option">
                                <span class="store-option-name">{{ store.name }}</span>
                                <span class="store-option-provider">{{ store.provider }}</span>
                            </div>
                        </ng-template>
                    </p-select>
                }
            </div>

            <!-- Refresh Interval -->
            <div class="field">
                <label for="refreshInterval">Refresh interval</label>
                <p-select id="refreshInterval" [options]="refreshOptions" [(ngModel)]="refreshInterval"
                    optionLabel="label" optionValue="value" styleClass="w-full" appendTo="body">
                </p-select>
            </div>

            <hr class="divider" />
            <h4 class="section-title">Data Mappings</h4>
            <p class="mapping-help">Map keys from the remote secret store to keys in the Kubernetes Secret.</p>

            <div class="mappings-list">
                @for (mapping of dataMappings; track $index) {
                    <div class="mapping-row">
                        <div class="mapping-fields">
                            <div class="mapping-field">
                                <label>Secret Key</label>
                                <input pInputText [(ngModel)]="mapping.secretKey" class="dialog-input"
                                    placeholder="e.g., DB_PASSWORD" />
                            </div>
                            <div class="mapping-field">
                                <label>Remote Key</label>
                                <input pInputText [(ngModel)]="mapping.remoteRef.key" class="dialog-input"
                                    placeholder="e.g., myapp/db" />
                            </div>
                            <div class="mapping-field mapping-field-sm">
                                <label>Property <span class="optional">(opt.)</span></label>
                                <input pInputText [(ngModel)]="mapping.remoteRef.property" class="dialog-input"
                                    placeholder="e.g., password" />
                            </div>
                            <p-button icon="pi pi-times" [text]="true" severity="danger" (onClick)="removeMapping($index)"
                                [disabled]="dataMappings.length <= 1" aria-label="Remove mapping">
                            </p-button>
                        </div>
                    </div>
                }
            </div>
            <p-button icon="pi pi-plus" [text]="true" label="Add mapping" (onClick)="addMapping()"></p-button>

            <!-- Advanced -->
            <hr class="divider" />
            <button class="advanced-toggle" (click)="showAdvanced = !showAdvanced" type="button">
                <i [class]="showAdvanced ? 'pi pi-chevron-down' : 'pi pi-chevron-right'"></i>
                <span>Advanced</span>
                @if (!showAdvanced && targetName && targetName !== secretName) {
                    <span class="advanced-hint">Target: {{ targetName }}</span>
                }
            </button>

            @if (showAdvanced) {
                <div class="advanced-section">
                    <div class="field">
                        <label for="targetName">Kubernetes Secret name</label>
                        <input pInputText id="targetName" [(ngModel)]="targetName" class="w-full dialog-input"
                            [placeholder]="secretName || 'Same as name'" />
                        <small class="field-hint">Defaults to the external secret name. Override to use a different name for the Kubernetes Secret.</small>
                    </div>
                </div>
            }
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions" style="display: flex; gap: var(--db-space-sm); align-items: center; width: 100%;">
                <div class="spacer" style="flex: 1;"></div>
                <p-button severity="secondary" [outlined]="true" label="Cancel" (onClick)="dialogVisible = false" [disabled]="saving"></p-button>
                <p-button severity="primary"
                    [icon]="saving ? 'pi pi-spin pi-spinner' : ''"
                    [label]="editMode ? 'Save' : 'Create'"
                    [disabled]="saving || !formValid"
                    (onClick)="saveSecret()">
                </p-button>
            </div>
        </ng-template>
    </p-dialog>

    <!-- Status Detail Dialog -->
    <p-dialog [header]="'Status: ' + selectedSecretName" [(visible)]="statusDialogVisible"
        [modal]="true" [draggable]="false" [resizable]="false" [style]="{ width: '600px' }"
        styleClass="db-dialog" [closable]="true" (onHide)="onStatusDialogHide()">

        <div class="status-content">
            @if (statusLoading) {
                <div class="status-loading">
                    <i class="pi pi-spin pi-spinner"></i>
                    <span>Loading status...</span>
                </div>
            } @else if (statusDetail(); as detail) {
                <div class="status-summary">
                    <div class="status-row">
                        <span class="status-label">Status</span>
                        <p-tag [value]="detail.status" [severity]="getStatusSeverity(detail.status)"></p-tag>
                    </div>
                    @if (detail.lastSyncedAt) {
                        <div class="status-row">
                            <span class="status-label">Last synced</span>
                            <span class="status-value">{{ detail.lastSyncedAt | date:'MMM d, yyyy, h:mm:ss a' }}</span>
                        </div>
                    }
                </div>

                @if (detail.lastError) {
                    <div class="error-block">
                        <div class="error-block-header">
                            <i class="pi pi-exclamation-triangle"></i>
                            <span>Error details</span>
                        </div>
                        <pre class="error-block-body">{{ detail.lastError }}</pre>
                    </div>
                }

                @if (detail.conditions.length > 0) {
                    <h4 class="section-title conditions-title">Conditions</h4>
                    <div class="conditions-list">
                        @for (cond of detail.conditions; track cond.type) {
                            <div class="condition-item" [class]="getConditionClass(cond)">
                                <div class="condition-header">
                                    <i [class]="getConditionIcon(cond)"></i>
                                    <span class="condition-type">{{ cond.type }}: {{ cond.status === 'True' ? 'True' : 'False' }}</span>
                                    @if (cond.reason) {
                                        <span class="condition-reason-badge">{{ cond.reason }}</span>
                                    }
                                </div>
                                @if (cond.message) {
                                    <pre class="condition-message">{{ cond.message }}</pre>
                                }
                                @if (cond.lastTransitionTime) {
                                    <span class="condition-time">{{ cond.lastTransitionTime | date:'MMM d, yyyy, h:mm:ss a' }}</span>
                                }
                            </div>
                        }
                    </div>
                }
            }
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions" style="display: flex; gap: var(--db-space-sm); align-items: center; width: 100%;">
                <p-button severity="secondary" [outlined]="true" icon="pi pi-refresh" label="Refresh" (onClick)="refreshStatus()" [disabled]="statusLoading"></p-button>
                <div class="spacer" style="flex: 1;"></div>
                <p-button severity="secondary" [outlined]="true" label="Close" (onClick)="statusDialogVisible = false"></p-button>
            </div>
        </ng-template>
    </p-dialog>

    <p-confirmDialog styleClass="db-confirm-dialog" [style]="{width: '440px'}" acceptButtonStyleClass="p-button-danger"
        rejectButtonStyleClass="p-button-text">
    </p-confirmDialog>

    <p-toast position="bottom-right"></p-toast>
</div>
