// src/features/project-console/secret-stores/secret-store-list.tsx
import { useCallback, useState } from 'react';
import { useParams } from 'react-router-dom';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { InputTextarea } from 'primereact/inputtextarea';
import { Checkbox } from 'primereact/checkbox';
import { Toast } from 'primereact/toast';
import {
  secretStoreApi,
  type SecretStore,
  type SecretStoreRequest,
  type SecretStoreStatusDetail,
  type VaultAuthType,
} from '../../../core/api/secret-store-api';
import { apiErrorMessage, formatMediumDateTime } from '../services/service-utils';
import { statusTone } from './secret-status';
import { StatusTag } from '../../../shared/components/status-tag';
import { StatusDialog } from './status-dialog';
import { usePolledResources } from './use-polled-resources';
import { useStatusDialog } from './use-status-dialog';
import { SECTION_TITLE_CLASS, DIVIDER_CLASS } from './constants';
import SearchFilter from '../../../shared/components/search-filter';
import { PageHeader } from '../../../shared/components/page-header';
import { useToastMessages } from '../../../shared/hooks/use-toast-messages';
import { useRowActionsMenu } from '../../../shared/hooks/use-row-actions-menu';
import { k8sNameError } from '../../../shared/utils/k8s-names';
import { DialogFooter } from '../../../shared/components/dialog-footer';
import DeleteConfirmDialog from '../../../shared/components/delete-confirm-dialog';

const MODE_SWITCH_CLASS =
  'mb-4 flex rounded-sm border border-border-light bg-surface-secondary p-1';
const MODE_BTN_CLASS =
  'flex-1 cursor-pointer rounded-xs border-none p-2 transition-all duration-200';
const MODE_BTN_ACTIVE_CLASS = 'bg-surface font-semibold text-fg shadow-[0_1px_3px_rgba(0,0,0,0.1)]';
const MODE_BTN_IDLE_CLASS = 'bg-transparent font-medium text-fg-secondary';

const modeBtnClass = (active: boolean) =>
  `${MODE_BTN_CLASS} ${active ? MODE_BTN_ACTIVE_CLASS : MODE_BTN_IDLE_CLASS}`;

const AUTH_TYPE_OPTIONS: { label: string; value: VaultAuthType }[] = [
  { label: 'Token', value: 'token' },
  { label: 'Kubernetes', value: 'kubernetes' },
];

interface StoreForm {
  storeName: string;
  vaultServer: string;
  vaultPath: string;
  vaultVersion: 'v1' | 'v2';
  caBundle: string;
  authType: VaultAuthType;
  authToken: string;
  authMountPath: string;
  authRole: string;
  isDefault: boolean;
}

const EMPTY_FORM: StoreForm = {
  storeName: '',
  vaultServer: '',
  vaultPath: '',
  vaultVersion: 'v2',
  caBundle: '',
  authType: 'token',
  authToken: '',
  authMountPath: '',
  authRole: '',
  isDefault: false,
};

const getStatusTone = (status: string) => statusTone(status, 'Ready');

const isStoreChanged = (s: SecretStore, c: SecretStore) =>
  s.name !== c.name ||
  s.status !== c.status ||
  s.lastCheckedAt !== c.lastCheckedAt ||
  s.lastError !== c.lastError ||
  s.isDefault !== c.isDefault;

const toStoreFallbackDetail = (store: SecretStore): SecretStoreStatusDetail => ({
  status: store.status,
  conditions: [],
  lastCheckedAt: store.lastCheckedAt,
  lastError: store.lastError,
});

export function SecretStoreList() {
  const { projectId = '' } = useParams<{ projectId: string }>();
  const { toast, showSuccess, showError } = useToastMessages();

  const [globalFilter, setGlobalFilter] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<SecretStore | null>(null);

  // Dialog state
  const [dialogVisible, setDialogVisible] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [testing, setTesting] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<StoreForm>(EMPTY_FORM);

  const patchForm = (patch: Partial<StoreForm>) => setForm((f) => ({ ...f, ...patch }));

  const {
    items: stores,
    loading,
    reload: loadStores,
    merge: mergeStores,
  } = usePolledResources(projectId, secretStoreApi.list, isStoreChanged, () =>
    showError('Failed to load secret stores'),
  );

  const listAndMerge = useCallback(
    () =>
      secretStoreApi.list(projectId).then((data) => {
        mergeStores(data);
        return data;
      }),
    [projectId, mergeStores],
  );

  const statusDialog = useStatusDialog({
    projectId,
    getStatus: secretStoreApi.getStatus,
    listAndMerge,
    toFallbackDetail: toStoreFallbackDetail,
    showError,
  });

  // --- Name validation ---
  const nameError = k8sNameError(form.storeName);

  const formValid = (() => {
    if (!form.storeName || !form.vaultServer || !form.vaultPath) return false;
    if (nameError) return false;
    if (form.authType === 'token' && !form.authToken && !editMode) return false;
    if (form.authType === 'kubernetes' && !form.authRole) return false;
    return true;
  })();

  // --- Dialog ---
  const showCreateDialog = () => {
    setForm(EMPTY_FORM);
    setEditMode(false);
    setDialogVisible(true);
  };

  const showEditDialog = (store: SecretStore) => {
    setEditMode(true);
    setForm({
      storeName: store.name,
      vaultServer: store.vault?.server ?? '',
      vaultPath: store.vault?.path ?? '',
      vaultVersion: store.vault?.version ?? 'v2',
      caBundle: store.vault?.caBundle ?? '',
      authType: store.auth?.type ?? 'token',
      authToken: '',
      authMountPath: store.auth?.config?.mountPath ?? '',
      authRole: store.auth?.config?.role ?? '',
      isDefault: store.isDefault,
    });
    setDialogVisible(true);
  };

  const buildRequest = (): SecretStoreRequest => ({
    name: form.storeName,
    provider: 'vault',
    vault: {
      server: form.vaultServer,
      path: form.vaultPath,
      version: form.vaultVersion,
      caBundle: form.caBundle || undefined,
    },
    auth: {
      type: form.authType,
      config: {
        token: form.authType === 'token' ? form.authToken || undefined : undefined,
        mountPath: form.authType === 'kubernetes' ? form.authMountPath || undefined : undefined,
        role: form.authType === 'kubernetes' ? form.authRole || undefined : undefined,
      },
    },
    isDefault: form.isDefault,
  });

  const testConnection = () => {
    setTesting(true);
    secretStoreApi
      .testConnection(projectId, buildRequest())
      .then(() => {
        setTesting(false);
        showSuccess('Connection successful!');
      })
      .catch((err) => {
        setTesting(false);
        showError(`Connection test failed: ${apiErrorMessage(err, 'Connection failed')}`);
      });
  };

  const saveStore = () => {
    setSaving(true);
    const request = buildRequest();
    const save = editMode
      ? secretStoreApi.update(projectId, form.storeName, request)
      : secretStoreApi.create(projectId, request);

    save
      .then(() => {
        setSaving(false);
        setDialogVisible(false);
        showSuccess(
          `Secret store "${form.storeName}" ${editMode ? 'updated' : 'created'} successfully`,
        );
        loadStores();
      })
      .catch((err) => {
        setSaving(false);
        showError(apiErrorMessage(err, `Failed to ${editMode ? 'update' : 'create'} secret store`));
      });
  };

  const confirmDelete = (store: SecretStore) => setDeleteTarget(store);

  const deleteStore = (store: SecretStore) => {
    secretStoreApi
      .delete(projectId, store.name)
      .then(() => {
        showSuccess(`Secret store "${store.name}" deleted successfully`);
        loadStores();
      })
      .catch((err) => {
        showError(apiErrorMessage(err, 'Failed to delete secret store'));
      });
  };

  const { menuElement, openMenu } = useRowActionsMenu<SecretStore>([
    { label: 'View Status', icon: 'pi pi-info-circle', command: statusDialog.open },
    { label: 'Edit', icon: 'pi pi-pencil', command: showEditDialog },
    { label: 'Delete', icon: 'pi pi-trash', command: confirmDelete },
  ]);

  const dialogFooter = (
    <DialogFooter
      onCancel={() => setDialogVisible(false)}
      onConfirm={saveStore}
      confirmLabel={editMode ? 'Save' : 'Create'}
      confirmDisabled={testing || !formValid}
      cancelDisabled={testing}
      busy={saving}
      leading={
        <Button
          severity="secondary"
          outlined
          icon={testing ? 'pi pi-spin pi-spinner' : 'pi pi-check-circle'}
          label="Test Connection"
          onClick={testConnection}
          disabled={testing || saving || !form.vaultServer}
        />
      }
    />
  );

  return (
    <div>
      {/* Top Bar */}
      <PageHeader
        title="Secret Stores"
        actions={
          <button className="create-btn" onClick={showCreateDialog}>
            <i className="pi pi-plus"></i>
            <span>Add secret store</span>
          </button>
        }
      />

      <SearchFilter
        value={globalFilter}
        onChange={setGlobalFilter}
        placeholder="Filter stores..."
      />

      {/* Data Table */}
      <div className="table-wrapper">
        <DataTable
          value={stores}
          loading={loading}
          globalFilter={globalFilter}
          globalFilterFields={['name', 'provider', 'status', 'vault.server']}
          className="minimal-table"
          dataKey="name"
          rowClassName={() => 'cluster-row'}
          emptyMessage={
            <div className="flex items-center justify-center gap-2 p-8 text-[14px] text-fg-secondary">
              <i className="pi pi-lock text-[1.2rem] opacity-50"></i>
              <span>
                No secret stores configured. Click <strong>Add secret store</strong> to connect one.
              </span>
            </div>
          }
        >
          <Column
            header="Name"
            field="name"
            style={{ width: '20%' }}
            body={(store: SecretStore) => (
              <>
                <span className="font-medium">{store.name}</span>
                {store.isDefault && <StatusTag value="default" tone="info" className="ml-2" />}
              </>
            )}
          />
          <Column
            header="Provider"
            field="provider"
            style={{ width: '12%' }}
            body={(store: SecretStore) => (
              <span className="inline-flex items-center gap-1.5 rounded-xs border border-border-light bg-surface-secondary px-2 py-[3px] text-[12px] font-medium text-fg-secondary capitalize">
                <i className="pi pi-shield text-[11px]"></i>
                {store.provider}
              </span>
            )}
          />
          <Column
            header="Server"
            style={{ width: '28%' }}
            className="max-w-0 overflow-hidden text-[13px] text-ellipsis whitespace-nowrap text-fg-secondary mono"
            body={(store: SecretStore) => (
              <span title={store.vault?.server || ''}>{store.vault?.server || '-'}</span>
            )}
          />
          <Column
            header="Status"
            field="status"
            style={{ width: '10%' }}
            body={(store: SecretStore) => (
              <span title={store.lastError || ''}>
                <StatusTag
                  value={store.status}
                  tone={getStatusTone(store.status)}
                  pulse={store.status === 'Pending'}
                />
              </span>
            )}
          />
          <Column
            header="Last Checked"
            style={{ width: '18%' }}
            className="text-[13px] whitespace-nowrap text-fg-secondary"
            body={(store: SecretStore) =>
              store.lastCheckedAt ? formatMediumDateTime(store.lastCheckedAt) : '-'
            }
          />
          <Column
            style={{ width: '12%', textAlign: 'right' }}
            body={(store: SecretStore) => (
              <div className="actions">
                <Button
                  icon="pi pi-info-circle"
                  text
                  rounded
                  onClick={() => statusDialog.open(store)}
                  title="View status"
                  aria-label={`View status for ${store.name}`}
                />
                <Button
                  icon="pi pi-ellipsis-v"
                  text
                  rounded
                  aria-label={`Actions for ${store.name}`}
                  onClick={(e) => openMenu(store, e)}
                />
              </div>
            )}
          />
        </DataTable>
        {menuElement}
      </div>

      {/* Create / Edit Dialog */}
      <Dialog
        header={editMode ? 'Edit secret store' : 'Add secret store'}
        visible={dialogVisible}
        modal
        draggable={false}
        resizable={false}
        style={{ width: '600px' }}
        className="db-dialog"
        closable
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
      >
        <div className="dialog-content">
          {/* Store Name */}
          <div className="field">
            <label htmlFor="storeName">Store name</label>
            <InputText
              id="storeName"
              value={form.storeName}
              onChange={(e) => patchForm({ storeName: e.target.value })}
              className={`w-full dialog-input${nameError ? ' border-danger!' : ''}`}
              placeholder="e.g., vault-main"
              disabled={editMode}
            />
            {nameError && <small className="mt-1 block text-[12px] text-danger">{nameError}</small>}
          </div>

          <hr className={DIVIDER_CLASS} />
          <h4 className={SECTION_TITLE_CLASS}>Vault Connection</h4>

          {/* Server */}
          <div className="field">
            <label htmlFor="vaultServer">Server URL</label>
            <InputText
              id="vaultServer"
              value={form.vaultServer}
              onChange={(e) => patchForm({ vaultServer: e.target.value })}
              className="w-full dialog-input"
              placeholder="https://vault.example.com:8200"
            />
          </div>

          {/* Path */}
          <div className="field">
            <label htmlFor="vaultPath">Secret path</label>
            <InputText
              id="vaultPath"
              value={form.vaultPath}
              onChange={(e) => patchForm({ vaultPath: e.target.value })}
              className="w-full dialog-input"
              placeholder="e.g., secret"
            />
          </div>

          {/* Version */}
          <div className="field">
            <label id="vaultVersion-label">KV version</label>
            <div
              className={MODE_SWITCH_CLASS}
              role="radiogroup"
              aria-labelledby="vaultVersion-label"
            >
              <button
                className={modeBtnClass(form.vaultVersion === 'v2')}
                onClick={() => patchForm({ vaultVersion: 'v2' })}
                role="radio"
                aria-checked={form.vaultVersion === 'v2'}
              >
                v2
              </button>
              <button
                className={modeBtnClass(form.vaultVersion === 'v1')}
                onClick={() => patchForm({ vaultVersion: 'v1' })}
                role="radio"
                aria-checked={form.vaultVersion === 'v1'}
              >
                v1
              </button>
            </div>
          </div>

          {/* CA Bundle */}
          <div className="field">
            <label htmlFor="caBundle">
              CA Bundle <span className="optional">(optional)</span>
            </label>
            <InputTextarea
              id="caBundle"
              value={form.caBundle}
              onChange={(e) => patchForm({ caBundle: e.target.value })}
              className="w-full dialog-input resize-y text-[12px]! mono"
              placeholder={'-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----'}
              rows={3}
            />
          </div>

          <hr className={DIVIDER_CLASS} />
          <h4 className={SECTION_TITLE_CLASS}>
            Authentication{' '}
            {editMode && <span className="optional">(leave empty to keep existing)</span>}
          </h4>

          {/* Auth Type Switch */}
          <div className={MODE_SWITCH_CLASS} role="radiogroup" aria-label="Authentication type">
            {AUTH_TYPE_OPTIONS.map((opt) => (
              <button
                key={opt.value}
                className={modeBtnClass(form.authType === opt.value)}
                onClick={() => patchForm({ authType: opt.value })}
                role="radio"
                aria-checked={form.authType === opt.value}
              >
                {opt.label}
              </button>
            ))}
          </div>

          {/* Token Auth */}
          {form.authType === 'token' && (
            <div className="field">
              <label htmlFor="authToken">Vault Token</label>
              <InputText
                id="authToken"
                value={form.authToken}
                onChange={(e) => patchForm({ authToken: e.target.value })}
                className="w-full dialog-input"
                type="password"
                placeholder={
                  editMode ? '(existing token preserved - leave empty to keep)' : 'hvs.XXXX...'
                }
              />
            </div>
          )}

          {/* Kubernetes Auth */}
          {form.authType === 'kubernetes' && (
            <>
              <div className="field">
                <label htmlFor="authMountPath">
                  Mount path <span className="optional">(optional)</span>
                </label>
                <InputText
                  id="authMountPath"
                  value={form.authMountPath}
                  onChange={(e) => patchForm({ authMountPath: e.target.value })}
                  className="w-full dialog-input"
                  placeholder="kubernetes"
                />
              </div>
              <div className="field">
                <label htmlFor="authRole">Role</label>
                <InputText
                  id="authRole"
                  value={form.authRole}
                  onChange={(e) => patchForm({ authRole: e.target.value })}
                  className="w-full dialog-input"
                  placeholder="e.g., my-app-role"
                />
              </div>
            </>
          )}

          {/* Options */}
          <hr className={DIVIDER_CLASS} />
          <div className="mb-5 flex items-center gap-2">
            <Checkbox
              checked={form.isDefault}
              onChange={(e) => patchForm({ isDefault: !!e.checked })}
              inputId="isDefault"
            />
            <label htmlFor="isDefault" className="m-0 cursor-pointer text-[14px] text-fg">
              Set as default store for this project
            </label>
          </div>
        </div>
      </Dialog>

      <StatusDialog
        visible={statusDialog.visible}
        selectedName={statusDialog.selectedName}
        loading={statusDialog.loading}
        detail={statusDialog.detail}
        tone={statusDialog.detail ? getStatusTone(statusDialog.detail.status) : 'info'}
        checkedLabel="Last checked"
        checkedAt={statusDialog.detail?.lastCheckedAt}
        onHide={statusDialog.close}
        onRefresh={statusDialog.refresh}
      />

      <DeleteConfirmDialog
        resourceName={deleteTarget?.name ?? null}
        resourceKind="secret store"
        message={
          deleteTarget && (
            <>
              This will remove <strong>{deleteTarget.name}</strong>. This action cannot be undone.
            </>
          )
        }
        onHide={() => setDeleteTarget(null)}
        onConfirm={() => {
          if (deleteTarget) deleteStore(deleteTarget);
          setDeleteTarget(null);
        }}
      />

      <Toast ref={toast} position="bottom-right" />
    </div>
  );
}

// src/app/features/project-console/secret-stores/secret-store-list.component.ts
import { Component, inject, signal, effect, DestroyRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Subscription } from 'rxjs';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { ToastModule } from 'primeng/toast';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { TooltipModule } from 'primeng/tooltip';
import { MenuModule } from 'primeng/menu';
import { SelectModule } from 'primeng/select';
import { TagModule } from 'primeng/tag';
import { CheckboxModule } from 'primeng/checkbox';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';
import { MessageService, ConfirmationService, MenuItem } from 'primeng/api';
import {
    SecretStore,
    SecretStoreApiService,
    SecretStoreRequest,
    SecretStoreStatusDetail,
    SecretStoreCondition,
    VaultAuthType
} from '../../../core/api/secret-store-api.service';
import { ProjectContextService } from '../../../core/context/project-context.service';

const NAME_PATTERN = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

@Component({
    selector: 'app-secret-store-list',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        TableModule,
        ButtonModule,
        DialogModule,
        InputTextModule,
        TextareaModule,
        ToastModule,
        ConfirmDialogModule,
        TooltipModule,
        MenuModule,
        SelectModule,
        TagModule,
        CheckboxModule,
        IconFieldModule,
        InputIconModule
    ],
    providers: [MessageService, ConfirmationService],
    templateUrl: './secret-store-list.component.html',
    styleUrls: ['./secret-store-list.component.css']
})
export class SecretStoreListComponent {
    private readonly api = inject(SecretStoreApiService);
    private readonly context = inject(ProjectContextService);
    private readonly messageService = inject(MessageService);
    private readonly confirmationService = inject(ConfirmationService);
    private readonly destroyRef = inject(DestroyRef);

    stores = signal<SecretStore[]>([]);
    loading = signal(true);

    private pollTimer: ReturnType<typeof setInterval> | null = null;
    private readonly POLL_INTERVAL_MS = 10_000;
    private activeSub: Subscription | null = null;

    constructor() {
        effect(() => {
            const project = this.context.currentProject();
            if (project) {
                this.loadStores();
                this.startPolling();
            } else {
                this.stopPolling();
            }
        });

        this.destroyRef.onDestroy(() => this.stopPolling());
    }

    private startPolling() {
        this.stopPolling();
        this.pollTimer = setInterval(() => {
            if (!this.projectId) return;
            this.activeSub?.unsubscribe();
            this.activeSub = this.api.list(this.projectId).pipe(
                takeUntilDestroyed(this.destroyRef)
            ).subscribe({
                next: (data) => this.mergeStores(data),
                error: () => {}
            });
        }, this.POLL_INTERVAL_MS);
    }

    private stopPolling() {
        if (this.pollTimer) {
            clearInterval(this.pollTimer);
            this.pollTimer = null;
        }
        this.activeSub?.unsubscribe();
        this.activeSub = null;
    }

    private mergeStores(incoming: SecretStore[]) {
        const current = this.stores();
        if (current.length !== incoming.length) {
            this.stores.set(incoming);
            return;
        }
        const changed = incoming.some((s, i) => {
            const c = current[i];
            return s.name !== c.name
                || s.status !== c.status
                || s.lastCheckedAt !== c.lastCheckedAt
                || s.lastError !== c.lastError
                || s.isDefault !== c.isDefault;
        });
        if (changed) {
            this.stores.set(incoming);
        }
    }

    trackByName(_index: number, store: SecretStore): string {
        return store.name;
    }

    // --- Dialog state ---
    dialogVisible = false;
    editMode = false;
    testing = false;
    saving = false;

    // --- Status detail ---
    statusDialogVisible = false;
    statusDetail = signal<SecretStoreStatusDetail | null>(null);
    statusLoading = false;
    selectedStoreName = '';
    private statusPollTimer: ReturnType<typeof setInterval> | null = null;

    // --- Form fields ---
    storeName = '';
    vaultServer = '';
    vaultPath = '';
    vaultVersion: 'v1' | 'v2' = 'v2';
    caBundle = '';
    authType: VaultAuthType = 'token';
    authToken = '';
    authMountPath = '';
    authRole = '';
    isDefault = false;

    readonly versionOptions = [
        { label: 'v2', value: 'v2' },
        { label: 'v1', value: 'v1' }
    ];

    readonly authTypeOptions: { label: string; value: VaultAuthType }[] = [
        { label: 'Token', value: 'token' },
        { label: 'Kubernetes', value: 'kubernetes' }
    ];

    selectedStore: SecretStore | null = null;

    menuItems: MenuItem[] = [
        {
            label: 'View Status',
            icon: 'pi pi-info-circle',
            command: () => {
                if (this.selectedStore) this.showStatusDetail(this.selectedStore);
            }
        },
        {
            label: 'Edit',
            icon: 'pi pi-pencil',
            command: () => {
                if (this.selectedStore) this.showEditDialog(this.selectedStore);
            }
        },
        {
            label: 'Delete',
            icon: 'pi pi-trash',
            command: () => {
                if (this.selectedStore) this.confirmDelete(this.selectedStore);
            }
        }
    ];

    private get projectId(): string {
        return this.context.currentProject()?.name ?? '';
    }

    loadStores() {
        if (!this.projectId) return;
        this.loading.set(true);
        this.api.list(this.projectId).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (data) => {
                this.stores.set(data);
                this.loading.set(false);
            },
            error: () => {
                this.showError('Failed to load secret stores');
                this.loading.set(false);
            }
        });
    }

    // --- Name validation ---

    get nameError(): string {
        if (!this.storeName) return '';
        if (this.storeName.length > 63) return 'Maximum 63 characters';
        if (!NAME_PATTERN.test(this.storeName)) {
            return 'Lowercase letters, numbers and hyphens only (must start/end with alphanumeric)';
        }
        return '';
    }

    // --- Dialog ---

    showCreateDialog() {
        this.resetForm();
        this.editMode = false;
        this.dialogVisible = true;
    }

    showEditDialog(store: SecretStore) {
        this.editMode = true;
        this.storeName = store.name;
        this.vaultServer = store.vault?.server ?? '';
        this.vaultPath = store.vault?.path ?? '';
        this.vaultVersion = store.vault?.version ?? 'v2';
        this.caBundle = store.vault?.caBundle ?? '';
        this.authType = store.auth?.type ?? 'token';
        this.authToken = '';
        this.authMountPath = store.auth?.config?.mountPath ?? '';
        this.authRole = store.auth?.config?.role ?? '';
        this.isDefault = store.isDefault;
        this.dialogVisible = true;
    }

    private resetForm() {
        this.storeName = '';
        this.vaultServer = '';
        this.vaultPath = '';
        this.vaultVersion = 'v2';
        this.caBundle = '';
        this.authType = 'token';
        this.authToken = '';
        this.authMountPath = '';
        this.authRole = '';
        this.isDefault = false;
    }

    private buildRequest(): SecretStoreRequest {
        return {
            name: this.storeName,
            provider: 'vault',
            vault: {
                server: this.vaultServer,
                path: this.vaultPath,
                version: this.vaultVersion,
                caBundle: this.caBundle || undefined,
            },
            auth: {
                type: this.authType,
                config: {
                    token: this.authType === 'token' ? this.authToken || undefined : undefined,
                    mountPath: this.authType === 'kubernetes' ? this.authMountPath || undefined : undefined,
                    role: this.authType === 'kubernetes' ? this.authRole || undefined : undefined,
                }
            },
            isDefault: this.isDefault
        };
    }

    get formValid(): boolean {
        if (!this.storeName || !this.vaultServer || !this.vaultPath) return false;
        if (this.nameError) return false;
        if (this.authType === 'token' && !this.authToken && !this.editMode) return false;
        if (this.authType === 'kubernetes' && !this.authRole) return false;
        return true;
    }

    testConnection() {
        const request = this.buildRequest();
        this.testing = true;

        this.api.testConnection(this.projectId, request).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: () => {
                this.testing = false;
                this.showSuccess('Connection successful!');
            },
            error: (err) => {
                this.testing = false;
                const errorMsg = err?.error?.error || err?.error?.message || 'Connection failed';
                this.showError(`Connection test failed: ${errorMsg}`);
            }
        });
    }

    saveStore() {
        this.saving = true;
        this.performSave(this.buildRequest());
    }

    private performSave(request: SecretStoreRequest) {
        const obs = this.editMode
            ? this.api.update(this.projectId, this.storeName, request)
            : this.api.create(this.projectId, request);

        obs.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
            next: () => {
                this.saving = false;
                this.dialogVisible = false;
                this.showSuccess(`Secret store "${this.storeName}" ${this.editMode ? 'updated' : 'created'} successfully`);
                this.loadStores();
            },
            error: (err) => {
                this.saving = false;
                const detail = err?.error?.error || err?.error?.message || `Failed to ${this.editMode ? 'update' : 'create'} secret store`;
                this.showError(detail);
            }
        });
    }

    confirmDelete(store: SecretStore) {
        this.confirmationService.confirm({
            message: `Are you sure you want to delete <strong>${store.name}</strong>? This action cannot be undone.`,
            header: 'Delete secret store?',
            icon: 'pi pi-exclamation-triangle',
            acceptLabel: 'Delete',
            rejectLabel: 'Cancel',
            accept: () => {
                this.api.delete(this.projectId, store.name).pipe(
                    takeUntilDestroyed(this.destroyRef)
                ).subscribe({
                    next: () => {
                        this.showSuccess(`Secret store "${store.name}" deleted successfully`);
                        this.loadStores();
                    },
                    error: (err) => {
                        const detail = err?.error?.error || err?.error?.message || 'Failed to delete secret store';
                        this.showError(detail);
                    }
                });
            }
        });
    }

    // --- Status detail ---

    showStatusDetail(store: SecretStore) {
        this.selectedStoreName = store.name;
        this.statusLoading = true;
        this.statusDetail.set(null);
        this.statusDialogVisible = true;

        this.fetchStatusDetail(store.name, store);
        this.startStatusPolling();
    }

    onStatusDialogHide() {
        this.stopStatusPolling();
    }

    private startStatusPolling() {
        this.stopStatusPolling();
        this.statusPollTimer = setInterval(() => {
            if (!this.selectedStoreName || !this.projectId || this.statusLoading) return;
            this.fetchStatusDetail(this.selectedStoreName);
        }, this.POLL_INTERVAL_MS);
    }

    private stopStatusPolling() {
        if (this.statusPollTimer) {
            clearInterval(this.statusPollTimer);
            this.statusPollTimer = null;
        }
    }

    private fetchStatusDetail(storeName: string, fallback?: SecretStore) {
        this.api.getStatus(this.projectId, storeName).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (detail) => {
                this.statusDetail.set(detail);
                this.statusLoading = false;
            },
            error: () => {
                if (fallback) {
                    this.statusDetail.set({
                        status: fallback.status,
                        conditions: [],
                        lastCheckedAt: fallback.lastCheckedAt,
                        lastError: fallback.lastError
                    });
                }
                this.statusLoading = false;
            }
        });
    }

    refreshStatus() {
        if (!this.selectedStoreName || !this.projectId) return;
        this.statusLoading = true;

        this.api.list(this.projectId).pipe(
            takeUntilDestroyed(this.destroyRef)
        ).subscribe({
            next: (data) => {
                this.mergeStores(data);
                const freshStore = data.find(s => s.name === this.selectedStoreName);
                if (freshStore) {
                    this.statusDetail.set({
                        status: freshStore.status,
                        conditions: [],
                        lastCheckedAt: freshStore.lastCheckedAt,
                        lastError: freshStore.lastError
                    });
                    this.fetchStatusDetail(freshStore.name);
                } else {
                    this.statusLoading = false;
                }
            },
            error: () => {
                this.showError('Failed to refresh status');
                this.statusLoading = false;
            }
        });
    }

    // --- Helpers ---

    getStatusSeverity(status: string): 'success' | 'danger' | 'warn' | 'info' {
        switch (status) {
            case 'Ready': return 'success';
            case 'Error': return 'danger';
            case 'Pending': return 'warn';
            default: return 'info';
        }
    }

    getConditionIcon(condition: SecretStoreCondition): string {
        return condition.status === 'True' ? 'pi pi-check-circle' : 'pi pi-times-circle';
    }

    getConditionClass(condition: SecretStoreCondition): string {
        return condition.status === 'True' ? 'condition-ok' : 'condition-error';
    }

    private showSuccess(detail: string) {
        this.messageService.add({ severity: 'success', summary: 'Success', detail, life: 3000 });
    }

    private showError(detail: string) {
        this.messageService.add({ severity: 'error', summary: 'Error', detail, life: 5000 });
    }
}

<div class="cluster-container">
    <!-- Top Bar -->
    <div class="top-bar">
        <div class="left-group">
            <h1>Secret Stores</h1>
            <p-iconfield>
                <p-inputicon styleClass="pi pi-search" />
                <input type="text" pInputText placeholder="Filter stores..."
                    (input)="dt.filterGlobal($any($event.target).value, 'contains')" />
            </p-iconfield>
        </div>

        <p-button label="Add secret store" (onClick)="showCreateDialog()" styleClass="create-btn">
        </p-button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
        <p-table #dt [value]="stores()" [loading]="loading()"
            [globalFilterFields]="['name', 'provider', 'status', 'vault.server']"
            styleClass="minimal-table" dataKey="name">

            <ng-template pTemplate="header">
                <tr>
                    <th style="width: 20%">Name</th>
                    <th style="width: 12%">Provider</th>
                    <th style="width: 28%">Server</th>
                    <th style="width: 10%">Status</th>
                    <th style="width: 18%">Last Checked</th>
                    <th style="width: 12%"></th>
                </tr>
            </ng-template>

            <ng-template pTemplate="body" let-store>
                <tr class="cluster-row">
                    <td>
                        <span class="store-name">{{ store.name }}</span>
                        @if (store.isDefault) {
                            <span class="default-badge">default</span>
                        }
                    </td>
                    <td>
                        <span class="provider-badge">
                            <i class="pi pi-shield"></i>
                            {{ store.provider }}
                        </span>
                    </td>
                    <td class="endpoint-cell" [pTooltip]="store.vault?.server || ''" tooltipPosition="top">
                        {{ store.vault?.server || '-' }}
                    </td>
                    <td>
                        <p-tag [value]="store.status" [severity]="getStatusSeverity(store.status)"
                            [pTooltip]="store.lastError || ''" tooltipPosition="top">
                        </p-tag>
                    </td>
                    <td class="date-cell">
                        @if (store.lastCheckedAt) {
                            {{ store.lastCheckedAt | date:'MMM d, yyyy, h:mm:ss a' }}
                        } @else {
                            -
                        }
                    </td>
                    <td style="text-align: right">
                        <div class="actions">
                            <p-button icon="pi pi-info-circle" [text]="true" [rounded]="true"
                                (onClick)="showStatusDetail(store)"
                                title="View status" aria-label="View status for {{ store.name }}">
                            </p-button>
                            <p-button icon="pi pi-ellipsis-v" [text]="true" [rounded]="true"
                                (onClick)="menu.toggle($event); selectedStore = store"
                                aria-label="Actions for {{ store.name }}">
                            </p-button>
                            <p-menu #menu [model]="menuItems" [popup]="true" appendTo="body"></p-menu>
                        </div>
                    </td>
                </tr>
            </ng-template>

            <ng-template pTemplate="emptymessage">
                <tr>
                    <td colspan="6" class="empty-message">
                        <div class="empty-state-inline">
                            <i class="pi pi-lock"></i>
                            <span>No secret stores configured. Click <strong>Add secret store</strong> to connect one.</span>
                        </div>
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>

    <!-- Create / Edit Dialog -->
    <p-dialog [header]="editMode ? 'Edit secret store' : 'Add secret store'" [(visible)]="dialogVisible"
        [modal]="true" [draggable]="false" [resizable]="false" [style]="{ width: '600px' }"
        styleClass="db-dialog" [closable]="true">

        <div class="dialog-content">
            <!-- Store Name -->
            <div class="field">
                <label for="storeName">Store name</label>
                <input pInputText id="storeName" [(ngModel)]="storeName" class="w-full dialog-input"
                    placeholder="e.g., vault-main" [disabled]="editMode"
                    [class.input-error]="nameError" />
                @if (nameError) {
                    <small class="field-error">{{ nameError }}</small>
                }
            </div>

            <hr class="divider" />
            <h4 class="section-title">Vault Connection</h4>

            <!-- Server -->
            <div class="field">
                <label for="vaultServer">Server URL</label>
                <input pInputText id="vaultServer" [(ngModel)]="vaultServer" class="w-full dialog-input"
                    placeholder="https://vault.example.com:8200" />
            </div>

            <!-- Path -->
            <div class="field">
                <label for="vaultPath">Secret path</label>
                <input pInputText id="vaultPath" [(ngModel)]="vaultPath" class="w-full dialog-input"
                    placeholder="e.g., secret" />
            </div>

            <!-- Version -->
            <div class="field">
                <label for="vaultVersion">KV version</label>
                <div class="mode-switch" role="radiogroup" aria-label="KV version">
                    <button class="mode-btn" [class.active]="vaultVersion === 'v2'"
                        (click)="vaultVersion = 'v2'" role="radio" [attr.aria-checked]="vaultVersion === 'v2'">v2</button>
                    <button class="mode-btn" [class.active]="vaultVersion === 'v1'"
                        (click)="vaultVersion = 'v1'" role="radio" [attr.aria-checked]="vaultVersion === 'v1'">v1</button>
                </div>
            </div>

            <!-- CA Bundle -->
            <div class="field">
                <label for="caBundle">CA Bundle <span class="optional">(optional)</span></label>
                <textarea pInputTextarea id="caBundle" [(ngModel)]="caBundle"
                    class="w-full dialog-input credential-input"
                    placeholder="-----BEGIN CERTIFICATE-----&#10;...&#10;-----END CERTIFICATE-----"
                    rows="3"></textarea>
            </div>

            <hr class="divider" />
            <h4 class="section-title">Authentication
                @if (editMode) {
                    <span class="optional">(leave empty to keep existing)</span>
                }
            </h4>

            <!-- Auth Type Switch -->
            <div class="mode-switch" role="radiogroup" aria-label="Authentication type">
                @for (opt of authTypeOptions; track opt.value) {
                    <button class="mode-btn" [class.active]="authType === opt.value"
                        (click)="authType = opt.value" role="radio"
                        [attr.aria-checked]="authType === opt.value">{{ opt.label }}</button>
                }
            </div>

            <!-- Token Auth -->
            @if (authType === 'token') {
                <div class="field">
                    <label for="authToken">Vault Token</label>
                    <input pInputText id="authToken" [(ngModel)]="authToken" class="w-full dialog-input"
                        type="password"
                        [placeholder]="editMode ? '(existing token preserved - leave empty to keep)' : 'hvs.XXXX...'" />
                </div>
            }

            <!-- Kubernetes Auth -->
            @if (authType === 'kubernetes') {
                <div class="field">
                    <label for="authMountPath">Mount path <span class="optional">(optional)</span></label>
                    <input pInputText id="authMountPath" [(ngModel)]="authMountPath" class="w-full dialog-input"
                        placeholder="kubernetes" />
                </div>
                <div class="field">
                    <label for="authRole">Role</label>
                    <input pInputText id="authRole" [(ngModel)]="authRole" class="w-full dialog-input"
                        placeholder="e.g., my-app-role" />
                </div>
            }

            <!-- Options -->
            <hr class="divider" />
            <div class="field checkbox-field">
                <p-checkbox [(ngModel)]="isDefault" [binary]="true" inputId="isDefault"></p-checkbox>
                <label for="isDefault" class="checkbox-label">Set as default store for this project</label>
            </div>
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions" style="display: flex; gap: var(--db-space-sm); align-items: center; width: 100%;">
                <p-button severity="secondary" [outlined]="true"
                    [icon]="testing ? 'pi pi-spin pi-spinner' : 'pi pi-check-circle'"
                    label="Test Connection"
                    (onClick)="testConnection()"
                    [disabled]="testing || saving || !vaultServer">
                </p-button>
                <div class="spacer" style="flex: 1;"></div>
                <p-button severity="secondary" [outlined]="true" label="Cancel" (onClick)="dialogVisible = false" [disabled]="testing || saving"></p-button>
                <p-button severity="primary"
                    [icon]="saving ? 'pi pi-spin pi-spinner' : ''"
                    [label]="editMode ? 'Save' : 'Create'"
                    [disabled]="testing || saving || !formValid"
                    (onClick)="saveStore()">
                </p-button>
            </div>
        </ng-template>
    </p-dialog>

    <!-- Status Detail Dialog -->
    <p-dialog [header]="'Status: ' + selectedStoreName" [(visible)]="statusDialogVisible"
        [modal]="true" [draggable]="false" [resizable]="false" [style]="{ width: '600px' }"
        styleClass="db-dialog" [closable]="true" (onHide)="onStatusDialogHide()">

        <div class="status-content">
            @if (statusLoading) {
                <div class="status-loading">
                    <i class="pi pi-spin pi-spinner"></i>
                    <span>Loading status...</span>
                </div>
            } @else if (statusDetail(); as detail) {
                <div class="status-summary">
                    <div class="status-row">
                        <span class="status-label">Status</span>
                        <p-tag [value]="detail.status" [severity]="getStatusSeverity(detail.status)"></p-tag>
                    </div>
                    @if (detail.lastCheckedAt) {
                        <div class="status-row">
                            <span class="status-label">Last checked</span>
                            <span class="status-value">{{ detail.lastCheckedAt | date:'MMM d, yyyy, h:mm:ss a' }}</span>
                        </div>
                    }
                </div>

                @if (detail.lastError) {
                    <div class="error-block">
                        <div class="error-block-header">
                            <i class="pi pi-exclamation-triangle"></i>
                            <span>Error details</span>
                        </div>
                        <pre class="error-block-body">{{ detail.lastError }}</pre>
                    </div>
                }

                @if (detail.conditions.length > 0) {
                    <h4 class="section-title conditions-title">Conditions</h4>
                    <div class="conditions-list">
                        @for (cond of detail.conditions; track cond.type) {
                            <div class="condition-item" [class]="getConditionClass(cond)">
                                <div class="condition-header">
                                    <i [class]="getConditionIcon(cond)"></i>
                                    <span class="condition-type">{{ cond.type }}: {{ cond.status === 'True' ? 'True' : 'False' }}</span>
                                    @if (cond.reason) {
                                        <span class="condition-reason-badge">{{ cond.reason }}</span>
                                    }
                                </div>
                                @if (cond.message) {
                                    <pre class="condition-message">{{ cond.message }}</pre>
                                }
                                @if (cond.lastTransitionTime) {
                                    <span class="condition-time">{{ cond.lastTransitionTime | date:'MMM d, yyyy, h:mm:ss a' }}</span>
                                }
                            </div>
                        }
                    </div>
                }
            }
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions" style="display: flex; gap: var(--db-space-sm); align-items: center; width: 100%;">
                <p-button severity="secondary" [outlined]="true" icon="pi pi-refresh" label="Refresh" (onClick)="refreshStatus()" [disabled]="statusLoading"></p-button>
                <div class="spacer" style="flex: 1;"></div>
                <p-button severity="secondary" [outlined]="true" label="Close" (onClick)="statusDialogVisible = false"></p-button>
            </div>
        </ng-template>
    </p-dialog>

    <p-confirmDialog styleClass="db-confirm-dialog" [style]="{width: '440px'}" acceptButtonStyleClass="p-button-danger"
        rejectButtonStyleClass="p-button-text">
    </p-confirmDialog>

    <p-toast position="bottom-right"></p-toast>
</div>
