// src/features/admin/identity/users/user-list.tsx
import { useState } from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { InputTextarea } from 'primereact/inputtextarea';
import { Password } from 'primereact/password';
import { MultiSelect } from 'primereact/multiselect';
import { Checkbox } from 'primereact/checkbox';
import { Toast } from 'primereact/toast';
import { identityApi, type User } from '../../../../core/api/identity-api';
import { useIdentityGroups, useIdentityUsers } from '../use-identity';
import EmptyState from '../../../../shared/components/empty-state';
import SearchFilter from '../../../../shared/components/search-filter';
import { PageHeader } from '../../../../shared/components/page-header';
import { useToastMessages } from '../../../../shared/hooks/use-toast-messages';
import { useRowActionsMenu } from '../../../../shared/hooks/use-row-actions-menu';
import { DialogFooter } from '../../../../shared/components/dialog-footer';
import DeleteConfirmDialog from '../../../../shared/components/delete-confirm-dialog';
import { StatusTag } from '../../../../shared/components/status-tag';

export function UserList() {
  const { toast, showSuccess, showError } = useToastMessages();

  const { users, loading, error, refresh: refreshUsers } = useIdentityUsers();
  const { groups: availableGroups } = useIdentityGroups();

  const [globalFilter, setGlobalFilter] = useState('');
  const [userDialog, setUserDialog] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<User | null>(null);
  const [user, setUser] = useState<User>({ username: '', name: '' });
  const [emailInput, setEmailInput] = useState('');
  const [selectedGroups, setSelectedGroups] = useState<string[]>([]);

  const openNew = () => {
    setUser({ username: '', name: '', disabled: false });
    setEmailInput('');
    setSelectedGroups([]);
    setIsEditMode(false);
    setUserDialog(true);
  };

  const editUser = (u: User) => {
    setUser({ ...u, password: '' });
    setEmailInput(u.email ? u.email.join(', ') : '');
    setSelectedGroups(u.groups || []);
    setIsEditMode(true);
    setUserDialog(true);
  };

  const deleteUser = (u: User) => {
    identityApi
      .deleteUser(u.username)
      .then(() => {
        showSuccess('User deleted');
        refreshUsers();
      })
      .catch(() => showError('Failed to delete user'));
  };

  const hideDialog = () => setUserDialog(false);

  const saveUser = () => {
    if (!user.username?.trim()) {
      return;
    }

    const payload: User = {
      ...user,
      email: emailInput.trim() ? emailInput.split(',').map((e) => e.trim()) : [],
      groups: selectedGroups,
    };

    const save = isEditMode
      ? identityApi.updateUser(payload.username, payload)
      : identityApi.createUser(payload);

    save
      .then(() => {
        showSuccess(isEditMode ? 'User updated' : 'User created');
        refreshUsers();
        hideDialog();
      })
      .catch(() => showError(isEditMode ? 'Failed to update user' : 'Failed to create user'));
  };

  const { menuElement, openMenu } = useRowActionsMenu<User>([
    { label: 'Edit', icon: 'pi pi-pencil', command: editUser },
    { separator: true },
    { label: 'Delete', icon: 'pi pi-trash', command: setDeleteTarget },
  ]);

  const dialogFooter = (
    <DialogFooter
      onCancel={hideDialog}
      onConfirm={saveUser}
      confirmLabel={isEditMode ? 'Save' : 'Create'}
      confirmDisabled={!user.name || !user.username}
    />
  );

  return (
    <div>
      <Toast ref={toast} />
      <DeleteConfirmDialog
        resourceName={deleteTarget?.username ?? null}
        resourceKind="user"
        message={
          deleteTarget && (
            <>
              This will permanently remove <strong>{deleteTarget.name}</strong>. This action cannot
              be undone.
            </>
          )
        }
        onHide={() => setDeleteTarget(null)}
        onConfirm={() => {
          if (deleteTarget) deleteUser(deleteTarget);
          setDeleteTarget(null);
        }}
      />

      {/* Top Bar */}
      <PageHeader
        title="Users"
        actions={
          <button className="create-btn" onClick={openNew}>
            <i className="pi pi-plus"></i>
            <span>Create user</span>
          </button>
        }
      />

      {error && users.length === 0 ? (
        <EmptyState
          icon="pi pi-exclamation-triangle"
          title="Failed to load users"
          description="The user list could not be retrieved. Check your connection and try again."
          action={
            <button className="btn-secondary mt-3" onClick={refreshUsers}>
              <i className="pi pi-refresh"></i>
              <span>Retry</span>
            </button>
          }
        />
      ) : (
        <>
          <SearchFilter
            value={globalFilter}
            onChange={setGlobalFilter}
            placeholder="Filter users..."
          />

          {/* Data Table */}
          <div className="table-wrapper">
            <DataTable
              value={users}
              loading={loading}
              globalFilter={globalFilter}
              globalFilterFields={['name', 'email']}
              className="minimal-table"
              emptyMessage="No users found."
            >
              <Column
                header="Name"
                field="name"
                style={{ width: '20%' }}
                body={(u: User) => <span className="font-medium">{u.name}</span>}
              />
              <Column
                header="Email"
                style={{ width: '25%' }}
                body={(u: User) => u.email?.join(', ') || '-'}
              />
              <Column
                header="Groups"
                style={{ width: '25%' }}
                body={(u: User) => (
                  <div className="flex flex-wrap items-center gap-1.5">
                    {u.groups?.slice(0, 3).map((group) => (
                      <span key={group} className="okdp-tag">
                        {group}
                      </span>
                    ))}
                    {(u.groups?.length ?? 0) > 3 && (
                      <span className="text-xs text-fg-muted">+{u.groups!.length - 3}</span>
                    )}
                  </div>
                )}
              />
              <Column
                header="Status"
                style={{ width: '15%' }}
                body={(u: User) =>
                  u.disabled ? (
                    <StatusTag value="Disabled" tone="neutral" />
                  ) : (
                    <StatusTag value="Active" tone="success" />
                  )
                }
              />
              <Column
                style={{ width: '15%', textAlign: 'right' }}
                body={(u: User) => (
                  <div className="actions">
                    <Button icon="pi pi-ellipsis-v" text rounded onClick={(e) => openMenu(u, e)} />
                  </div>
                )}
              />
            </DataTable>
            {menuElement}
          </div>
        </>
      )}

      {/* Create/Edit Dialog */}
      <Dialog
        header={isEditMode ? 'Edit user' : 'Create new user'}
        visible={userDialog}
        modal
        draggable={false}
        resizable={false}
        style={{ width: '500px' }}
        className="db-dialog"
        closable
        onHide={hideDialog}
        footer={dialogFooter}
      >
        <div className="dialog-content">
          <div className="field">
            <label htmlFor="username">Username</label>
            <InputText
              id="username"
              value={user.username}
              onChange={(e) => setUser((u) => ({ ...u, username: e.target.value }))}
              className="w-full dialog-input"
              placeholder="e.g., john.doe"
              disabled={isEditMode}
            />
          </div>

          <div className="field">
            <label htmlFor="name">Display Name</label>
            <InputText
              id="name"
              value={user.name}
              onChange={(e) => setUser((u) => ({ ...u, name: e.target.value }))}
              className="w-full dialog-input"
              placeholder="e.g., John Doe"
            />
          </div>

          <div className="field">
            <label htmlFor="email">
              Email <span className="optional">(comma-separated for multiple)</span>
            </label>
            <InputText
              id="email"
              value={emailInput}
              onChange={(e) => setEmailInput(e.target.value)}
              className="w-full dialog-input"
              placeholder="e.g., john@example.com"
            />
          </div>

          <div className="field">
            <label htmlFor="password">
              Password{' '}
              {isEditMode && <span className="optional">(leave empty to keep current)</span>}
            </label>
            <Password
              value={user.password ?? ''}
              onChange={(e) => setUser((u) => ({ ...u, password: e.target.value }))}
              toggleMask
              feedback={false}
              className="w-full"
            />
          </div>

          <div className="field">
            <label htmlFor="groups">Groups</label>
            <MultiSelect
              options={availableGroups}
              value={selectedGroups}
              onChange={(e) => setSelectedGroups(e.value)}
              optionLabel="name"
              optionValue="name"
              placeholder="Select groups"
              style={{ width: '100%' }}
              appendTo={document.body}
              display="chip"
            />
          </div>

          <div className="field">
            <label htmlFor="comment">
              Comment <span className="optional">(optional)</span>
            </label>
            <InputTextarea
              id="comment"
              value={user.comment ?? ''}
              onChange={(e) => setUser((u) => ({ ...u, comment: e.target.value }))}
              rows={3}
              className="w-full dialog-input"
              placeholder="Add a note about this user..."
            />
          </div>

          <div className="field-checkbox">
            <Checkbox
              checked={!!user.disabled}
              onChange={(e) => setUser((u) => ({ ...u, disabled: !!e.checked }))}
              inputId="disabled"
            />
            <label htmlFor="disabled">Disable account</label>
          </div>
        </div>
      </Dialog>
    </div>
  );
}

// src/app/features/admin/identity/users/user-list.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { PasswordModule } from 'primeng/password';
import { MultiSelectModule } from 'primeng/multiselect';
import { CheckboxModule } from 'primeng/checkbox';
import { TagModule } from 'primeng/tag';
import { MenuModule } from 'primeng/menu';
import { FormsModule } from '@angular/forms';
import { IdentityService, User } from '../../../../core/services/identity.service';
import { ConfirmationService, MessageService, MenuItem } from 'primeng/api';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { ToastModule } from 'primeng/toast';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [
    CommonModule,
    TableModule,
    ButtonModule,
    DialogModule,
    InputTextModule,
    TextareaModule,
    PasswordModule,
    MultiSelectModule,
    CheckboxModule,
    TagModule,
    MenuModule,
    FormsModule,
    ConfirmDialogModule,
    ToastModule,
    IconFieldModule,
    InputIconModule
  ],
  providers: [ConfirmationService, MessageService],
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.css']
})
export class UserListComponent {
  private readonly identityService = inject(IdentityService);
  private readonly messageService = inject(MessageService);
  private readonly confirmationService = inject(ConfirmationService);

  // Consume signals directly from service
  readonly users = this.identityService.users;
  readonly availableGroups = this.identityService.groups;
  readonly loading = this.identityService.usersLoading;

  userDialog = false;
  submitted = false;
  isEditMode = false;

  user: User = { username: '', name: '' };
  emailInput = '';
  selectedGroups: string[] = [];
  selectedUser: User | null = null;

  menuItems: MenuItem[] = [
    {
      label: 'Edit',
      icon: 'pi pi-pencil',
      command: () => {
        if (this.selectedUser) {
          this.editUser(this.selectedUser);
        }
      }
    },
    { separator: true },
    {
      label: 'Delete',
      icon: 'pi pi-trash',
      command: () => {
        if (this.selectedUser) {
          this.deleteUser(this.selectedUser);
        }
      }
    }
  ];

  openNew() {
    this.user = { username: '', name: '', disabled: false };
    this.emailInput = '';
    this.selectedGroups = [];
    this.submitted = false;
    this.isEditMode = false;
    this.userDialog = true;
  }

  editUser(user: User) {
    this.user = { ...user, password: '' };
    this.emailInput = user.email ? user.email.join(', ') : '';
    this.selectedGroups = user.groups || [];
    this.userDialog = true;
    this.isEditMode = true;
  }

  deleteUser(user: User) {
    this.confirmationService.confirm({
      message: `Are you sure you want to delete <strong>${user.name} </strong>? This action cannot be undone.`,
      header: 'Delete user?',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Delete',
      rejectLabel: 'Cancel',
      accept: () => {
        this.identityService.deleteUser(user.username).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'User deleted' });
            // No need to manually reload - service auto-refreshes
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to delete user' });
          }
        });
      }
    });
  }


  hideDialog() {
    this.userDialog = false;
    this.submitted = false;
  }

  saveUser() {
    this.submitted = true;

    if (this.user.username?.trim()) {
      if (this.emailInput && this.emailInput.trim()) {
        this.user.email = this.emailInput.split(',').map(e => e.trim());
      } else {
        this.user.email = [];
      }

      this.user.groups = this.selectedGroups;

      if (this.isEditMode) {
        this.identityService.updateUser(this.user.username, this.user).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'User updated' });
            this.hideDialog();
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to update user' });
          }
        });
      } else {
        this.identityService.createUser(this.user).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'User created' });
            this.hideDialog();
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to create user' });
          }
        });
      }
    }
  }
}


<div class="user-container">
    <p-toast></p-toast>
    <p-confirmDialog styleClass="db-confirm-dialog" [style]="{width: '400px'}" acceptButtonStyleClass="p-button-danger"
        rejectButtonStyleClass="p-button-text">
    </p-confirmDialog>

    <!-- Top Bar -->
    <div class="top-bar">
        <div class="left-group">
            <h1>Users</h1>
            <p-iconfield>
                <p-inputicon styleClass="pi pi-search" />
                <input type="text" pInputText placeholder="Filter users..."
                    (input)="dt.filterGlobal($any($event.target).value, 'contains')" />
            </p-iconfield>
        </div>

        <p-button label="Create user" (onClick)="openNew()" styleClass="create-btn">
        </p-button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
        <p-table #dt [value]="users()" [loading]="loading()" [globalFilterFields]="['name', 'email']"
            styleClass="minimal-table">

            <ng-template pTemplate="header">
                <tr>
                    <th style="width: 20%">Name</th>
                    <th style="width: 25%">Email</th>
                    <th style="width: 25%">Groups</th>
                    <th style="width: 15%">Status</th>
                    <th style="width: 15%"></th>
                </tr>
            </ng-template>

            <ng-template pTemplate="body" let-user>
                <tr class="user-row">
                    <td>
                        <div class="user-info">
                            <span class="user-name">{{ user.name }}</span>
                        </div>
                    </td>
                    <td class="email-cell">
                        {{ user.email?.join(', ') || '-' }}
                    </td>
                    <td>
                        <div class="groups-list">
                            @for (group of user.groups?.slice(0, 3); track group) {
                            <span class="group-badge">{{ group }}</span>
                            }
                            @if (user.groups?.length > 3) {
                            <span class="group-more">+{{ user.groups.length - 3 }}</span>
                            }
                        </div>
                    </td>
                    <td>
                        @if (user.disabled) {
                        <span class="status-badge disabled">Disabled</span>
                        } @else {
                        <span class="status-badge active">Active</span>
                        }
                    </td>
                    <td style="text-align: right">
                        <div class="actions">
                            <p-button icon="pi pi-ellipsis-v" [text]="true" [rounded]="true"
                                (onClick)="menu.toggle($event); selectedUser = user">
                            </p-button>
                            <p-menu #menu [model]="menuItems" [popup]="true" appendTo="body"></p-menu>
                        </div>
                    </td>
                </tr>
            </ng-template>

            <ng-template pTemplate="emptymessage">
                <tr>
                    <td colspan="5" class="empty-message">
                        No users found.
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>

    <!-- Create/Edit Dialog -->
    <p-dialog [header]="isEditMode ? 'Edit user' : 'Create new user'" [(visible)]="userDialog" [modal]="true"
        [draggable]="false" [resizable]="false" [style]="{ width: '500px' }" styleClass="db-dialog" [closable]="true">

        <div class="dialog-content">
            <div class="field">
                <label for="username">Username</label>
                <input pInputText id="username" [(ngModel)]="user.username" class="w-full dialog-input"
                    placeholder="e.g., john.doe" [disabled]="isEditMode" />
                <small class="p-error" *ngIf="submitted && !user.username">Username is required.</small>
            </div>

            <div class="field">
                <label for="name">Display Name</label>
                <input pInputText id="name" [(ngModel)]="user.name" class="w-full dialog-input"
                    placeholder="e.g., John Doe" />
            </div>

            <div class="field">
                <label for="email">Email <span class="optional">(comma-separated for multiple)</span></label>
                <input pInputText id="email" [(ngModel)]="emailInput" class="w-full dialog-input"
                    placeholder="e.g., john@example.com" />
            </div>

            <div class="field">
                <label for="password">Password <span class="optional" *ngIf="isEditMode">(leave empty to keep
                        current)</span></label>
                <p-password [(ngModel)]="user.password" [toggleMask]="true" [feedback]="false" styleClass="w-full">
                </p-password>
            </div>

            <div class="field">
                <label for="groups">Groups</label>
                <p-multiselect [options]="availableGroups()" [(ngModel)]="selectedGroups" optionLabel="name"
                    optionValue="name" placeholder="Select groups" [style]="{'width':'100%'}" appendTo="body"
                    display="chip">
                </p-multiselect>
            </div>

            <div class="field">
                <label for="comment">Comment <span class="optional">(optional)</span></label>
                <textarea pInputTextarea id="comment" [(ngModel)]="user.comment" rows="3" class="w-full dialog-input"
                    placeholder="Add a note about this user..."></textarea>
            </div>

            <div class="field-checkbox">
                <p-checkbox [(ngModel)]="user.disabled" [binary]="true" inputId="disabled"></p-checkbox>
                <label for="disabled">Disable account</label>
            </div>
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions">
                <p-button severity="secondary" [outlined]="true" label="Cancel" (onClick)="hideDialog()"></p-button>
                <p-button severity="primary" [disabled]="!user.name || !user.username" (onClick)="saveUser()" [label]="isEditMode ? 'Save' : 'Create'"></p-button>
            </div>
        </ng-template>
    </p-dialog>
</div>
