// src/app/shared/components/profile-list-editor.component.ts
import {
    Component,
    Input,
    Output,
    EventEmitter,
    OnChanges,
    SimpleChanges,
    signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SelectModule } from 'primeng/select';
import { InputNumberModule } from 'primeng/inputnumber';
import { ToggleSwitchModule } from 'primeng/toggleswitch';
import { PanelModule } from 'primeng/panel';
import { ButtonModule } from 'primeng/button';

export interface Profile {
    type: string;
    image: string;
    cpuRequest: number;
    cpuLimit: number;
    memoryRequestGi: number;
    memoryLimitGi: number;
    gpuEnabled: boolean;
    gpuCount: number;
}

const DEFAULT_PROFILE: Profile = {
    type: '',
    image: '',
    cpuRequest: 0.5,
    cpuLimit: 2.0,
    memoryRequestGi: 1,
    memoryLimitGi: 4,
    gpuEnabled: false,
    gpuCount: 1,
};

@Component({
    selector: 'app-profile-list-editor',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        SelectModule,
        InputNumberModule,
        ToggleSwitchModule,
        PanelModule,
        ButtonModule,
    ],
    template: `
        <div class="profile-list">
            @for (profile of profiles(); track $index) {
                <div class="profile-card">
                    <div class="profile-header">
                        <div class="profile-header-left">
                            <span class="profile-number">{{ $index + 1 }}</span>
                            <span class="profile-label">Profile {{ $index + 1 }}</span>
                        </div>
                        <p-button icon="pi pi-times" [text]="true" [rounded]="true" severity="danger" 
                            (onClick)="removeProfile($index)" title="Remove this profile">
                        </p-button>
                    </div>

                    <div class="profile-body">
                        <div class="field-row-2">
                            <div class="field">
                                <label>Type</label>
                                <p-select [(ngModel)]="profile.type"
                                    [options]="profileTypeOptions"
                                    optionLabel="label" optionValue="value"
                                    placeholder="Select type"
                                    appendTo="body"
                                    styleClass="w-full"
                                    (ngModelChange)="onTypeChange($index)"></p-select>
                            </div>
                            <div class="field">
                                <label>Image</label>
                                <p-select [(ngModel)]="profile.image"
                                    [options]="getImagesForType(profile.type)"
                                    optionLabel="label" optionValue="image"
                                    placeholder="Select image"
                                    [disabled]="!profile.type"
                                    appendTo="body"
                                    styleClass="w-full"
                                    (ngModelChange)="emitChange()"></p-select>
                            </div>
                        </div>

                        <p-panel header="Resources" [toggleable]="true" [collapsed]="true"
                            styleClass="resource-panel">
                            <div class="field-row-2">
                                <div class="field">
                                    <label>CPU Request (vCPU)</label>
                                    <p-inputNumber [(ngModel)]="profile.cpuRequest"
                                        [showButtons]="true" buttonLayout="horizontal"
                                        [step]="0.25" [min]="0.25" [max]="16"
                                        [minFractionDigits]="1" [maxFractionDigits]="2"
                                        incrementButtonIcon="pi pi-plus" decrementButtonIcon="pi pi-minus"
                                        styleClass="w-full"
                                        (ngModelChange)="emitChange()"></p-inputNumber>
                                </div>
                                <div class="field">
                                    <label>CPU Limit (vCPU)</label>
                                    <p-inputNumber [(ngModel)]="profile.cpuLimit"
                                        [showButtons]="true" buttonLayout="horizontal"
                                        [step]="0.25" [min]="0.25" [max]="64"
                                        [minFractionDigits]="1" [maxFractionDigits]="2"
                                        incrementButtonIcon="pi pi-plus" decrementButtonIcon="pi pi-minus"
                                        styleClass="w-full"
                                        (ngModelChange)="emitChange()"></p-inputNumber>
                                </div>
                            </div>
                            <div class="field-row-2">
                                <div class="field">
                                    <label>Memory Request (GiB)</label>
                                    <p-inputNumber [(ngModel)]="profile.memoryRequestGi"
                                        [showButtons]="true" buttonLayout="horizontal"
                                        [step]="0.25" [min]="0.25" [max]="64"
                                        [minFractionDigits]="1" [maxFractionDigits]="2"
                                        incrementButtonIcon="pi pi-plus" decrementButtonIcon="pi pi-minus"
                                        styleClass="w-full"
                                        (ngModelChange)="emitChange()"></p-inputNumber>
                                </div>
                                <div class="field">
                                    <label>Memory Limit (GiB)</label>
                                    <p-inputNumber [(ngModel)]="profile.memoryLimitGi"
                                        [showButtons]="true" buttonLayout="horizontal"
                                        [step]="0.25" [min]="0.25" [max]="256"
                                        [minFractionDigits]="1" [maxFractionDigits]="2"
                                        incrementButtonIcon="pi pi-plus" decrementButtonIcon="pi pi-minus"
                                        styleClass="w-full"
                                        (ngModelChange)="emitChange()"></p-inputNumber>
                                </div>
                            </div>
                            <div class="field">
                                <label>GPU</label>
                                <div class="gpu-row">
                                    <p-toggleSwitch [(ngModel)]="profile.gpuEnabled"
                                        (ngModelChange)="emitChange()"></p-toggleSwitch>
                                    @if (profile.gpuEnabled) {
                                        <p-inputNumber [(ngModel)]="profile.gpuCount"
                                            [showButtons]="true" [min]="1" [max]="8"
                                            styleClass="gpu-count"
                                            (ngModelChange)="emitChange()"></p-inputNumber>
                                    }
                                </div>
                            </div>
                        </p-panel>
                    </div>
                </div>
            }

            <p-button label="Add profile" icon="pi pi-plus" [outlined]="true" severity="secondary" styleClass="w-full" (onClick)="addProfile()"></p-button>
        </div>
    `,
    styles: [`
        .profile-list {
            display: flex;
            flex-direction: column;
            gap: var(--db-space-md);
        }
        .profile-card {
            border: 1px solid var(--db-border-light);
            border-radius: var(--db-radius-xl);
            overflow: hidden;
            background: var(--db-bg-primary);
            box-shadow: 0 2px 8px rgba(0,0,0,0.02);
            transition: box-shadow 0.3s ease, border-color 0.3s ease, transform var(--db-transition-spring);
            animation: fadeInUp var(--db-transition-spring) backwards;
        }
        .profile-card:hover {
            box-shadow: 0 8px 24px rgba(0,0,0,0.06);
            border-color: var(--db-primary-200);
            transform: translateY(-2px);
        }
        .profile-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 16px;
            background: var(--db-bg-secondary);
            border-bottom: 1px solid var(--db-border-light);
        }
        .profile-header-left {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .profile-number {
            width: 24px;
            height: 24px;
            border-radius: var(--db-radius-sm);
            background: var(--db-primary);
            color: white;
            font-size: 12px;
            font-weight: 600;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .profile-label {
            font-weight: 700;
            font-size: 15px;
            color: var(--db-text-primary);
            letter-spacing: -0.02em;
        }
        .remove-btn {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 32px;
            height: 32px;
            border: 1px solid var(--db-border-light);
            background: var(--db-bg-primary);
            border-radius: var(--db-radius-md);
            cursor: pointer;
            color: var(--db-text-secondary);
            transition: all var(--db-transition-fast);
        }
        .remove-btn:hover {
            background: var(--db-accent-red-light);
            color: var(--db-accent-red);
        }
        .profile-body {
            padding: 16px;
            display: flex;
            flex-direction: column;
            gap: 16px;
        }
        .field-row-2 {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 14px;
        }
        .field {
            display: flex;
            flex-direction: column;
            gap: 6px;
        }
        .field label {
            font-weight: 600;
            font-size: 14px;
            color: var(--db-text-secondary);
            letter-spacing: -0.01em;
        }
        .gpu-row {
            display: flex;
            align-items: center;
            gap: 14px;
        }
        .add-profile-btn {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 14px 20px;
            background: var(--db-bg-secondary);
            border: 1px solid var(--db-border-light);
            border-radius: var(--db-radius-xl);
            cursor: pointer;
            color: var(--db-text-secondary);
            font-size: 15px;
            font-weight: 600;
            font-family: inherit;
            transition: all var(--db-transition-base);
        }
        .add-profile-btn:hover {
            border-color: var(--db-primary-300);
            color: var(--db-primary);
            background: var(--db-primary-50);
        }
        .add-icon-circle {
            width: 28px;
            height: 28px;
            border-radius: 50%;
            background: var(--db-bg-tertiary);
            display: flex;
            align-items: center;
            justify-content: center;
            transition: background var(--db-transition-base);
        }
        .add-profile-btn:hover .add-icon-circle {
            background: var(--db-primary-100);
        }
        .add-icon-circle i {
            font-size: 11px;
        }
        :host ::ng-deep .gpu-count {
            width: 120px;
        }
        :host ::ng-deep .resource-panel .p-panel-header {
            padding: 10px 0;
            background: transparent;
            border: none;
            border-top: 1px solid var(--db-border-light);
        }
        :host ::ng-deep .resource-panel .p-panel-content {
            padding: 14px 0 0 0;
            border: none;
            display: flex;
            flex-direction: column;
            gap: 14px;
        }
        :host ::ng-deep .resource-panel .p-panel-title {
            font-size: 13px;
            font-weight: 500;
            color: var(--db-text-secondary);
        }
    `]
})
export class ProfileListEditorComponent implements OnChanges {
    @Input() profileImages: Record<string, { label: string; image: string }[]> = {};
    @Input() initialProfiles: Profile[] = [];
    @Output() profilesChange = new EventEmitter<Profile[]>();

    profiles = signal<Profile[]>([]);

    ngOnChanges(changes: SimpleChanges) {
        if (changes['initialProfiles'] && this.initialProfiles.length > 0) {
            this.profiles.set(this.initialProfiles.map(p => ({ ...DEFAULT_PROFILE, ...p })));
            this.emitChange();
        }
    }

    profileTypeOptions = [
        { label: 'JupyterLab', value: 'jupyterlab' },
        { label: 'VSCode', value: 'vscode' },
        { label: 'RStudio', value: 'rstudio' },
    ];

    getImagesForType(type: string): { label: string; image: string }[] {
        return this.profileImages[type] || [];
    }

    addProfile() {
        this.profiles.update(list => [...list, { ...DEFAULT_PROFILE }]);
        this.emitChange();
    }

    removeProfile(index: number) {
        this.profiles.update(list => list.filter((_, i) => i !== index));
        this.emitChange();
    }

    onTypeChange(index: number) {
        this.profiles.update(list => {
            const updated = [...list];
            updated[index] = { ...updated[index], image: '' };
            return updated;
        });
        this.emitChange();
    }

    emitChange() {
        this.profilesChange.emit(this.profiles());
    }
}

// src/shared/components/profile-list-editor.tsx
import { useEffect, useRef, useState } from 'react';
import { Button } from 'primereact/button';
import { Dropdown } from 'primereact/dropdown';
import { InputNumber } from 'primereact/inputnumber';
import { InputSwitch } from 'primereact/inputswitch';
import { Panel } from 'primereact/panel';

/* The resource-panel class scopes the PrimeReact Panel overrides in
   the PrimeReact overrides section of styles.css. */
const FIELD_CLASS = 'mb-5 flex flex-col gap-1.5';
const FIELD_LABEL_CLASS = 'block text-[14px] font-semibold tracking-[-0.01em] text-fg-secondary';
const FIELD_ROW_2_CLASS = 'grid grid-cols-2 gap-3.5';

export interface Profile {
  type: string;
  image: string;
  cpuRequest: number;
  cpuLimit: number;
  memoryRequestGi: number;
  memoryLimitGi: number;
  gpuEnabled: boolean;
  gpuCount: number;
}

const DEFAULT_PROFILE: Profile = {
  type: '',
  image: '',
  cpuRequest: 0.5,
  cpuLimit: 2.0,
  memoryRequestGi: 1,
  memoryLimitGi: 4,
  gpuEnabled: false,
  gpuCount: 1,
};

const PROFILE_TYPE_OPTIONS = [
  { label: 'JupyterLab', value: 'jupyterlab' },
  { label: 'VSCode', value: 'vscode' },
  { label: 'RStudio', value: 'rstudio' },
];

// Stable default — an inline `[]` default would change identity on every
// parent render and needlessly re-run the adoption effect.
const NO_PROFILES: Profile[] = [];

/* Each row carries a stable id so React keys survive removals — keying by
   index would shift the uncontrolled Panel collapse state to the wrong card.
   The id is stripped before onProfilesChange. */
interface ProfileRow {
  id: string;
  profile: Profile;
}

export interface ProfileListEditorProps {
  profileImages: Record<string, { label: string; image: string }[]>;
  initialProfiles?: Profile[];
  onProfilesChange: (profiles: Profile[]) => void;
}

interface NumberFieldProps {
  label: string;
  value: number;
  step: number;
  min: number;
  max: number;
  onChange: (value: number) => void;
}

function ResourceNumberField({ label, value, step, min, max, onChange }: NumberFieldProps) {
  return (
    <div className={FIELD_CLASS}>
      <label className={FIELD_LABEL_CLASS}>{label}</label>
      <InputNumber
        value={value}
        showButtons
        buttonLayout="horizontal"
        step={step}
        min={min}
        max={max}
        minFractionDigits={1}
        maxFractionDigits={2}
        incrementButtonIcon="pi pi-plus"
        decrementButtonIcon="pi pi-minus"
        className="w-full"
        onValueChange={(e) => onChange(e.value ?? min)}
      />
    </div>
  );
}

export function ProfileListEditor({
  profileImages,
  initialProfiles = NO_PROFILES,
  onProfilesChange,
}: ProfileListEditorProps) {
  const [rows, setRows] = useState<ProfileRow[]>([]);

  const onProfilesChangeRef = useRef(onProfilesChange);
  onProfilesChangeRef.current = onProfilesChange;

  // Adopt incoming profiles (legacy ngOnChanges behavior)
  useEffect(() => {
    if (initialProfiles.length > 0) {
      setRows(
        initialProfiles.map((p) => ({
          id: crypto.randomUUID(),
          profile: { ...DEFAULT_PROFILE, ...p },
        })),
      );
    }
  }, [initialProfiles]);

  useEffect(() => {
    onProfilesChangeRef.current(rows.map((r) => r.profile));
  }, [rows]);

  const getImagesForType = (type: string) => profileImages[type] || [];

  const updateProfile = (index: number, patch: Partial<Profile>) => {
    setRows((list) =>
      list.map((r, i) => (i === index ? { ...r, profile: { ...r.profile, ...patch } } : r)),
    );
  };

  const addProfile = () =>
    setRows((list) => [...list, { id: crypto.randomUUID(), profile: { ...DEFAULT_PROFILE } }]);

  const removeProfile = (index: number) => setRows((list) => list.filter((_, i) => i !== index));

  return (
    <div className="flex flex-col gap-3">
      {rows.map(({ id, profile }, index) => (
        <div
          key={id}
          className="animate-[fadeInUp_var(--db-transition-spring)_backwards] overflow-hidden rounded-xl border border-border-light bg-surface shadow-[0_2px_8px_rgba(0,0,0,0.02)] [transition:box-shadow_0.3s_ease,border-color_0.3s_ease,transform_var(--db-transition-spring)] hover:-translate-y-0.5 hover:border-primary-200 hover:shadow-[0_8px_24px_rgba(0,0,0,0.06)]"
        >
          <div className="flex items-center justify-between border-b border-border-light bg-surface-secondary px-4 py-3">
            <div className="flex items-center gap-2.5">
              <span className="flex h-6 w-6 items-center justify-center rounded-sm bg-primary text-[12px] font-semibold text-white">
                {index + 1}
              </span>
              <span className="text-[15px] font-bold tracking-[-0.02em] text-fg">
                Profile {index + 1}
              </span>
            </div>
            <Button
              icon="pi pi-times"
              text
              rounded
              severity="danger"
              title="Remove this profile"
              onClick={() => removeProfile(index)}
            />
          </div>

          <div className="flex flex-col gap-4 p-4">
            <div className={FIELD_ROW_2_CLASS}>
              <div className={FIELD_CLASS}>
                <label className={FIELD_LABEL_CLASS}>Type</label>
                <Dropdown
                  value={profile.type}
                  options={PROFILE_TYPE_OPTIONS}
                  optionLabel="label"
                  optionValue="value"
                  placeholder="Select type"
                  appendTo={document.body}
                  className="w-full"
                  onChange={(e) => updateProfile(index, { type: e.value, image: '' })}
                />
              </div>
              <div className={FIELD_CLASS}>
                <label className={FIELD_LABEL_CLASS}>Image</label>
                <Dropdown
                  value={profile.image}
                  options={getImagesForType(profile.type)}
                  optionLabel="label"
                  optionValue="image"
                  placeholder="Select image"
                  disabled={!profile.type}
                  appendTo={document.body}
                  className="w-full"
                  onChange={(e) => updateProfile(index, { image: e.value })}
                />
              </div>
            </div>

            <Panel header="Resources" toggleable collapsed className="resource-panel">
              <div className={FIELD_ROW_2_CLASS}>
                <ResourceNumberField
                  label="CPU Request (vCPU)"
                  value={profile.cpuRequest}
                  step={0.25}
                  min={0.25}
                  max={16}
                  onChange={(v) => updateProfile(index, { cpuRequest: v })}
                />
                <ResourceNumberField
                  label="CPU Limit (vCPU)"
                  value={profile.cpuLimit}
                  step={0.25}
                  min={0.25}
                  max={64}
                  onChange={(v) => updateProfile(index, { cpuLimit: v })}
                />
              </div>
              <div className={FIELD_ROW_2_CLASS}>
                <ResourceNumberField
                  label="Memory Request (GiB)"
                  value={profile.memoryRequestGi}
                  step={0.25}
                  min={0.25}
                  max={64}
                  onChange={(v) => updateProfile(index, { memoryRequestGi: v })}
                />
                <ResourceNumberField
                  label="Memory Limit (GiB)"
                  value={profile.memoryLimitGi}
                  step={0.25}
                  min={0.25}
                  max={256}
                  onChange={(v) => updateProfile(index, { memoryLimitGi: v })}
                />
              </div>
              <div className={FIELD_CLASS}>
                <label className={FIELD_LABEL_CLASS}>GPU</label>
                <div className="flex items-center gap-3.5">
                  <InputSwitch
                    checked={profile.gpuEnabled}
                    onChange={(e) => updateProfile(index, { gpuEnabled: !!e.value })}
                  />
                  {profile.gpuEnabled && (
                    <InputNumber
                      value={profile.gpuCount}
                      showButtons
                      min={1}
                      max={8}
                      className="w-[120px]"
                      onValueChange={(e) => updateProfile(index, { gpuCount: e.value ?? 1 })}
                    />
                  )}
                </div>
              </div>
            </Panel>
          </div>
        </div>
      ))}

      <Button
        label="Add profile"
        icon="pi pi-plus"
        outlined
        severity="secondary"
        className="w-full"
        onClick={addProfile}
      />
    </div>
  );
}
