// src/features/admin/identity/groups/group-list.tsx
import { useState } from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { InputTextarea } from 'primereact/inputtextarea';
import { Toast } from 'primereact/toast';
import { identityApi, type Group } from '../../../../core/api/identity-api';
import { useIdentityGroups } from '../use-identity';
import EmptyState from '../../../../shared/components/empty-state';
import SearchFilter from '../../../../shared/components/search-filter';
import { PageHeader } from '../../../../shared/components/page-header';
import { useToastMessages } from '../../../../shared/hooks/use-toast-messages';
import { useRowActionsMenu } from '../../../../shared/hooks/use-row-actions-menu';
import { DialogFooter } from '../../../../shared/components/dialog-footer';
import DeleteConfirmDialog from '../../../../shared/components/delete-confirm-dialog';

export function GroupList() {
  const { toast, showSuccess, showError } = useToastMessages();

  const { groups, loading, error, refresh: refreshGroups } = useIdentityGroups();

  const [globalFilter, setGlobalFilter] = useState('');
  const [groupDialog, setGroupDialog] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [group, setGroup] = useState<Group>({ name: '' });
  const [deleteTarget, setDeleteTarget] = useState<Group | null>(null);

  const openNew = () => {
    setGroup({ name: '' });
    setIsEditMode(false);
    setGroupDialog(true);
  };

  const editGroup = (g: Group) => {
    setGroup({ ...g });
    setIsEditMode(true);
    setGroupDialog(true);
  };

  const deleteGroup = (g: Group) => {
    identityApi
      .deleteGroup(g.name)
      .then(() => {
        showSuccess('Group deleted');
        refreshGroups();
      })
      .catch(() => showError('Failed to delete group'));
  };

  const hideDialog = () => setGroupDialog(false);

  const saveGroup = () => {
    if (!group.name?.trim()) {
      return;
    }

    const save = isEditMode
      ? identityApi.updateGroup(group.name, group)
      : identityApi.createGroup(group);

    save
      .then(() => {
        showSuccess(isEditMode ? 'Group updated' : 'Group created');
        refreshGroups();
        hideDialog();
      })
      .catch(() => showError(isEditMode ? 'Failed to update group' : 'Failed to create group'));
  };

  const { menuElement, openMenu } = useRowActionsMenu<Group>([
    { label: 'Edit', icon: 'pi pi-pencil', command: editGroup },
    { separator: true },
    { label: 'Delete', icon: 'pi pi-trash', command: setDeleteTarget },
  ]);

  const dialogFooter = (
    <DialogFooter
      onCancel={hideDialog}
      onConfirm={saveGroup}
      confirmLabel={isEditMode ? 'Save' : 'Create'}
      confirmDisabled={!group.name}
    />
  );

  return (
    <div>
      <Toast ref={toast} />
      <DeleteConfirmDialog
        resourceName={deleteTarget?.name ?? null}
        resourceKind="group"
        message={
          deleteTarget && (
            <>
              This will permanently remove <strong>{deleteTarget.name}</strong>. This action cannot
              be undone.
            </>
          )
        }
        onHide={() => setDeleteTarget(null)}
        onConfirm={() => {
          if (deleteTarget) deleteGroup(deleteTarget);
          setDeleteTarget(null);
        }}
      />

      {/* Top Bar */}
      <PageHeader
        title="Groups"
        actions={
          <button className="create-btn" onClick={openNew}>
            <i className="pi pi-plus"></i>
            <span>Create group</span>
          </button>
        }
      />

      {error && groups.length === 0 ? (
        <EmptyState
          icon="pi pi-exclamation-triangle"
          title="Failed to load groups"
          description="The group list could not be retrieved. Check your connection and try again."
          action={
            <button className="btn-secondary mt-3" onClick={refreshGroups}>
              <i className="pi pi-refresh"></i>
              <span>Retry</span>
            </button>
          }
        />
      ) : (
        <>
          <SearchFilter
            value={globalFilter}
            onChange={setGlobalFilter}
            placeholder="Filter groups..."
          />

          {/* Data Table */}
          <div className="table-wrapper">
            <DataTable
              value={groups}
              loading={loading}
              globalFilter={globalFilter}
              globalFilterFields={['name', 'description']}
              className="minimal-table"
              emptyMessage="No groups found."
              rowClassName={() => 'group-row'}
            >
              <Column
                header="Name"
                field="name"
                style={{ width: '30%' }}
                body={(g: Group) => <span className="font-medium">{g.name}</span>}
              />
              <Column
                header="Description"
                field="description"
                style={{ width: '55%' }}
                body={(g: Group) => g.description || '-'}
              />
              <Column
                style={{ width: '15%', textAlign: 'right' }}
                body={(g: Group) => (
                  <div className="actions">
                    <Button icon="pi pi-ellipsis-v" text rounded onClick={(e) => openMenu(g, e)} />
                  </div>
                )}
              />
            </DataTable>
            {menuElement}
          </div>
        </>
      )}

      {/* Create/Edit Dialog */}
      <Dialog
        header={isEditMode ? 'Edit group' : 'Create new group'}
        visible={groupDialog}
        modal
        draggable={false}
        resizable={false}
        style={{ width: '450px' }}
        className="db-dialog"
        closable
        onHide={hideDialog}
        footer={dialogFooter}
      >
        <div className="dialog-content">
          <div className="field">
            <label htmlFor="name">Group name</label>
            <InputText
              id="name"
              value={group.name}
              onChange={(e) => setGroup((g) => ({ ...g, name: e.target.value }))}
              className="w-full dialog-input"
              placeholder="e.g., developers"
              disabled={isEditMode}
            />
          </div>

          <div className="field">
            <label htmlFor="description">
              Description <span className="optional">(optional)</span>
            </label>
            <InputTextarea
              id="description"
              value={group.description ?? ''}
              onChange={(e) => setGroup((g) => ({ ...g, description: e.target.value }))}
              rows={4}
              className="w-full dialog-input"
              placeholder="Describe the purpose of this group..."
            />
          </div>
        </div>
      </Dialog>
    </div>
  );
}

// src/app/features/admin/identity/groups/group-list.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { MenuModule } from 'primeng/menu';
import { FormsModule } from '@angular/forms';
import { IdentityService, Group } from '../../../../core/services/identity.service';
import { ConfirmationService, MessageService, MenuItem } from 'primeng/api';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { ToastModule } from 'primeng/toast';
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';

@Component({
  selector: 'app-group-list',
  standalone: true,
  imports: [
    CommonModule,
    TableModule,
    ButtonModule,
    DialogModule,
    InputTextModule,
    TextareaModule,
    MenuModule,
    FormsModule,
    ConfirmDialogModule,
    ToastModule,
    IconFieldModule,
    InputIconModule
  ],
  providers: [ConfirmationService, MessageService],
  templateUrl: './group-list.component.html',
  styleUrls: ['./group-list.component.css']
})
export class GroupListComponent {
  private readonly identityService = inject(IdentityService);
  private readonly messageService = inject(MessageService);
  private readonly confirmationService = inject(ConfirmationService);

  // Consume signal directly from service
  readonly groups = this.identityService.groups;
  readonly loading = this.identityService.groupsLoading;

  groupDialog = false;
  submitted = false;
  isEditMode = false;

  group: Group = { name: '' };
  selectedGroup: Group | null = null;

  menuItems: MenuItem[] = [
    {
      label: 'Edit',
      icon: 'pi pi-pencil',
      command: () => {
        if (this.selectedGroup) {
          this.editGroup(this.selectedGroup);
        }
      }
    },
    { separator: true },
    {
      label: 'Delete',
      icon: 'pi pi-trash',
      command: () => {
        if (this.selectedGroup) {
          this.deleteGroup(this.selectedGroup);
        }
      }
    }
  ];

  openNew() {
    this.group = { name: '' };
    this.submitted = false;
    this.isEditMode = false;
    this.groupDialog = true;
  }

  editGroup(group: Group) {
    this.group = { ...group };
    this.groupDialog = true;
    this.isEditMode = true;
  }

  deleteGroup(group: Group) {
    this.confirmationService.confirm({
      message: `Are you sure you want to delete <strong>${group.name}</strong>? This action cannot be undone.`,
      header: 'Delete group?',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Delete',
      rejectLabel: 'Cancel',
      accept: () => {
        this.identityService.deleteGroup(group.name).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Group deleted' });
            // No manual reload needed - service auto-refreshes
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to delete group' });
          }
        });
      }
    });
  }

  hideDialog() {
    this.groupDialog = false;
    this.submitted = false;
  }

  saveGroup() {
    this.submitted = true;

    if (this.group.name?.trim()) {
      if (this.isEditMode) {
        this.identityService.updateGroup(this.group.name, this.group).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Group updated' });
            this.hideDialog();
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to update group' });
          }
        });
      } else {
        this.identityService.createGroup(this.group).subscribe({
          next: () => {
            this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Group created' });
            this.hideDialog();
          },
          error: () => {
            this.messageService.add({ severity: 'error', summary: 'Error', detail: 'Failed to create group' });
          }
        });
      }
    }
  }
}


<div class="group-container">
    <p-toast></p-toast>
    <p-confirmDialog styleClass="db-confirm-dialog" [style]="{width: '400px'}" acceptButtonStyleClass="p-button-danger"
        rejectButtonStyleClass="p-button-text">
    </p-confirmDialog>

    <!-- Top Bar -->
    <div class="top-bar">
        <div class="left-group">
            <h1>Groups</h1>
            <p-iconfield>
                <p-inputicon styleClass="pi pi-search" />
                <input type="text" pInputText placeholder="Filter groups..."
                    (input)="dt.filterGlobal($any($event.target).value, 'contains')" />
            </p-iconfield>
        </div>

        <p-button label="Create group" (onClick)="openNew()" styleClass="create-btn">
        </p-button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
        <p-table #dt [value]="groups()" [loading]="loading()" [globalFilterFields]="['name', 'description']"
            styleClass="minimal-table">

            <ng-template pTemplate="header">
                <tr>
                    <th style="width: 30%">Name</th>
                    <th style="width: 55%">Description</th>
                    <th style="width: 15%"></th>
                </tr>
            </ng-template>

            <ng-template pTemplate="body" let-group>
                <tr class="group-row">
                    <td>
                        <span class="group-name">{{ group.name }}</span>
                    </td>
                    <td class="description-cell">
                        {{ group.description || '-' }}
                    </td>
                    <td style="text-align: right">
                        <div class="actions">
                            <p-button icon="pi pi-ellipsis-v" [text]="true" [rounded]="true"
                                (onClick)="menu.toggle($event); selectedGroup = group">
                            </p-button>
                            <p-menu #menu [model]="menuItems" [popup]="true" appendTo="body"></p-menu>
                        </div>
                    </td>
                </tr>
            </ng-template>

            <ng-template pTemplate="emptymessage">
                <tr>
                    <td colspan="3" class="empty-message">
                        No groups found.
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>

    <!-- Create/Edit Dialog -->
    <p-dialog [header]="isEditMode ? 'Edit group' : 'Create new group'" [(visible)]="groupDialog" [modal]="true"
        [draggable]="false" [resizable]="false" [style]="{ width: '450px' }" styleClass="db-dialog" [closable]="true">

        <div class="dialog-content">
            <div class="field">
                <label for="name">Group name</label>
                <input pInputText id="name" [(ngModel)]="group.name" class="w-full dialog-input"
                    placeholder="e.g., developers" [disabled]="isEditMode" />
                <small class="p-error" *ngIf="submitted && !group.name">Group name is required.</small>
            </div>

            <div class="field">
                <label for="description">Description <span class="optional">(optional)</span></label>
                <textarea pInputTextarea id="description" [(ngModel)]="group.description" rows="4"
                    class="w-full dialog-input" placeholder="Describe the purpose of this group..."></textarea>
            </div>
        </div>

        <ng-template pTemplate="footer">
            <div class="dialog-actions">
                <p-button severity="secondary" [outlined]="true" label="Cancel" (onClick)="hideDialog()"></p-button>
                <p-button severity="primary" [disabled]="!group.name" (onClick)="saveGroup()" [label]="isEditMode ? 'Save' : 'Create'"></p-button>
            </div>
        </ng-template>
    </p-dialog>
</div>
