// src/features/project-console/services/service-detail-page.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Toast } from 'primereact/toast';
import DeleteConfirmDialog from '../../../shared/components/delete-confirm-dialog';
import EmptyState from '../../../shared/components/empty-state';
import { serviceApi } from '../../../core/api/service-api';
import type { Pod, ServiceInstance, ServiceMetrics } from '../../../core/models/service.model';
import { useToastMessages } from '../../../shared/hooks/use-toast-messages';
import { PodList } from './pod-list';
import { PodLogViewer } from './pod-log-viewer';
import {
  apiErrorMessage,
  areaBasePath,
  formatMediumDateTime,
  isTransitioning,
  openInNewTab,
  parentLabel,
  statusTone,
} from './service-utils';
import { StatusTag } from '../../../shared/components/status-tag';

type Tab = 'overview' | 'pods' | 'logs' | 'parameters';

const TABS: Tab[] = ['overview', 'pods', 'logs', 'parameters'];

interface ResourceUsage {
  used: string;
  limit: string;
  pct: number;
  pctLabel: string;
  unbounded: boolean;
}

function resourceUsage(metrics: ServiceMetrics | null, kind: 'cpu' | 'memory'): ResourceUsage {
  if (!metrics) {
    return { used: '—', limit: '—', pct: 0, pctLabel: '—', unbounded: false };
  }
  const v = kind === 'cpu' ? metrics.cpu : metrics.memory;
  const hasLimit = v.limitRaw > 0;
  return {
    used: v.available ? v.used : '—',
    limit: hasLimit ? v.limit : '—',
    pct: v.pct,
    pctLabel: hasLimit ? `${Math.round(v.pct * 100)}%` : '',
    unbounded: v.available && !hasLimit,
  };
}

function MetricCard({
  label,
  usage,
  unit,
}: {
  label: string;
  usage: ResourceUsage;
  unit?: string;
}) {
  return (
    <div className={`metric${usage.unbounded ? ' unbounded' : ''}`}>
      <div className="metric-top">
        <span className="metric-label">{label}</span>
        {!usage.unbounded && (
          <span className="metric-unit">
            <span className="metric-used">{usage.used}</span>
            <span className="metric-sep">/</span>
            <span>
              {usage.limit}
              {unit ? ` ${unit}` : ''}
            </span>
          </span>
        )}
      </div>
      {usage.unbounded ? (
        <div className="metric-value">
          <span className="metric-value-big">{usage.used}</span>
          {unit && <span className="muted-text small">{unit}</span>}
          <span className="metric-hint" style={{ marginLeft: 'auto' }}>
            No limit set
          </span>
        </div>
      ) : (
        <>
          <div className="metric-bar">
            <div
              className={[
                'metric-fill',
                usage.pct > 0.6 && usage.pct <= 0.8 ? 'tone-warn' : '',
                usage.pct > 0.8 ? 'tone-danger' : '',
              ]
                .filter(Boolean)
                .join(' ')}
              style={{ width: `${usage.pct * 100}%` }}
            ></div>
          </div>
          <div className="metric-pct">{usage.pctLabel}</div>
        </>
      )}
    </div>
  );
}

export default function ServiceDetailPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { projectId = '', serviceName = '' } = useParams<{
    projectId: string;
    serviceName: string;
  }>();
  const [searchParams] = useSearchParams();
  const { toast, showSuccess, showError } = useToastMessages();
  // Stale-response guard: only the latest loadAll call may commit state
  // (params can change mid-flight when navigating between instances).
  const reqIdRef = useRef(0);

  const [instance, setInstance] = useState<ServiceInstance | null>(null);
  const [pods, setPods] = useState<Pod[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPod, setSelectedPod] = useState<Pod | null>(null);
  const [tab, setTab] = useState<Tab>('overview');
  const [metrics, setMetrics] = useState<ServiceMetrics | null>(null);
  // Type-to-confirm deletion dialog visibility.
  const [deleteVisible, setDeleteVisible] = useState(false);

  const runningPods = useMemo(
    () => pods.filter((p) => p.status === 'Running' || p.status === 'Ready').length,
    [pods],
  );

  const paramEntries = useMemo(() => {
    const params = instance?.parameters || {};
    const entries: { key: string; value: string }[] = [];
    for (const [k, v] of Object.entries(params)) {
      if (k === 'profiles') continue;
      entries.push({ key: k, value: typeof v === 'object' ? JSON.stringify(v) : String(v) });
    }
    return entries;
  }, [instance]);

  const cpuUsage = resourceUsage(metrics, 'cpu');
  const memUsage = resourceUsage(metrics, 'memory');

  const loadAll = useCallback(() => {
    const reqId = ++reqIdRef.current;
    if (!projectId || !serviceName) {
      setLoading(false);
      return;
    }
    setLoading(true);
    Promise.all([
      serviceApi.getService(projectId, serviceName),
      serviceApi.getPods(projectId, serviceName),
    ])
      .then(([inst, podList]) => {
        if (reqId !== reqIdRef.current) return;
        setInstance(inst);
        setPods(podList);
        setLoading(false);
      })
      .catch(() => {
        if (reqId !== reqIdRef.current) return;
        showError('Failed to load instance details');
        setLoading(false);
      });
  }, [projectId, serviceName, showError]);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  // Metrics: fetch immediately then every 10s.
  useEffect(() => {
    if (!projectId || !serviceName) return;
    let cancelled = false;
    const fetchMetrics = () => {
      serviceApi
        .getServiceMetrics(projectId, serviceName)
        .then((m) => {
          if (!cancelled) setMetrics(m);
        })
        .catch(() => {
          // Leave metrics as null; UI falls back to "—".
        });
    };
    fetchMetrics();
    const id = setInterval(fetchMetrics, 10_000);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [projectId, serviceName]);

  // Navigation stays inside the instance's own console area (e.g. a Trino
  // instance edits/returns under /trino, not /services).
  const basePath = areaBasePath(instance?.service).join('/');

  const goBack = () => {
    if (!projectId) return;
    const returnTo = searchParams.get('returnTo');
    if (returnTo) {
      navigate(returnTo);
    } else {
      navigate(`/projects/${projectId}/${basePath}`);
    }
  };

  const openExternal = () => {
    const url = instance?.url;
    if (url) openInNewTab(url);
  };

  const editInstance = () => {
    if (projectId) {
      const returnTo = encodeURIComponent(location.pathname + location.search);
      navigate(`/projects/${projectId}/${basePath}/${serviceName}/edit?returnTo=${returnTo}`);
    }
  };

  const confirmDelete = () => {
    if (instance) setDeleteVisible(true);
  };

  const deleteInstance = () => {
    setDeleteVisible(false);
    if (!instance) return;
    serviceApi
      .deleteService(projectId, instance.name)
      .then(() => {
        showSuccess(`"${instance.name}" has been removed`, 'Instance deleted');
        goBack();
      })
      .catch((err) => {
        showError(apiErrorMessage(err, 'Failed to delete instance'));
      });
  };

  const onViewLogs = (pod: Pod) => {
    setSelectedPod(pod);
    setTab('logs');
  };

  const tabLabel = (t: Tab) => t.charAt(0).toUpperCase() + t.slice(1);

  return (
    <>
      <Toast ref={toast} />
      <DeleteConfirmDialog
        resourceName={deleteVisible ? (instance?.name ?? null) : null}
        resourceKind="instance"
        message={
          instance && (
            <>
              This will remove <strong>{instance.name}</strong> and all its pods. This cannot be
              undone.
            </>
          )
        }
        onHide={() => setDeleteVisible(false)}
        onConfirm={deleteInstance}
      />

      <div className="detail-page animate-in">
        <div className="page-header">
          <nav className="breadcrumb">
            <a
              className="breadcrumb-link"
              onClick={goBack}
              onKeyDown={(e) => e.key === 'Enter' && goBack()}
              tabIndex={0}
            >
              <i className="pi pi-arrow-left text-[11px]"></i>
              {parentLabel(instance?.service)}
            </a>
            <i className="pi pi-angle-right text-[10px] text-fg-muted"></i>
            <span className="breadcrumb-current">{instance?.name || serviceName}</span>
          </nav>

          {instance && (
            <div className="header-row">
              <div className="header-badge">
                <i className="pi pi-server"></i>
              </div>
              <div className="header-text">
                <div className="header-title-row">
                  <h2>{instance.name}</h2>
                  <StatusTag
                    value={instance.status}
                    tone={statusTone(instance.status)}
                    pulse={isTransitioning(instance.status)}
                  />
                </div>
                <p className="page-desc">
                  {instance.service} · <span className="mono">{instance.serviceTag}</span>
                </p>
              </div>
              <div className="header-actions">
                {instance.url && (
                  <button
                    className="btn-secondary"
                    disabled={instance.status !== 'Ready'}
                    onClick={openExternal}
                  >
                    <i className="pi pi-external-link"></i>
                    Open
                  </button>
                )}
                <button className="btn-secondary" onClick={loadAll}>
                  <i className="pi pi-refresh"></i>
                  Refresh
                </button>
                <button className="btn-secondary" onClick={editInstance}>
                  <i className="pi pi-pencil"></i>
                  Edit
                </button>
                <button className="btn-secondary danger" onClick={confirmDelete}>
                  <i className="pi pi-trash"></i>
                  Delete
                </button>
              </div>
            </div>
          )}
        </div>

        {loading ? (
          <EmptyState
            variant="panel"
            icon="pi pi-spin pi-spinner"
            title="Loading instance details…"
          />
        ) : instance ? (
          <>
            <div className="okdp-tabs">
              {TABS.map((t) => (
                <button
                  key={t}
                  className={`okdp-tab${tab === t ? ' active' : ''}`}
                  onClick={() => setTab(t)}
                >
                  {tabLabel(t)}
                  {t === 'pods' && <span className="tab-count">{pods.length}</span>}
                </button>
              ))}
            </div>

            {tab === 'overview' && (
              <div className="detail-content">
                {instance.status === 'Error' && (
                  <div className="alert alert-danger">
                    <i className="pi pi-exclamation-circle"></i>
                    <div>
                      <strong>Instance failed to start</strong>
                      {instance.statusMessage ? (
                        <p className="mono">{instance.statusMessage}</p>
                      ) : (
                        <p className="mono">Check the pod logs for the underlying error.</p>
                      )}
                    </div>
                  </div>
                )}
                {instance.status === 'Updating' && (
                  <div className="alert alert-warn">
                    <i className="pi pi-spin pi-spinner"></i>
                    <div>
                      <strong>Updating…</strong>
                      {instance.statusMessage ? (
                        <p className="mono">{instance.statusMessage}</p>
                      ) : (
                        <p>KuboCD is rolling out the new configuration.</p>
                      )}
                    </div>
                  </div>
                )}
                {instance.status === 'Installing' && (
                  <div className="alert alert-warn">
                    <i className="pi pi-spin pi-spinner"></i>
                    <div>
                      <strong>Installing…</strong>
                      {instance.statusMessage ? (
                        <p className="mono">{instance.statusMessage}</p>
                      ) : (
                        <p>Pulling image and scheduling pod. This usually takes ~30s.</p>
                      )}
                    </div>
                  </div>
                )}

                <div className="info-card">
                  <div className="info-grid">
                    <div className="info-item">
                      <span className="info-label">Instance name</span>
                      <span className="info-value">{instance.name}</span>
                    </div>
                    <div className="info-item">
                      <span className="info-label">Release</span>
                      <span className="info-value mono">{instance.releaseName}</span>
                    </div>
                    <div className="info-item">
                      <span className="info-label">Namespace</span>
                      <span className="info-value mono">{instance.targetNamespace}</span>
                    </div>
                    <div className="info-item">
                      <span className="info-label">Service</span>
                      <span className="info-value">{instance.service}</span>
                    </div>
                    <div className="info-item">
                      <span className="info-label">Version</span>
                      <span className="info-value mono">{instance.serviceTag}</span>
                    </div>
                    <div className="info-item">
                      <span className="info-label">Created</span>
                      <span className="info-value">
                        {instance.createdAt ? formatMediumDateTime(instance.createdAt) : '—'}
                      </span>
                    </div>
                    {instance.url && (
                      <div className="info-item info-item-wide">
                        <span className="info-label">URL</span>
                        <a
                          className="info-link mono"
                          href={instance.url}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          {instance.url}
                          <i className="pi pi-external-link text-[11px]"></i>
                        </a>
                      </div>
                    )}
                  </div>
                </div>

                <div className="section-card">
                  <div className="section-header">
                    <div className="section-icon-badge chart">
                      <i className="pi pi-chart-bar"></i>
                    </div>
                    <h3 className="section-title">Resource usage</h3>
                    <span className="muted-text small">Last 5 min</span>
                  </div>
                  <div className="metric-grid">
                    <MetricCard label="CPU" usage={cpuUsage} unit="cores" />
                    <MetricCard label="Memory" usage={memUsage} />
                  </div>
                </div>

                <div className="section-card">
                  <div className="section-header">
                    <div className="section-icon-badge">
                      <i className="pi pi-box"></i>
                    </div>
                    <h3 className="section-title">Pods</h3>
                    <span className="muted-text small">
                      {runningPods} / {pods.length} running
                    </span>
                  </div>
                  <PodList pods={pods} onViewLogs={onViewLogs} />
                </div>
              </div>
            )}

            {tab === 'pods' && (
              <div className="section-card">
                <PodList pods={pods} onViewLogs={onViewLogs} />
              </div>
            )}

            {tab === 'logs' &&
              (pods.length > 0 ? (
                <PodLogViewer
                  projectId={projectId}
                  serviceName={serviceName}
                  pods={pods}
                  initialPodName={selectedPod?.name}
                />
              ) : (
                <div className="section-card">
                  <div className="section-header">
                    <div className="section-icon-badge">
                      <i className="pi pi-file"></i>
                    </div>
                    <h3 className="section-title">Logs</h3>
                  </div>
                  <p className="muted-text" style={{ padding: '12px 0 0' }}>
                    No pods available yet. Logs will appear here once the service is running.
                  </p>
                </div>
              ))}

            {tab === 'parameters' && (
              <div className="section-card">
                {paramEntries.length > 0 ? (
                  <div className="param-list">
                    {paramEntries.map((param) => (
                      <div key={param.key} className="param-row">
                        <span className="param-key mono">{param.key}</span>
                        <span className="param-value mono">{param.value}</span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="muted-text">No parameters set on this instance.</p>
                )}
              </div>
            )}
          </>
        ) : (
          <EmptyState
            variant="panel"
            icon="pi pi-exclamation-triangle"
            title="Instance not found"
            description="The service instance could not be loaded."
            action={
              <button className="btn-secondary" onClick={goBack}>
                <i className="pi pi-arrow-left"></i>
                Back to instances
              </button>
            }
          />
        )}
      </div>
    </>
  );
}

// src/app/features/project-console/services/service-detail-page.component.ts
import { Component, inject, signal, OnInit, OnDestroy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastModule } from 'primeng/toast';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { MessageService, ConfirmationService } from 'primeng/api';
import { forkJoin } from 'rxjs';
import { ServiceApiService } from '../../../core/api/service-api.service';
import { ProjectContextService } from '../../../core/context/project-context.service';
import { ServiceInstance, Pod, ServiceMetrics } from '../../../core/models/service.model';
import { PodListComponent } from './pod-list.component';
import { PodLogViewerComponent } from './pod-log-viewer.component';

type Tab = 'overview' | 'pods' | 'logs' | 'parameters';

@Component({
    selector: 'app-service-detail-page',
    standalone: true,
    imports: [
        CommonModule,
        ToastModule,
        ConfirmDialogModule,
        PodListComponent,
        PodLogViewerComponent,
    ],
    providers: [MessageService, ConfirmationService],
    template: `
        <p-toast></p-toast>
        <p-confirmDialog></p-confirmDialog>

        <div class="detail-page animate-in">
            <div class="page-header">
                <nav class="breadcrumb">
                    <a
                        class="breadcrumb-link"
                        (click)="goBack()"
                        (keydown.enter)="goBack()"
                        tabindex="0">
                        <i class="pi pi-arrow-left" style="font-size: 11px"></i>
                        {{ parentLabel() }}
                    </a>
                    <i class="pi pi-angle-right" style="font-size: 10px; color: var(--db-text-muted)"></i>
                    <span class="breadcrumb-current">{{ instance()?.name || serviceName }}</span>
                </nav>

                @if (instance(); as inst) {
                    <div class="header-row">
                        <div class="header-badge">
                            <i class="pi pi-server"></i>
                        </div>
                        <div class="header-text">
                            <div class="header-title-row">
                                <h2>{{ inst.name }}</h2>
                                <span class="okdp-tag" [class]="tagClass(inst.status)">
                                    @if (inst.status === 'Installing' || inst.status === 'Updating') {
                                        <span class="okdp-tag-dot"></span>
                                    }
                                    {{ inst.status }}
                                </span>
                            </div>
                            <p class="page-desc">
                                {{ inst.service }} ·
                                <span class="mono">{{ inst.serviceTag }}</span>
                            </p>
                        </div>
                        <div class="header-actions">
                            @if (inst.url) {
                                <button
                                    class="btn-secondary"
                                    [disabled]="inst.status !== 'Ready'"
                                    (click)="openExternal()">
                                    <i class="pi pi-external-link"></i>
                                    Open
                                </button>
                            }
                            <button class="btn-secondary" (click)="refreshAll()">
                                <i class="pi pi-refresh"></i>
                                Refresh
                            </button>
                            <button class="btn-secondary" (click)="editInstance()">
                                <i class="pi pi-pencil"></i>
                                Edit
                            </button>
                            <button class="btn-secondary danger" (click)="confirmDelete()">
                                <i class="pi pi-trash"></i>
                                Delete
                            </button>
                        </div>
                    </div>
                }
            </div>

            @if (loading()) {
                <div class="empty-state-panel">
                    <div class="empty-icon-wrapper">
                        <i class="pi pi-spin pi-spinner"></i>
                    </div>
                    <h3>Loading instance details…</h3>
                </div>
            } @else if (instance(); as inst) {
                <div class="okdp-tabs">
                    @for (t of tabs; track t) {
                        <button
                            class="okdp-tab"
                            [class.active]="tab() === t"
                            (click)="tab.set(t)">
                            {{ tabLabel(t) }}
                            @if (t === 'pods') {
                                <span class="tab-count">{{ pods().length }}</span>
                            }
                        </button>
                    }
                </div>

                @if (tab() === 'overview') {
                    <div class="detail-content">
                        @if (inst.status === 'Error') {
                            <div class="alert alert-danger">
                                <i class="pi pi-exclamation-circle"></i>
                                <div>
                                    <strong>Instance failed to start</strong>
                                    @if (inst.statusMessage) {
                                        <p class="mono">{{ inst.statusMessage }}</p>
                                    } @else {
                                        <p class="mono">Check the pod logs for the underlying error.</p>
                                    }
                                </div>
                            </div>
                        }
                        @if (inst.status === 'Updating') {
                            <div class="alert alert-warn">
                                <i class="pi pi-spin pi-spinner"></i>
                                <div>
                                    <strong>Updating…</strong>
                                    @if (inst.statusMessage) {
                                        <p class="mono">{{ inst.statusMessage }}</p>
                                    } @else {
                                        <p>KuboCD is rolling out the new configuration.</p>
                                    }
                                </div>
                            </div>
                        }
                        @if (inst.status === 'Installing') {
                            <div class="alert alert-warn">
                                <i class="pi pi-spin pi-spinner"></i>
                                <div>
                                    <strong>Installing…</strong>
                                    @if (inst.statusMessage) {
                                        <p class="mono">{{ inst.statusMessage }}</p>
                                    } @else {
                                        <p>Pulling image and scheduling pod. This usually takes ~30s.</p>
                                    }
                                </div>
                            </div>
                        }

                        <div class="info-card">
                            <div class="info-grid">
                                <div class="info-item">
                                    <span class="info-label">Instance name</span>
                                    <span class="info-value">{{ inst.name }}</span>
                                </div>
                                <div class="info-item">
                                    <span class="info-label">Release</span>
                                    <span class="info-value mono">{{ inst.releaseName }}</span>
                                </div>
                                <div class="info-item">
                                    <span class="info-label">Namespace</span>
                                    <span class="info-value mono">{{ inst.targetNamespace }}</span>
                                </div>
                                <div class="info-item">
                                    <span class="info-label">Service</span>
                                    <span class="info-value">{{ inst.service }}</span>
                                </div>
                                <div class="info-item">
                                    <span class="info-label">Version</span>
                                    <span class="info-value mono">{{ inst.serviceTag }}</span>
                                </div>
                                <div class="info-item">
                                    <span class="info-label">Created</span>
                                    <span class="info-value">
                                        {{ inst.createdAt ? (inst.createdAt | date: 'medium') : '—' }}
                                    </span>
                                </div>
                                @if (inst.url) {
                                    <div class="info-item info-item-wide">
                                        <span class="info-label">URL</span>
                                        <a
                                            class="info-link mono"
                                            [href]="inst.url"
                                            target="_blank"
                                            rel="noopener">
                                            {{ inst.url }}
                                            <i class="pi pi-external-link" style="font-size: 11px"></i>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>

                        <div class="section-card">
                            <div class="section-header">
                                <div class="section-icon-badge chart">
                                    <i class="pi pi-chart-bar"></i>
                                </div>
                                <h3 class="section-title">Resource usage</h3>
                                <span class="muted-text small">Last 5 min</span>
                            </div>
                            <div class="metric-grid">
                                <div class="metric" [class.unbounded]="cpuUsage().unbounded">
                                    <div class="metric-top">
                                        <span class="metric-label">CPU</span>
                                        @if (!cpuUsage().unbounded) {
                                            <span class="metric-unit">
                                                <span class="metric-used">{{ cpuUsage().used }}</span>
                                                <span class="metric-sep">/</span>
                                                <span>{{ cpuUsage().limit }} cores</span>
                                            </span>
                                        }
                                    </div>
                                    @if (cpuUsage().unbounded) {
                                        <div class="metric-value">
                                            <span class="metric-value-big">{{ cpuUsage().used }}</span>
                                            <span class="muted-text small">cores</span>
                                            <span class="metric-hint" style="margin-left: auto">No limit set</span>
                                        </div>
                                    } @else {
                                        <div class="metric-bar">
                                            <div
                                                class="metric-fill"
                                                [class.tone-warn]="cpuUsage().pct > 0.6 && cpuUsage().pct <= 0.8"
                                                [class.tone-danger]="cpuUsage().pct > 0.8"
                                                [style.width.%]="cpuUsage().pct * 100">
                                            </div>
                                        </div>
                                        <div class="metric-pct">{{ cpuUsage().pctLabel }}</div>
                                    }
                                </div>
                                <div class="metric" [class.unbounded]="memUsage().unbounded">
                                    <div class="metric-top">
                                        <span class="metric-label">Memory</span>
                                        @if (!memUsage().unbounded) {
                                            <span class="metric-unit">
                                                <span class="metric-used">{{ memUsage().used }}</span>
                                                <span class="metric-sep">/</span>
                                                <span>{{ memUsage().limit }}</span>
                                            </span>
                                        }
                                    </div>
                                    @if (memUsage().unbounded) {
                                        <div class="metric-value">
                                            <span class="metric-value-big">{{ memUsage().used }}</span>
                                            <span class="metric-hint" style="margin-left: auto">No limit set</span>
                                        </div>
                                    } @else {
                                        <div class="metric-bar">
                                            <div
                                                class="metric-fill"
                                                [class.tone-warn]="memUsage().pct > 0.6 && memUsage().pct <= 0.8"
                                                [class.tone-danger]="memUsage().pct > 0.8"
                                                [style.width.%]="memUsage().pct * 100">
                                            </div>
                                        </div>
                                        <div class="metric-pct">{{ memUsage().pctLabel }}</div>
                                    }
                                </div>
                            </div>
                        </div>

                        <div class="section-card">
                            <div class="section-header">
                                <div class="section-icon-badge">
                                    <i class="pi pi-box"></i>
                                </div>
                                <h3 class="section-title">Pods</h3>
                                <span class="muted-text small">
                                    {{ runningPods() }} / {{ pods().length }} running
                                </span>
                            </div>
                            <app-pod-list
                                [pods]="pods()"
                                (viewLogs)="onViewLogs($event)">
                            </app-pod-list>
                        </div>
                    </div>
                }

                @if (tab() === 'pods') {
                    <div class="section-card">
                        <app-pod-list
                            [pods]="pods()"
                            (viewLogs)="onViewLogs($event)">
                        </app-pod-list>
                    </div>
                }

                @if (tab() === 'logs') {
                    @if (pods().length > 0) {
                        <app-pod-log-viewer
                            [projectId]="projectId"
                            [serviceName]="serviceName"
                            [pods]="pods()"
                            [initialPodName]="selectedPod()?.name">
                        </app-pod-log-viewer>
                    } @else {
                        <div class="section-card">
                            <div class="section-header">
                                <div class="section-icon-badge">
                                    <i class="pi pi-file"></i>
                                </div>
                                <h3 class="section-title">Logs</h3>
                            </div>
                            <p class="muted-text" style="padding: 12px 0 0">
                                No pods available yet. Logs will appear here once the service is running.
                            </p>
                        </div>
                    }
                }

                @if (tab() === 'parameters') {
                    <div class="section-card">
                        @if (paramEntries().length > 0) {
                            <div class="param-list">
                                @for (param of paramEntries(); track param.key) {
                                    <div class="param-row">
                                        <span class="param-key mono">{{ param.key }}</span>
                                        <span class="param-value mono">{{ param.value }}</span>
                                    </div>
                                }
                            </div>
                        } @else {
                            <p class="muted-text">No parameters set on this instance.</p>
                        }
                    </div>
                }
            } @else {
                <div class="empty-state-panel">
                    <div class="empty-icon-wrapper">
                        <i class="pi pi-exclamation-triangle"></i>
                    </div>
                    <h3>Instance not found</h3>
                    <p>The service instance could not be loaded.</p>
                    <button class="btn-secondary" (click)="goBack()">
                        <i class="pi pi-arrow-left"></i>
                        Back to instances
                    </button>
                </div>
            }
        </div>
    `,
})
export class ServiceDetailPageComponent implements OnInit, OnDestroy {
    private readonly api = inject(ServiceApiService);
    private readonly context = inject(ProjectContextService);
    private readonly messageService = inject(MessageService);
    private readonly confirmationService = inject(ConfirmationService);
    private readonly router = inject(Router);
    private readonly route = inject(ActivatedRoute);

    instance = signal<ServiceInstance | null>(null);
    pods = signal<Pod[]>([]);
    loading = signal(true);
    selectedPod = signal<Pod | null>(null);
    paramEntries = signal<{ key: string; value: string }[]>([]);
    tab = signal<Tab>('overview');
    metrics = signal<ServiceMetrics | null>(null);
    private metricsPollId: ReturnType<typeof setInterval> | null = null;

    readonly tabs: Tab[] = ['overview', 'pods', 'logs', 'parameters'];

    runningPods = computed(
        () => this.pods().filter((p) => p.status === 'Running' || p.status === 'Ready').length,
    );

    cpuUsage = computed(() => this.resourceUsage('cpu'));
    memUsage = computed(() => this.resourceUsage('memory'));

    private resourceUsage(kind: 'cpu' | 'memory') {
        const m = this.metrics();
        if (!m) {
            return { used: '—', limit: '—', pct: 0, pctLabel: '—', unbounded: false };
        }
        const v = kind === 'cpu' ? m.cpu : m.memory;
        const hasLimit = v.limitRaw > 0;
        return {
            used: v.available ? v.used : '—',
            limit: hasLimit ? v.limit : '—',
            pct: v.pct,
            pctLabel: hasLimit ? `${Math.round(v.pct * 100)}%` : '',
            unbounded: v.available && !hasLimit,
        };
    }

    projectId = '';
    serviceName = '';

    ngOnInit() {
        const project = this.context.currentProject();
        this.serviceName = this.route.snapshot.paramMap.get('serviceName') || '';
        this.projectId = project?.name || '';

        if (!this.projectId || !this.serviceName) {
            this.loading.set(false);
            return;
        }

        this.loadAll();
        this.startMetricsPolling();
    }

    ngOnDestroy() {
        if (this.metricsPollId !== null) {
            clearInterval(this.metricsPollId);
            this.metricsPollId = null;
        }
    }

    private startMetricsPolling() {
        // Fetch immediately then every 10s.
        this.fetchMetrics();
        this.metricsPollId = setInterval(() => this.fetchMetrics(), 10_000);
    }

    private fetchMetrics() {
        if (!this.projectId || !this.serviceName) return;
        this.api.getServiceMetrics(this.projectId, this.serviceName).subscribe({
            next: (m) => this.metrics.set(m),
            error: () => {
                // Leave metrics as null; UI falls back to "—".
            },
        });
    }

    private loadAll() {
        this.loading.set(true);
        forkJoin({
            instance: this.api.getService(this.projectId, this.serviceName),
            pods: this.api.getPods(this.projectId, this.serviceName),
        }).subscribe({
            next: ({ instance, pods }) => {
                this.instance.set(instance);
                this.pods.set(pods);

                const params = instance.parameters || {};
                const entries: { key: string; value: string }[] = [];
                for (const [k, v] of Object.entries(params)) {
                    if (k === 'profiles') continue;
                    entries.push({
                        key: k,
                        value: typeof v === 'object' ? JSON.stringify(v) : String(v),
                    });
                }
                this.paramEntries.set(entries);
                this.loading.set(false);
            },
            error: () => {
                this.messageService.add({
                    severity: 'error',
                    summary: 'Error',
                    detail: 'Failed to load instance details',
                });
                this.loading.set(false);
            },
        });
    }

    refreshAll() {
        this.loadAll();
    }

    onViewLogs(pod: Pod) {
        this.selectedPod.set(pod);
        this.tab.set('logs');
    }

    openExternal() {
        const url = this.instance()?.url;
        if (url) window.open(url, '_blank');
    }

    editInstance() {
        const project = this.context.currentProject();
        if (project) {
            this.router.navigate(
                ['/project', project.name, 'services', this.serviceName, 'edit'],
                { queryParams: { returnTo: this.router.url } },
            );
        }
    }

    confirmDelete() {
        const inst = this.instance();
        if (!inst) return;
        this.confirmationService.confirm({
            message: `This will remove "${inst.name}" and all its pods. This cannot be undone.`,
            header: 'Delete this instance?',
            icon: 'pi pi-exclamation-triangle',
            acceptButtonStyleClass: 'p-button-danger',
            accept: () => this.delete(),
        });
    }

    private delete() {
        const inst = this.instance();
        if (!inst) return;
        this.api.deleteService(this.projectId, inst.name).subscribe({
            next: () => {
                this.messageService.add({
                    severity: 'success',
                    summary: 'Instance deleted',
                    detail: `"${inst.name}" has been removed`,
                });
                this.goBack();
            },
            error: (err) => {
                this.messageService.add({
                    severity: 'error',
                    summary: 'Error',
                    detail: err?.error?.error || 'Failed to delete instance',
                });
            },
        });
    }

    tagClass(status: string): string {
        switch (status) {
            case 'Ready':
            case 'Running':
                return 'okdp-tag-success';
            case 'Installing':
            case 'Updating':
                return 'okdp-tag-warn';
            case 'Error':
            case 'CrashLoopBackOff':
            case 'Failed':
                return 'okdp-tag-danger';
            default:
                return 'okdp-tag-info';
        }
    }

    tabLabel(t: Tab): string {
        return t.charAt(0).toUpperCase() + t.slice(1);
    }

    parentLabel(): string {
        const svc = this.instance()?.service;
        if (svc === 'jupyterhub') return 'Jupyter';
        if (svc === 'spark-history-server') return 'History Server';
        if (svc === 'trino') return 'Trino';
        return svc || 'Services';
    }

    goBack() {
        const project = this.context.currentProject();
        if (!project) return;
        const returnTo = this.route.snapshot.queryParamMap.get('returnTo');
        if (returnTo) {
            this.router.navigateByUrl(returnTo);
        } else {
            this.router.navigate(['/project', project.name, 'services']);
        }
    }
}
