// src/features/project-console/services/services-page.tsx
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { areaBasePath, parentLabel } from './service-utils';
import { ServiceList } from './service-list';
import { PageHeader } from '../../../shared/components/page-header';

export interface ServicesPageProps {
  title: string;
  deployLabel: string;
  serviceFilter: string;
  emptyMessage: string;
}

interface ServiceAreaCopy {
  breadcrumbParent: string;
  subtitle: string;
  emptyTitle: string;
}

// Page copy per service area. Labels and the area base path (used so the
// sidebar highlights the correct entry — otherwise anything under
// /jupyterhub/* lights up the JupyterHub link, even when the user clicked
// Deploy from the Spark History Server page) come from the SERVICE_AREAS
// registry in service-utils.
function areaCopy(serviceFilter: string): ServiceAreaCopy {
  switch (serviceFilter) {
    case 'jupyterhub':
      return {
        breadcrumbParent: 'Notebooks',
        subtitle:
          "Launch and manage per-user JupyterLab environments running in this project's namespace.",
        emptyTitle: 'Deploy JupyterHub',
      };
    case 'spark-history-server':
      return {
        breadcrumbParent: 'Spark',
        subtitle: 'Browse completed Spark applications and stream live job monitoring UIs.',
        emptyTitle: 'Deploy a Spark History Server',
      };
    case 'trino':
      return {
        breadcrumbParent: 'Lakehouse',
        subtitle:
          'Distributed SQL query engine. Query data across the lakehouse and federated sources.',
        emptyTitle: 'Deploy Trino',
      };
    case 'polaris':
      return {
        breadcrumbParent: 'Lakehouse',
        subtitle: 'Iceberg-native data catalog. Centralize table metadata across engines.',
        emptyTitle: 'Deploy Polaris',
      };
    case 'superset':
      return {
        breadcrumbParent: 'SQL & BI',
        subtitle: 'Open-source dashboarding and ad-hoc data exploration.',
        emptyTitle: 'Deploy Superset',
      };
    case 'airflow':
      return {
        breadcrumbParent: 'Data Engineering',
        subtitle: 'Workflow orchestrator. Schedule and monitor data pipelines as DAGs.',
        emptyTitle: 'Deploy Airflow',
      };
    default:
      return {
        breadcrumbParent: 'Services',
        subtitle: '',
        emptyTitle: 'No instances yet',
      };
  }
}

export default function ServicesPage({
  title,
  deployLabel,
  serviceFilter,
  emptyMessage,
}: ServicesPageProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const { projectId } = useParams<{ projectId: string }>();

  const copy = areaCopy(serviceFilter);
  const basePath = areaBasePath(serviceFilter);
  const breadcrumbCurrent = serviceFilter ? parentLabel(serviceFilter) : 'Instances';

  const goToDeploy = () => {
    if (!projectId) return;

    const params = new URLSearchParams({ returnTo: location.pathname + location.search });
    if (serviceFilter) {
      params.set('service', serviceFilter);
    }
    navigate(`/projects/${projectId}/${basePath.join('/')}/deploy?${params.toString()}`);
  };

  return (
    <div className="services-list animate-in">
      <PageHeader
        breadcrumb={{ parent: copy.breadcrumbParent, current: breadcrumbCurrent }}
        title={title}
        subtitle={copy.subtitle}
        actions={
          <button className="create-btn" onClick={goToDeploy}>
            <i className="pi pi-plus"></i>
            <span>{deployLabel}</span>
          </button>
        }
      />

      <ServiceList
        serviceFilter={serviceFilter}
        emptyMessage={emptyMessage}
        emptyTitle={copy.emptyTitle}
        basePath={basePath}
        onDeploy={goToDeploy}
      />
    </div>
  );
}

// src/app/features/project-console/services/services-page.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { ProjectContextService } from '../../../core/context/project-context.service';
import { ServiceListComponent } from './service-list.component';

@Component({
    selector: 'app-services-page',
    standalone: true,
    imports: [CommonModule, ServiceListComponent],
    template: `
        <div class="services-list animate-in">
            <div class="page-heading">
                <div>
                    <div class="breadcrumb-thin">
                        <span>{{ breadcrumbParent }}</span>
                        <i class="pi pi-angle-right" style="font-size: 10px"></i>
                        <span class="bc-current">{{ breadcrumbCurrent }}</span>
                    </div>
                    <h1 class="page-title">{{ title }}</h1>
                    <p class="page-sub">{{ subtitle }}</p>
                </div>
                <button class="create-btn" (click)="goToDeploy()">
                    <i class="pi pi-plus"></i>
                    <span>{{ deployLabel }}</span>
                </button>
            </div>

            <app-service-list
                [serviceFilter]="serviceFilter"
                [emptyMessage]="emptyMessage"
                [emptyTitle]="emptyTitle"
                [basePath]="basePath"
                (deploy)="goToDeploy()">
            </app-service-list>
        </div>
    `,
})
export class ServicesPageComponent {
    private readonly router = inject(Router);
    private readonly route = inject(ActivatedRoute);
    private readonly context = inject(ProjectContextService);

    readonly title: string;
    readonly subtitle: string;
    readonly deployLabel: string;
    readonly serviceFilter: string;
    readonly emptyMessage: string;
    readonly emptyTitle: string;
    readonly breadcrumbParent: string;
    readonly breadcrumbCurrent: string;
    // URL segments under /project/:projectId for this page's "service area".
    // Routes for deploy/edit/detail are mirrored under each area so the
    // sidebar's routerLinkActive highlights the correct entry (otherwise
    // anything under /services/* lights up the Jupyter link, even when the
    // user clicked Deploy from the Spark History Server page).
    readonly basePath: string[];

    constructor() {
        const data = this.route.snapshot.data;
        this.title = data['title'] || 'Service instances';
        this.deployLabel = data['deployLabel'] || 'New instance';
        this.serviceFilter = data['serviceFilter'] || '';
        this.emptyMessage = data['emptyMessage'] || 'No instances deployed yet.';
        // Each service may live under a section-specific URL prefix; the
        // breadcrumb back-link must follow that prefix (otherwise clicking
        // "Polaris" from the detail page would land on /services).
        this.basePath =
            this.serviceFilter === 'spark-history-server' ? ['spark', 'history-server']
            : this.serviceFilter === 'polaris'            ? ['lakehouse', 'polaris']
            : this.serviceFilter === 'trino'              ? ['lakehouse', 'trino']
            : this.serviceFilter === 'airflow'            ? ['data-engineering', 'airflow']
            : this.serviceFilter === 'superset'           ? ['bi', 'superset']
            : ['services'];

        // Derive breadcrumb + subtitle from the service filter when not provided.
        if (this.serviceFilter === 'jupyterhub') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Notebook';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Jupyter';
            this.subtitle =
                data['subtitle'] ||
                "Launch and manage per-user JupyterLab environments running in this project's namespace.";
            this.emptyTitle = data['emptyTitle'] || 'Launch your first Jupyter instance';
        } else if (this.serviceFilter === 'spark-history-server') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Spark';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'History Server';
            this.subtitle =
                data['subtitle'] ||
                'Browse completed Spark applications and stream live job monitoring UIs.';
            this.emptyTitle = data['emptyTitle'] || 'Deploy a Spark History Server';
        } else if (this.serviceFilter === 'polaris') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Lakehouse';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Polaris';
            this.subtitle =
                data['subtitle'] ||
                'Iceberg-native data catalog. Centralize table metadata across engines.';
            this.emptyTitle = data['emptyTitle'] || 'Deploy Polaris';
        } else if (this.serviceFilter === 'trino') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Lakehouse';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Trino';
            this.subtitle =
                data['subtitle'] ||
                'Distributed SQL query engine. Query data across the lakehouse and federated sources.';
            this.emptyTitle = data['emptyTitle'] || 'Deploy Trino';
        } else if (this.serviceFilter === 'airflow') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Data Engineering';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Airflow';
            this.subtitle =
                data['subtitle'] ||
                'Workflow orchestrator. Schedule and monitor data pipelines as DAGs.';
            this.emptyTitle = data['emptyTitle'] || 'Deploy Airflow';
        } else if (this.serviceFilter === 'superset') {
            this.breadcrumbParent = data['breadcrumbParent'] || 'SQL & BI';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Superset';
            this.subtitle =
                data['subtitle'] ||
                'Open-source dashboarding and ad-hoc data exploration.';
            this.emptyTitle = data['emptyTitle'] || 'Deploy Superset';
        } else {
            this.breadcrumbParent = data['breadcrumbParent'] || 'Services';
            this.breadcrumbCurrent = data['breadcrumbCurrent'] || 'Instances';
            this.subtitle = data['subtitle'] || '';
            this.emptyTitle = data['emptyTitle'] || 'No instances yet';
        }
    }

    goToDeploy() {
        const project = this.context.currentProject();
        if (!project) return;

        const currentPath = this.router.url;
        const queryParams: Record<string, string> = { returnTo: currentPath };
        if (this.serviceFilter) {
            queryParams['service'] = this.serviceFilter;
        }
        this.router.navigate(['/project', project.name, ...this.basePath, 'deploy'], { queryParams });
    }
}
