// src/features/project-console/home/project-home.tsx
import { useProjectContext } from '../../../core/context/project-context';
import DeployedServicesSummary from './deployed-services-summary';
import { useProjectServicesSummary } from './use-project-services-summary';
import ProjectKpis from './project-kpis';
import SectionHeading from '../../../shared/components/section-heading';
import { ActionCard, QuickActions } from '../../../shared/components/action-card';
import EmptyState from '../../../shared/components/empty-state';
import CtaButton from '../../../shared/components/cta-button';

export default function ProjectHome() {
  const context = useProjectContext();
  const project = context.currentProject;
  const summary = useProjectServicesSummary(project?.name);

  return (
    <section className="flex animate-[fadeInUp_0.4s_ease-out] flex-col gap-7">
      {project ? (
        <>
          <div>
            <h1>Platform Dashboard</h1>
            {project.description && <p className="page-sub mt-1">{project.description}</p>}
          </div>

          <ProjectKpis summary={summary} />

          <SectionHeading>Deployed services</SectionHeading>
          <DeployedServicesSummary projectId={project.name} summary={summary} />

          <SectionHeading>Quick Actions</SectionHeading>
          <QuickActions>
            <ActionCard
              to={`/projects/${project.name}/jupyterhub/deploy?service=jupyterhub`}
              icon="pi pi-play"
              tone="primary"
              title="Deploy Notebook"
              description="Launch a new JupyterHub instance"
            />
            <ActionCard
              to={`/projects/${project.name}/jupyterhub`}
              icon="pi pi-server"
              tone="blue"
              title="View Instances"
              description="Monitor running notebooks"
            />
            <ActionCard
              to={`/projects/${project.name}/secret-stores`}
              icon="pi pi-lock"
              tone="purple"
              title="Manage Secrets"
              description="Configure secret stores"
            />
          </QuickActions>
        </>
      ) : context.availableProjects.length === 0 ? (
        <EmptyState
          icon="pi pi-folder-open"
          title="No Projects Available"
          description="Your workspace is empty. Create your first project to get started."
          action={
            <CtaButton to="/projects" icon="pi pi-plus">
              Create Project
            </CtaButton>
          }
        />
      ) : (
        <div className="flex items-center gap-2.5 py-7 text-fg-secondary">
          <i className="pi pi-spin pi-spinner text-primary"></i>
          <p>Loading project...</p>
        </div>
      )}
    </section>
  );
}

// src/app/features/project-console/home/project-home.component.ts
import { Component, inject } from '@angular/core';
import { ProjectContextService } from '../../../core/context/project-context.service';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-project-home',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <section class="home">
      @if (context.currentProject(); as project) {
        <!-- Welcome Banner -->
        <div class="welcome-banner">
          <div class="banner-content">
            <div class="banner-icon">
              <i class="pi pi-th-large"></i>
            </div>
            <div class="banner-text">
              <h1>{{ project.name }}</h1>
              <p class="subtitle">{{ project.description || 'Project Dashboard' }}</p>
            </div>
          </div>
          <div class="banner-decoration"></div>
        </div>

        <!-- Quick Actions -->
        <h2 class="section-heading">Quick Actions</h2>
        <div class="quick-actions">
          <a class="action-card" [routerLink]="['/project', project.name, 'services', 'deploy']">
            <div class="card-icon deploy">
              <i class="pi pi-play"></i>
            </div>
            <div class="action-text">
              <span class="action-title">Deploy Notebook</span>
              <span class="action-desc">Launch a new Jupyter instance</span>
            </div>
            <i class="pi pi-arrow-right action-arrow"></i>
          </a>
          <a class="action-card" [routerLink]="['/project', project.name, 'services']">
            <div class="card-icon instances">
              <i class="pi pi-server"></i>
            </div>
            <div class="action-text">
              <span class="action-title">View Instances</span>
              <span class="action-desc">Monitor running notebooks</span>
            </div>
            <i class="pi pi-arrow-right action-arrow"></i>
          </a>
          <a class="action-card" [routerLink]="['/project', project.name, 'secret-stores']">
            <div class="card-icon secrets">
              <i class="pi pi-lock"></i>
            </div>
            <div class="action-text">
              <span class="action-title">Manage Secrets</span>
              <span class="action-desc">Configure secret stores</span>
            </div>
            <i class="pi pi-arrow-right action-arrow"></i>
          </a>
        </div>
      } @else if (context.availableProjects().length === 0) {
        <div class="empty-state">
          <div class="empty-icon-wrapper">
            <i class="pi pi-folder-open empty-icon"></i>
          </div>
          <h2>No Projects Available</h2>
          <p>Your workspace is empty. Create your first project to get started.</p>
          <a routerLink="/admin/projects" class="cta-button">
            <i class="pi pi-plus"></i>
            Create Project
          </a>
        </div>
      } @else {
        <div class="loading-state">
          <i class="pi pi-spin pi-spinner"></i>
          <p>Loading project...</p>
        </div>
      }
    </section>
  `,
  styles: [`
    /* Layout only — shared styles (welcome-banner, action-card, card-icon,
       empty-state, cta-button, etc.) are defined globally in base.css */
    .home {
      display: flex;
      flex-direction: column;
      gap: 28px;
      animation: fadeInUp 0.4s ease-out;
    }

    @keyframes fadeInUp {
      from { opacity: 0; transform: translateY(12px); }
      to { opacity: 1; transform: translateY(0); }
    }

    .loading-state {
      display: flex;
      align-items: center;
      gap: 10px;
      color: var(--db-text-secondary);
      padding: var(--db-space-xl) 0;
    }

    .loading-state i {
      color: var(--db-primary);
    }
  `]
})
export class ProjectHomeComponent {
  protected readonly context = inject(ProjectContextService);
}
