// src/app/features/project-console/services/service-edit-page.component.ts
import { Component, inject, signal, OnInit, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { SelectModule } from 'primeng/select';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { forkJoin } from 'rxjs';
import { ServiceApiService } from '../../../core/api/service-api.service';
import { ProjectContextService } from '../../../core/context/project-context.service';
import { ServiceInstance } from '../../../core/models/service.model';
import { DynamicSchemaFormComponent } from '../../../shared/components/dynamic-schema-form.component';
import {
    ProfileListEditorComponent,
    Profile,
} from '../../../shared/components/profile-list-editor.component';

@Component({
    selector: 'app-service-edit-page',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        SelectModule,
        ToastModule,
        DynamicSchemaFormComponent,
        ProfileListEditorComponent,
    ],
    providers: [MessageService],
    template: `
        <p-toast></p-toast>

        <div class="deploy-page animate-in">
            <div class="page-header">
                <nav class="breadcrumb">
                    <a
                        class="breadcrumb-link"
                        (click)="goBack()"
                        (keydown.enter)="goBack()"
                        tabindex="0">
                        <i class="pi pi-arrow-left" style="font-size: 11px"></i>
                        {{ parentLabel() }}
                    </a>
                    <i class="pi pi-angle-right" style="font-size: 10px; color: var(--db-text-muted)"></i>
                    <a class="breadcrumb-link" (click)="goBack()" tabindex="0">
                        {{ instance()?.name }}
                    </a>
                    <i class="pi pi-angle-right" style="font-size: 10px; color: var(--db-text-muted)"></i>
                    <span class="breadcrumb-current">Edit</span>
                </nav>

                @if (instance(); as inst) {
                    <div class="header-row">
                        <div class="header-badge">
                            <i class="pi pi-pencil"></i>
                        </div>
                        <div class="header-text">
                            <div class="header-title-row">
                                <h2>
                                    Edit
                                    <span class="mono" style="font-weight: 600">{{ inst.name }}</span>
                                </h2>
                                <span class="okdp-tag" [class]="tagClass(inst.status)">
                                    @if (inst.status === 'Installing' || inst.status === 'Updating') {
                                        <span class="okdp-tag-dot"></span>
                                    }
                                    {{ inst.status }}
                                </span>
                            </div>
                            <p class="page-desc">
                                Change version, parameters or profiles. Saving will trigger a rolling restart.
                            </p>
                        </div>
                    </div>
                }
            </div>

            @if (loading()) {
                <div class="empty-state-panel">
                    <div class="empty-icon-wrapper">
                        <i class="pi pi-spin pi-spinner"></i>
                    </div>
                    <h3>Loading instance configuration…</h3>
                </div>
            } @else if (instance(); as inst) {
                @if (hasPendingChanges() && inst.status === 'Ready') {
                    <div class="edit-banner">
                        <i class="pi pi-info-circle"></i>
                        <div>
                            <strong>A restart will be required.</strong>
                            <span class="muted-text">
                                Running kernels will be interrupted. Unsaved notebook changes are preserved on the persistent volume.
                            </span>
                        </div>
                    </div>
                }

                <div class="form-card">
                    <div class="form-section">
                        <div class="form-field">
                            <label>Instance name</label>
                            <input
                                class="text-input mono"
                                [value]="inst.name"
                                disabled />
                            <small class="field-hint">Name cannot be changed after creation.</small>
                        </div>

                        <div class="form-field">
                            <div class="field-head">
                                <label style="margin: 0">Version</label>
                                <span class="muted-text small mono">{{ inst.service }}</span>
                            </div>
                            <small class="field-hint" style="margin-top: 0; margin-bottom: 10px">
                                Currently <span class="mono">{{ inst.serviceTag }}</span>. Changing the tag reloads the parameter schema.
                            </small>
                            @if (versionOptions().length > 0) {
                                <p-select
                                    [(ngModel)]="selectedTag"
                                    [options]="versionOptions()"
                                    optionLabel="label"
                                    optionValue="value"
                                    appendTo="body"
                                    styleClass="w-full"
                                    (ngModelChange)="onVersionChange($event)">
                                </p-select>
                            } @else {
                                <span class="version-badge mono">{{ inst.serviceTag }}</span>
                            }
                        </div>
                    </div>
                </div>

                <div class="form-card" style="margin-top: 14px">
                    @if (schemaLoading()) {
                        <div class="form-section">
                            <div style="display: flex; align-items: center; gap: 12px; padding: 8px 0">
                                <i class="pi pi-spin pi-spinner" style="color: var(--db-primary); font-size: 18px"></i>
                                <div>
                                    <strong>Loading configuration schema…</strong>
                                    <div class="muted-text small">
                                        Fetching {{ inst.service }}:{{ selectedTag }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    } @else if (filteredSchema()) {
                        <div class="form-section">
                            <app-dynamic-schema-form
                                [schema]="filteredSchema()"
                                [initialValues]="parameterValues()"
                                (parametersChange)="onParametersChange($event)"
                                (validityChange)="paramsValid.set($event)">
                            </app-dynamic-schema-form>
                        </div>
                    }

                    @if (existingProfiles().length > 0 || needsProfileEditor()) {
                        <div class="form-section" style="margin-top: 20px">
                            <div class="field-head">
                                <label style="margin: 0">Profiles</label>
                                <span class="muted-text small">
                                    Notebook environments users can launch.
                                </span>
                            </div>
                            <app-profile-list-editor
                                [profileImages]="profileImages()"
                                [initialProfiles]="existingProfiles()"
                                (profilesChange)="onProfilesChange($event)">
                            </app-profile-list-editor>
                        </div>
                    }
                </div>

                <div class="wizard-actions">
                    <button class="btn-secondary" (click)="goBack()" [disabled]="saving()">
                        Cancel
                    </button>
                    <div class="wa-right">
                        <button
                            class="create-btn"
                            (click)="save()"
                            [disabled]="saving() || !paramsValid()">
                            @if (saving()) {
                                <i class="pi pi-spin pi-spinner"></i>
                                Saving…
                            } @else {
                                <i class="pi pi-check"></i>
                                Save changes
                            }
                        </button>
                    </div>
                </div>
            } @else {
                <div class="empty-state-panel">
                    <div class="empty-icon-wrapper">
                        <i class="pi pi-exclamation-triangle"></i>
                    </div>
                    <h3>Instance not found</h3>
                    <p>The service instance could not be loaded.</p>
                    <button class="btn-secondary" (click)="goBack()">
                        <i class="pi pi-arrow-left"></i>
                        Back to instances
                    </button>
                </div>
            }
        </div>
    `,
})
export class ServiceEditPageComponent implements OnInit {
    private readonly api = inject(ServiceApiService);
    private readonly context = inject(ProjectContextService);
    private readonly messageService = inject(MessageService);
    private readonly router = inject(Router);
    private readonly route = inject(ActivatedRoute);

    instance = signal<ServiceInstance | null>(null);
    loading = signal(true);
    saving = signal(false);
    // Mirrors the validity state of the dynamic schema form so Save can be
    // disabled when a CPU/memory quantity is malformed (e.g. "1" instead of
    // "1Gi"). Starts true so an untouched form with valid defaults is saveable.
    paramsValid = signal(true);
    schemaLoading = signal(false);
    filteredSchema = signal<any>(null);
    rawSchema = signal<any>(null);
    profileImages = signal<Record<string, { label: string; image: string }[]>>({});
    parameterValues = signal<Record<string, any>>({});
    existingProfiles = signal<Profile[]>([]);
    versionOptions = signal<{ label: string; value: string }[]>([]);

    selectedTag = '';
    private originalTag = '';
    private parameters: Record<string, any> = {};
    private profiles: Profile[] = [];

    hasPendingChanges = computed(() => this.selectedTag !== this.originalTag);

    tagClass(status: string): string {
        switch (status) {
            case 'Ready':
            case 'Running':
                return 'okdp-tag-success';
            case 'Installing':
            case 'Updating':
                return 'okdp-tag-warn';
            case 'Error':
            case 'CrashLoopBackOff':
            case 'Failed':
                return 'okdp-tag-danger';
            default:
                return 'okdp-tag-info';
        }
    }

    parentLabel(): string {
        const svc = this.instance()?.service;
        if (svc === 'jupyterhub') return 'Jupyter';
        if (svc === 'spark-history-server') return 'History Server';
        if (svc === 'trino') return 'Trino';
        if (svc === 'polaris') return 'Polaris';
        if (svc === 'superset') return 'Superset';
        return svc || 'Services';
    }

    needsProfileEditor(): boolean {
        const schema = this.rawSchema();
        if (!schema?.properties) return false;
        return Object.values<any>(schema.properties).some(
            (def) => def['x-ui-widget'] === 'profile-editor',
        );
    }

    ngOnInit() {
        const project = this.context.currentProject();
        const serviceName = this.route.snapshot.paramMap.get('serviceName');
        if (!project || !serviceName) {
            this.loading.set(false);
            return;
        }

        forkJoin({
            instance: this.api.getService(project.name, serviceName),
            profileImages: this.api.getProfileImages(),
            platformServices: this.api.getPlatformServices(),
        }).subscribe({
            next: ({ instance, profileImages, platformServices }) => {
                this.instance.set(instance);
                this.profileImages.set(profileImages);

                this.selectedTag = instance.serviceTag;
                this.originalTag = instance.serviceTag;

                const svc = platformServices.find((s) => s.name === instance.service);
                if (svc?.versions?.length) {
                    this.versionOptions.set(
                        svc.versions.map((v) => ({
                            label: v === svc.defaultVersion ? `${v} (recommended)` : v,
                            value: v,
                        })),
                    );
                }

                const { profiles, ...params } = instance.parameters || {};
                this.parameterValues.set(params);
                this.parameters = { ...params };

                if (Array.isArray(profiles) && profiles.length > 0) {
                    this.existingProfiles.set(profiles);
                    this.profiles = [...profiles];
                }

                this.loadSchema(instance.service, instance.serviceTag);
                this.loading.set(false);
            },
            error: () => {
                this.messageService.add({
                    severity: 'error',
                    summary: 'Error',
                    detail: 'Failed to load instance',
                });
                this.loading.set(false);
            },
        });
    }

    private loadSchema(serviceName: string, tag: string) {
        this.schemaLoading.set(true);
        this.api.getServiceSchema(serviceName, tag).subscribe({
            next: (schema) => {
                this.rawSchema.set(schema);
                this.filteredSchema.set(this.stripProfileEditorFields(schema));
                this.schemaLoading.set(false);
            },
            error: () => {
                this.messageService.add({
                    severity: 'warn',
                    summary: 'Schema unavailable',
                    detail: 'Could not load configuration schema.',
                });
                this.schemaLoading.set(false);
            },
        });
    }

    private stripProfileEditorFields(schema: any): any {
        if (!schema?.properties) return schema;
        const filtered = { ...schema, properties: { ...schema.properties } };
        for (const [key, def] of Object.entries<any>(filtered.properties)) {
            if (def['x-ui-widget'] === 'profile-editor') {
                delete filtered.properties[key];
            }
        }
        return filtered;
    }

    onVersionChange(tag: string) {
        const inst = this.instance();
        if (!inst || !tag) return;
        this.filteredSchema.set(null);
        this.loadSchema(inst.service, tag);
    }

    onParametersChange(params: Record<string, any>) {
        this.parameters = params;
    }

    onProfilesChange(profiles: Profile[]) {
        this.profiles = profiles;
    }

    save() {
        const project = this.context.currentProject();
        const svc = this.instance();
        if (!project || !svc) return;

        this.saving.set(true);
        // Only include `profiles` when the service schema actually expects it
        // (e.g. JupyterHub). Other services (Trino, Polaris, Superset, Airflow)
        // have `additionalProperties: false` and reject unknown keys.
        const mergedParams: Record<string, any> = { ...this.parameters };
        if (this.needsProfileEditor()) {
            mergedParams['profiles'] = this.profiles;
        }
        const body: { tag?: string; parameters: Record<string, any> } = { parameters: mergedParams };
        if (this.selectedTag && this.selectedTag !== this.originalTag) {
            body.tag = this.selectedTag;
        }
        this.api.updateServiceParameters(project.name, svc.name, body).subscribe({
            next: () => {
                this.messageService.add({
                    severity: 'success',
                    summary: 'Changes saved',
                    detail: `${svc.name} has been updated.`,
                });
                this.saving.set(false);
                this.navigateBack(project.name);
            },
            error: (err) => {
                const msg = err?.error?.error || 'Failed to save changes';
                this.messageService.add({ severity: 'error', summary: 'Error', detail: msg });
                this.saving.set(false);
            },
        });
    }

    goBack() {
        const project = this.context.currentProject();
        if (project) {
            this.navigateBack(project.name);
        }
    }

    private navigateBack(projectName: string) {
        const returnTo = this.route.snapshot.queryParamMap.get('returnTo');
        if (returnTo) {
            this.router.navigateByUrl(returnTo);
        } else {
            this.router.navigate(['/project', projectName, 'services']);
        }
    }
}

// src/features/project-console/services/service-edit-page.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Dropdown } from 'primereact/dropdown';
import { Toast } from 'primereact/toast';
import { serviceApi } from '../../../core/api/service-api';
import type { ServiceInstance } from '../../../core/models/service.model';
import { DynamicSchemaForm } from '../../../shared/components/dynamic-schema-form';
import EmptyState from '../../../shared/components/empty-state';
import { ProfileListEditor, type Profile } from '../../../shared/components/profile-list-editor';
import { useToastMessages } from '../../../shared/hooks/use-toast-messages';
import {
  apiErrorMessage,
  areaBasePath,
  hasProfileEditorWidget,
  isTransitioning,
  parentLabel,
  statusTone,
  useServiceSchema,
  versionOptionsFor,
} from './service-utils';
import { StatusTag } from '../../../shared/components/status-tag';

export default function ServiceEditPage() {
  const navigate = useNavigate();
  const { projectId: projectName, serviceName } = useParams<{
    projectId: string;
    serviceName: string;
  }>();
  const [searchParams] = useSearchParams();
  const { toast, showSuccess, showError, showWarn } = useToastMessages();

  const [instance, setInstance] = useState<ServiceInstance | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  // Mirrors the validity state of the dynamic schema form so Save can be
  // disabled when a CPU/memory quantity is malformed (e.g. "1" instead of
  // "1Gi"). Starts true so an untouched form with valid defaults is saveable.
  const [paramsValid, setParamsValid] = useState(true);
  const {
    schema: rawSchema,
    setSchema: setRawSchema,
    schemaLoading,
    loadSchema,
  } = useServiceSchema(showWarn, 'Could not load configuration schema.');
  const [profileImages, setProfileImages] = useState<
    Record<string, { label: string; image: string }[]>
  >({});
  const [parameterValues, setParameterValues] = useState<Record<string, any>>({});
  const [existingProfiles, setExistingProfiles] = useState<Profile[]>([]);
  const [versionOptions, setVersionOptions] = useState<{ label: string; value: string }[]>([]);
  const [selectedTag, setSelectedTag] = useState('');

  const originalTagRef = useRef('');
  const parametersRef = useRef<Record<string, any>>({});
  const profilesRef = useRef<Profile[]>([]);

  const hasPendingChanges = selectedTag !== originalTagRef.current;

  useEffect(() => {
    if (!projectName || !serviceName) {
      setLoading(false);
      return;
    }

    let cancelled = false;
    Promise.all([
      serviceApi.getService(projectName, serviceName),
      serviceApi.getProfileImages(),
      serviceApi.getPlatformServices(),
    ])
      .then(([inst, images, platformServices]) => {
        if (cancelled) return;
        setInstance(inst);
        setProfileImages(images);

        setSelectedTag(inst.serviceTag);
        originalTagRef.current = inst.serviceTag;

        const svc = platformServices.find((s) => s.name === inst.service);
        if (svc) {
          setVersionOptions(versionOptionsFor(svc));
        }

        const { profiles, ...params } = inst.parameters || {};
        setParameterValues(params);
        parametersRef.current = { ...params };

        if (Array.isArray(profiles) && profiles.length > 0) {
          setExistingProfiles(profiles);
          profilesRef.current = [...profiles];
        }

        loadSchema(inst.service, inst.serviceTag);
        setLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        showError('Failed to load instance');
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [projectName, serviceName, loadSchema, showError]);

  const onVersionChange = (tag: string) => {
    if (!instance || !tag) return;
    setSelectedTag(tag);
    setRawSchema(null);
    loadSchema(instance.service, tag);
  };

  const navigateBack = (project: string) => {
    const returnTo = searchParams.get('returnTo');
    if (returnTo) {
      navigate(returnTo);
    } else {
      navigate(`/projects/${project}/${areaBasePath(instance?.service).join('/')}`);
    }
  };

  const goBack = () => {
    if (projectName) {
      navigateBack(projectName);
    }
  };

  const save = () => {
    if (!projectName || !instance) return;

    setSaving(true);
    // Only include `profiles` when the service schema actually expects it
    // (e.g. JupyterHub). Other services (Trino, Polaris, Superset, Airflow)
    // have `additionalProperties: false` and reject unknown keys.
    const mergedParams: Record<string, any> = { ...parametersRef.current };
    if (hasProfileEditorWidget(rawSchema)) {
      mergedParams['profiles'] = profilesRef.current;
    }
    const body: { tag?: string; parameters: Record<string, any> } = { parameters: mergedParams };
    if (selectedTag && selectedTag !== originalTagRef.current) {
      body.tag = selectedTag;
    }
    serviceApi
      .updateServiceParameters(projectName, instance.name, body)
      .then(() => {
        showSuccess(`${instance.name} has been updated.`, 'Changes saved');
        setSaving(false);
        navigateBack(projectName);
      })
      .catch((err) => {
        showError(apiErrorMessage(err, 'Failed to save changes'));
        setSaving(false);
      });
  };

  return (
    <>
      <Toast ref={toast} />

      <div className="deploy-page animate-in">
        <div className="page-header">
          <nav className="breadcrumb">
            <a
              className="breadcrumb-link"
              onClick={goBack}
              onKeyDown={(e) => e.key === 'Enter' && goBack()}
              tabIndex={0}
            >
              <i className="pi pi-arrow-left text-[11px]"></i>
              {parentLabel(instance?.service)}
            </a>
            <i className="pi pi-angle-right text-[10px] text-fg-muted"></i>
            <a className="breadcrumb-link" onClick={goBack} tabIndex={0}>
              {instance?.name}
            </a>
            <i className="pi pi-angle-right text-[10px] text-fg-muted"></i>
            <span className="breadcrumb-current">Edit</span>
          </nav>

          {instance && (
            <div className="header-row">
              <div className="header-badge">
                <i className="pi pi-pencil"></i>
              </div>
              <div className="header-text">
                <div className="header-title-row">
                  <h2>
                    Edit{' '}
                    <span className="mono" style={{ fontWeight: 600 }}>
                      {instance.name}
                    </span>
                  </h2>
                  <StatusTag
                    value={instance.status}
                    tone={statusTone(instance.status)}
                    pulse={isTransitioning(instance.status)}
                  />
                </div>
                <p className="page-desc">
                  Change version, parameters or profiles. Saving will trigger a rolling restart.
                </p>
              </div>
            </div>
          )}
        </div>

        {loading ? (
          <EmptyState
            variant="panel"
            icon="pi pi-spin pi-spinner"
            title="Loading instance configuration…"
          />
        ) : instance ? (
          <>
            {hasPendingChanges && instance.status === 'Ready' && (
              <div className="edit-banner">
                <i className="pi pi-info-circle"></i>
                <div>
                  <strong>A restart will be required.</strong>
                  <span className="muted-text">
                    Running kernels will be interrupted. Unsaved notebook changes are preserved on
                    the persistent volume.
                  </span>
                </div>
              </div>
            )}

            <div className="form-card">
              <div className="form-section">
                <div className="form-field">
                  <label>Instance name</label>
                  <input className="text-input mono" value={instance.name} disabled />
                  <small className="field-hint">Name cannot be changed after creation.</small>
                </div>

                <div className="form-field">
                  <div className="field-head">
                    <label style={{ margin: 0 }}>Version</label>
                    <span className="muted-text small mono">{instance.service}</span>
                  </div>
                  <small className="field-hint" style={{ marginTop: 0, marginBottom: '10px' }}>
                    Currently <span className="mono">{instance.serviceTag}</span>. Changing the tag
                    reloads the parameter schema.
                  </small>
                  {versionOptions.length > 0 ? (
                    <Dropdown
                      value={selectedTag}
                      options={versionOptions}
                      optionLabel="label"
                      optionValue="value"
                      appendTo={document.body}
                      className="w-full"
                      onChange={(e) => onVersionChange(e.value)}
                    />
                  ) : (
                    <span className="version-badge mono">{instance.serviceTag}</span>
                  )}
                </div>
              </div>
            </div>

            <div className="form-card" style={{ marginTop: '14px' }}>
              {schemaLoading ? (
                <div className="form-section">
                  <div className="flex items-center gap-3 py-2">
                    <i className="pi pi-spin pi-spinner text-[18px] text-primary"></i>
                    <div>
                      <strong>Loading configuration schema…</strong>
                      <div className="muted-text small">
                        Fetching {instance.service}:{selectedTag}
                      </div>
                    </div>
                  </div>
                </div>
              ) : rawSchema ? (
                <div className="form-section">
                  <DynamicSchemaForm
                    schema={rawSchema}
                    initialValues={parameterValues}
                    onParametersChange={(params) => {
                      parametersRef.current = params;
                    }}
                    onValidityChange={setParamsValid}
                  />
                </div>
              ) : null}

              {(existingProfiles.length > 0 || hasProfileEditorWidget(rawSchema)) && (
                <div className="form-section" style={{ marginTop: '20px' }}>
                  <div className="field-head">
                    <label style={{ margin: 0 }}>Profiles</label>
                    <span className="muted-text small">
                      Notebook environments users can launch.
                    </span>
                  </div>
                  <ProfileListEditor
                    profileImages={profileImages}
                    initialProfiles={existingProfiles}
                    onProfilesChange={(profiles) => {
                      profilesRef.current = profiles;
                    }}
                  />
                </div>
              )}
            </div>

            <div className="wizard-actions">
              <button className="btn-secondary" onClick={goBack} disabled={saving}>
                Cancel
              </button>
              <div className="wa-right">
                <button className="create-btn" onClick={save} disabled={saving || !paramsValid}>
                  {saving ? (
                    <>
                      <i className="pi pi-spin pi-spinner"></i>
                      Saving…
                    </>
                  ) : (
                    <>
                      <i className="pi pi-check"></i>
                      Save changes
                    </>
                  )}
                </button>
              </div>
            </div>
          </>
        ) : (
          <EmptyState
            variant="panel"
            icon="pi pi-exclamation-triangle"
            title="Instance not found"
            description="The service instance could not be loaded."
            action={
              <button className="btn-secondary" onClick={goBack}>
                <i className="pi pi-arrow-left"></i>
                Back to instances
              </button>
            }
          />
        )}
      </div>
    </>
  );
}
