// src/app/features/project-console/services/service-list.component.ts
import {
    Component,
    inject,
    signal,
    effect,
    DestroyRef,
    input,
    output,
    computed,
} from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastModule } from 'primeng/toast';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { MessageService, ConfirmationService } from 'primeng/api';
import { Subscription } from 'rxjs';
import { ServiceApiService } from '../../../core/api/service-api.service';
import { ProjectContextService } from '../../../core/context/project-context.service';
import { ServiceInstance } from '../../../core/models/service.model';

type StatusFilter = 'All' | 'Ready' | 'Installing' | 'Updating' | 'Error';

@Component({
    selector: 'app-service-list',
    standalone: true,
    imports: [CommonModule, FormsModule, DatePipe, ToastModule, ConfirmDialogModule],
    providers: [MessageService, ConfirmationService],
    template: `
        <p-toast></p-toast>
        <p-confirmDialog></p-confirmDialog>

        <div class="stat-strip">
            @for (chip of statChips(); track chip.key) {
                <button
                    class="stat-chip"
                    [class.active]="filterStatus() === chip.key"
                    [class.chip-warn]="chip.tone === 'warn'"
                    [class.chip-danger]="chip.tone === 'danger'"
                    (click)="setStatus(chip.key)">
                    <span class="sc-label">{{ chip.key }}</span>
                    <span class="sc-count">{{ chip.count }}</span>
                </button>
            }
        </div>

        <div class="okdp-filter-bar">
            <div class="okdp-search-wrapper">
                <i class="pi pi-search search-icon"></i>
                <input
                    class="okdp-search-input"
                    placeholder="Filter by name, version, namespace…"
                    [ngModel]="query()"
                    (ngModelChange)="query.set($event)" />
            </div>
            <div class="filter-hint">
                {{ filtered().length }} of {{ services().length }}
            </div>
        </div>

        @if (loading()) {
            <div class="empty-state-panel">
                <div class="empty-icon-wrapper">
                    <i class="pi pi-spin pi-spinner"></i>
                </div>
                <h3>Loading instances…</h3>
            </div>
        } @else if (filtered().length === 0) {
            <div class="empty-state-panel">
                <div class="empty-icon-wrapper">
                    <i [class]="hasFilter() ? 'pi pi-search' : 'pi pi-server'"></i>
                </div>
                <h3>{{ hasFilter() ? 'No instances match' : emptyTitle() }}</h3>
                <p>
                    {{
                        hasFilter()
                            ? 'Try clearing the filter or searching by a different term.'
                            : emptyMessage()
                    }}
                </p>
                @if (!hasFilter()) {
                    <button class="create-btn" (click)="deploy.emit()">
                        <i class="pi pi-plus"></i>
                        <span>New instance</span>
                    </button>
                }
            </div>
        } @else {
            <div class="okdp-table-wrapper">
                <table class="okdp-table">
                    <thead>
                        <tr>
                            <th style="width: 32%">Instance</th>
                            <th style="width: 16%">Version</th>
                            <th style="width: 12%">Status</th>
                            <th style="width: 14%">Namespace</th>
                            <th style="width: 12%">Created</th>
                            <th style="width: 14%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (svc of filtered(); track svc.name) {
                            <tr class="clickable-row" (click)="viewDetail(svc)">
                                <td>
                                    <div class="cell-instance">
                                        <span class="cell-name">{{ svc.name }}</span>
                                        <span class="cell-ns mono">{{
                                            svc.releaseName || svc.service
                                        }}</span>
                                    </div>
                                </td>
                                <td>
                                    <span class="version-badge mono">{{ svc.serviceTag }}</span>
                                </td>
                                <td>
                                    <span class="okdp-tag" [class]="tagClass(svc.status)">
                                        @if (svc.status === 'Installing' || svc.status === 'Updating') {
                                            <span class="okdp-tag-dot"></span>
                                        }
                                        {{ svc.status }}
                                    </span>
                                </td>
                                <td>
                                    <span class="muted-text small mono">
                                        {{ svc.targetNamespace || '—' }}
                                    </span>
                                </td>
                                <td>
                                    <span class="muted-text">
                                        {{
                                            svc.createdAt ? (svc.createdAt | date: 'mediumDate') : '—'
                                        }}
                                    </span>
                                </td>
                                <td (click)="$event.stopPropagation()">
                                    <div class="okdp-actions">
                                        <button
                                            class="icon-btn"
                                            title="View details"
                                            (click)="viewDetail(svc)">
                                            <i class="pi pi-eye"></i>
                                        </button>
                                        <button
                                            class="icon-btn"
                                            title="Edit"
                                            (click)="editService(svc)">
                                            <i class="pi pi-pencil"></i>
                                        </button>
                                        @if (svc.url) {
                                            <button
                                                class="icon-btn primary"
                                                title="Open in a new tab"
                                                [disabled]="svc.status !== 'Ready'"
                                                (click)="openService(svc)">
                                                <i class="pi pi-external-link"></i>
                                            </button>
                                        }
                                        <button
                                            class="icon-btn danger"
                                            title="Delete"
                                            (click)="confirmDelete(svc)">
                                            <i class="pi pi-trash"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    `,
})
export class ServiceListComponent {
    private readonly api = inject(ServiceApiService);
    private readonly context = inject(ProjectContextService);
    private readonly messageService = inject(MessageService);
    private readonly confirmationService = inject(ConfirmationService);
    private readonly destroyRef = inject(DestroyRef);
    private readonly router = inject(Router);

    serviceFilter = input<string>();
    emptyMessage = input('No instances deployed yet.');
    emptyTitle = input('No instances yet');
    // URL segments under /project/:projectId for the parent "area" (e.g.
    // ['services'] for Jupyter, ['spark', 'history-server'] for Spark
    // History Server). Used for detail/edit navigation so the sidebar
    // highlights the correct entry.
    basePath = input<string[]>(['services']);

    deploy = output<void>();

    services = signal<ServiceInstance[]>([]);
    loading = signal(true);
    query = signal('');
    filterStatus = signal<StatusFilter>('All');

    statChips = computed(() => {
        const list = this.services();
        return [
            { key: 'All' as StatusFilter, count: list.length, tone: 'neutral' as const },
            {
                key: 'Ready' as StatusFilter,
                count: list.filter((s) => s.status === 'Ready').length,
                tone: 'success' as const,
            },
            {
                key: 'Installing' as StatusFilter,
                count: list.filter((s) => s.status === 'Installing' || s.status === 'Updating').length,
                tone: 'warn' as const,
            },
            {
                key: 'Error' as StatusFilter,
                count: list.filter((s) => s.status === 'Error').length,
                tone: 'danger' as const,
            },
        ];
    });

    filtered = computed(() => {
        const q = this.query().trim().toLowerCase();
        const status = this.filterStatus();
        return this.services().filter((s) => {
            if (status !== 'All') {
                // "Installing" tab groups Installing + Updating (in-progress reconciliation)
                const matches = status === 'Installing'
                    ? (s.status === 'Installing' || s.status === 'Updating')
                    : s.status === status;
                if (!matches) return false;
            }
            if (!q) return true;
            const hay = `${s.name} ${s.service} ${s.serviceTag} ${s.targetNamespace ?? ''}`.toLowerCase();
            return hay.includes(q);
        });
    });

    hasFilter = computed(() => !!this.query().trim() || this.filterStatus() !== 'All');

    private streamSub: Subscription | null = null;

    constructor() {
        effect(() => {
            const project = this.context.currentProject();
            if (project) {
                this.loadServices(project.name);
                this.subscribeStream(project.name);
            }
        });

        this.destroyRef.onDestroy(() => {
            this.streamSub?.unsubscribe();
        });
    }

    setStatus(s: StatusFilter) {
        this.filterStatus.set(s);
    }

    private matchesFilter(instance: ServiceInstance): boolean {
        const filter = this.serviceFilter();
        return !filter || instance.service === filter;
    }

    private loadServices(projectId: string) {
        this.loading.set(true);
        this.api.getServices(projectId).subscribe({
            next: (data) => {
                this.services.set(data.filter((s) => this.matchesFilter(s)));
                this.loading.set(false);
            },
            error: () => {
                this.messageService.add({
                    severity: 'error',
                    summary: 'Error',
                    detail: 'Failed to load services',
                });
                this.loading.set(false);
            },
        });
    }

    private subscribeStream(projectId: string) {
        this.streamSub?.unsubscribe();
        this.streamSub = this.api.getServicesStream(projectId).subscribe({
            next: (event) => {
                if (!this.matchesFilter(event.object)) return;

                const current = [...this.services()];
                const idx = current.findIndex((s) => s.name === event.object.name);

                if (event.type === 'DELETED') {
                    if (idx !== -1) current.splice(idx, 1);
                } else if (idx !== -1) {
                    current[idx] = event.object;
                } else {
                    current.push(event.object);
                }
                this.services.set(current);
            },
        });
    }

    tagClass(status: string): string {
        switch (status) {
            case 'Ready':
            case 'Running':
                return 'okdp-tag-success';
            case 'Installing':
            case 'Updating':
                return 'okdp-tag-warn';
            case 'Error':
            case 'CrashLoopBackOff':
            case 'Failed':
                return 'okdp-tag-danger';
            default:
                return 'okdp-tag-info';
        }
    }

    editService(svc: ServiceInstance) {
        const project = this.context.currentProject();
        if (project) {
            this.router.navigate(
                ['/project', project.name, ...this.basePath(), svc.name, 'edit'],
                { queryParams: { returnTo: this.router.url } },
            );
        }
    }

    viewDetail(svc: ServiceInstance) {
        const project = this.context.currentProject();
        if (project) {
            this.router.navigate(
                ['/project', project.name, ...this.basePath(), svc.name],
                { queryParams: { returnTo: this.router.url } },
            );
        }
    }

    openService(svc: ServiceInstance) {
        if (svc.url) {
            window.open(svc.url, '_blank');
        }
    }

    confirmDelete(svc: ServiceInstance) {
        this.confirmationService.confirm({
            message: `This will remove "${svc.name}" and all its pods. This cannot be undone.`,
            header: 'Delete this instance?',
            icon: 'pi pi-exclamation-triangle',
            acceptButtonStyleClass: 'p-button-danger',
            accept: () => this.deleteService(svc),
        });
    }

    private deleteService(svc: ServiceInstance) {
        const project = this.context.currentProject();
        if (!project) return;

        this.api.deleteService(project.name, svc.name).subscribe({
            next: () => {
                this.messageService.add({
                    severity: 'success',
                    summary: 'Instance deleted',
                    detail: `"${svc.name}" has been removed`,
                });
                this.services.set(this.services().filter((s) => s.name !== svc.name));
            },
            error: (err) => {
                const msg = err?.error?.error || 'Failed to delete instance';
                this.messageService.add({ severity: 'error', summary: 'Error', detail: msg });
            },
        });
    }
}

// src/features/project-console/services/service-list.tsx
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Toast } from 'primereact/toast';
import DeleteConfirmDialog from '../../../shared/components/delete-confirm-dialog';
import EmptyState from '../../../shared/components/empty-state';
import SearchFilter from '../../../shared/components/search-filter';
import { serviceApi } from '../../../core/api/service-api';
import { applyListEvent } from '../../../core/api/sse';
import { readUiCache, writeUiCache } from '../../../core/api/ui-cache';
import type { ServiceInstance } from '../../../core/models/service.model';
import { useToastMessages } from '../../../shared/hooks/use-toast-messages';
import {
  apiErrorMessage,
  formatMediumDate,
  isTransitioning,
  openInNewTab,
  statusTone,
} from './service-utils';
import { StatusTag } from '../../../shared/components/status-tag';

type StatusFilter = 'All' | 'Ready' | 'Installing' | 'Updating' | 'Error';

export interface ServiceListProps {
  serviceFilter?: string;
  emptyMessage?: string;
  emptyTitle?: string;
  /**
   * URL segments under /projects/:projectId for the parent "area" (e.g.
   * ['jupyterhub'], ['spark', 'history-server']). Used for detail/edit
   * navigation so the sidebar highlights the correct entry.
   */
  basePath?: string[];
  onDeploy: () => void;
}

export function ServiceList({
  serviceFilter,
  emptyMessage = 'No instances deployed yet.',
  emptyTitle = 'No instances yet',
  basePath = ['jupyterhub'],
  onDeploy,
}: ServiceListProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const { projectId: projectName } = useParams<{ projectId: string }>();
  const { toast, showSuccess, showError } = useToastMessages();

  const [services, setServices] = useState<ServiceInstance[]>([]);
  // Deletion runs until the backend confirms (slow helm uninstall); these
  // names render as "Deleting…" with their row actions disabled.
  const [deletingNames, setDeletingNames] = useState<Set<string>>(new Set());
  // Instance pending the type-to-confirm deletion dialog.
  const [deleteTarget, setDeleteTarget] = useState<ServiceInstance | null>(null);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState<StatusFilter>('All');

  useEffect(() => {
    if (!projectName) return;

    const matchesFilter = (instance: ServiceInstance) =>
      !serviceFilter || instance.service === serviceFilter;

    let cancelled = false;
    // Recent snapshot: skip the loading panel; the fetch below still runs.
    const cached = readUiCache<ServiceInstance[]>(`services:${projectName}`);
    setServices(cached ? cached.filter(matchesFilter) : []);
    setLoading(!cached);
    serviceApi
      .getServices(projectName)
      .then((data) => {
        if (cancelled) return;
        writeUiCache(`services:${projectName}`, data);
        setServices(data.filter(matchesFilter));
        setLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        showError('Failed to load services');
        setLoading(false);
      });

    const unsubscribe = serviceApi.subscribeServices(projectName, {
      next: (event) => {
        if (!matchesFilter(event.object)) return;
        if (event.type === 'DELETED') {
          setDeletingNames((names) => {
            if (!names.has(event.object.name)) return names;
            const next = new Set(names);
            next.delete(event.object.name);
            return next;
          });
        }
        setServices((current) => applyListEvent(current, event, (s) => s.name));
      },
    });

    return () => {
      cancelled = true;
      unsubscribe();
    };
  }, [projectName, serviceFilter, showError]);

  const statChips = useMemo(
    () => [
      { key: 'All' as StatusFilter, count: services.length, tone: 'neutral' as const },
      {
        key: 'Ready' as StatusFilter,
        count: services.filter((s) => s.status === 'Ready').length,
        tone: 'success' as const,
      },
      {
        key: 'Installing' as StatusFilter,
        count: services.filter((s) => s.status === 'Installing' || s.status === 'Updating').length,
        tone: 'warn' as const,
      },
      {
        key: 'Error' as StatusFilter,
        count: services.filter((s) => s.status === 'Error').length,
        tone: 'danger' as const,
      },
    ],
    [services],
  );

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return services.filter((s) => {
      if (filterStatus !== 'All') {
        // "Installing" tab groups Installing + Updating (in-progress reconciliation)
        const matches =
          filterStatus === 'Installing'
            ? s.status === 'Installing' || s.status === 'Updating'
            : s.status === filterStatus;
        if (!matches) return false;
      }
      if (!q) return true;
      const hay = `${s.name} ${s.service} ${s.serviceTag} ${s.targetNamespace ?? ''}`.toLowerCase();
      return hay.includes(q);
    });
  }, [services, query, filterStatus]);

  const hasFilter = !!query.trim() || filterStatus !== 'All';
  const currentUrl = location.pathname + location.search;

  const viewDetail = (svc: ServiceInstance) => {
    if (projectName) {
      navigate(
        `/projects/${projectName}/${basePath.join('/')}/${svc.name}?returnTo=${encodeURIComponent(currentUrl)}`,
      );
    }
  };

  const editService = (svc: ServiceInstance) => {
    if (projectName) {
      navigate(
        `/projects/${projectName}/${basePath.join('/')}/${svc.name}/edit?returnTo=${encodeURIComponent(currentUrl)}`,
      );
    }
  };

  const openService = (svc: ServiceInstance) => {
    if (svc.url) {
      openInNewTab(svc.url);
    }
  };

  const confirmDelete = (svc: ServiceInstance) => setDeleteTarget(svc);

  const deleteInstance = (svc: ServiceInstance) => {
    setDeleteTarget(null);
    if (!projectName) return;
    const clearDeleting = () =>
      setDeletingNames((names) => {
        const next = new Set(names);
        next.delete(svc.name);
        return next;
      });
    setDeletingNames((names) => new Set(names).add(svc.name));
    serviceApi
      .deleteService(projectName, svc.name)
      .then(() => {
        showSuccess(`"${svc.name}" has been removed`, 'Instance deleted');
        clearDeleting();
        setServices((current) => current.filter((s) => s.name !== svc.name));
      })
      .catch((err) => {
        clearDeleting();
        showError(apiErrorMessage(err, 'Failed to delete instance'));
      });
  };

  return (
    <>
      <Toast ref={toast} />
      <DeleteConfirmDialog
        resourceName={deleteTarget?.name ?? null}
        resourceKind="instance"
        message={
          deleteTarget && (
            <>
              This will remove <strong>{deleteTarget.name}</strong> and all its pods. This cannot be
              undone.
            </>
          )
        }
        onHide={() => setDeleteTarget(null)}
        onConfirm={() => deleteTarget && deleteInstance(deleteTarget)}
      />

      <div className="stat-strip">
        {statChips.map((chip) => (
          <button
            key={chip.key}
            className={[
              'stat-chip',
              filterStatus === chip.key ? 'active' : '',
              chip.tone === 'warn' ? 'chip-warn' : '',
              chip.tone === 'danger' ? 'chip-danger' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={() => setFilterStatus(chip.key)}
          >
            <span className="sc-label">{chip.key}</span>
            <span className="sc-count">{chip.count}</span>
          </button>
        ))}
      </div>

      <SearchFilter
        value={query}
        onChange={setQuery}
        placeholder="Filter by name, version, namespace…"
        hint={`${filtered.length} of ${services.length}`}
      />

      {loading ? (
        <EmptyState variant="panel" icon="pi pi-spin pi-spinner" title="Loading instances…" />
      ) : filtered.length === 0 ? (
        <EmptyState
          variant="panel"
          icon={hasFilter ? 'pi pi-search' : 'pi pi-server'}
          title={hasFilter ? 'No instances match' : emptyTitle}
          description={
            hasFilter ? 'Try clearing the filter or searching by a different term.' : emptyMessage
          }
          action={
            !hasFilter && (
              <button className="create-btn" onClick={onDeploy}>
                <i className="pi pi-plus"></i>
                <span>New instance</span>
              </button>
            )
          }
        />
      ) : (
        <div className="okdp-table-wrapper">
          <table className="okdp-table">
            <thead>
              <tr>
                <th style={{ width: '32%' }}>Instance</th>
                <th style={{ width: '16%' }}>Version</th>
                <th style={{ width: '12%' }}>Status</th>
                <th style={{ width: '14%' }}>Namespace</th>
                <th style={{ width: '12%' }}>Created</th>
                <th style={{ width: '14%' }}></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((svc) => {
                const deleting = deletingNames.has(svc.name);
                return (
                  <tr
                    key={svc.name}
                    className={deleting ? 'clickable-row opacity-50' : 'clickable-row'}
                    onClick={() => viewDetail(svc)}
                  >
                    <td>
                      <div className="cell-instance">
                        <span className="cell-name">{svc.name}</span>
                        <span className="cell-ns mono">{svc.releaseName || svc.service}</span>
                      </div>
                    </td>
                    <td>
                      <span className="version-badge mono">{svc.serviceTag}</span>
                    </td>
                    <td>
                      {deleting ? (
                        <StatusTag
                          value="Deleting…"
                          tone="warning"
                          icon={<i className="pi pi-spin pi-spinner text-[0.7rem]" />}
                        />
                      ) : (
                        <StatusTag
                          value={svc.status}
                          tone={statusTone(svc.status)}
                          pulse={isTransitioning(svc.status)}
                        />
                      )}
                    </td>
                    <td>
                      <span className="muted-text small mono">{svc.targetNamespace || '—'}</span>
                    </td>
                    <td>
                      <span className="muted-text">
                        {svc.createdAt ? formatMediumDate(svc.createdAt) : '—'}
                      </span>
                    </td>
                    <td onClick={(e) => e.stopPropagation()}>
                      <div className="okdp-actions">
                        <button
                          className="icon-btn"
                          title="View details"
                          onClick={() => viewDetail(svc)}
                        >
                          <i className="pi pi-eye"></i>
                        </button>
                        <button
                          className="icon-btn"
                          title="Edit"
                          disabled={deleting}
                          onClick={() => editService(svc)}
                        >
                          <i className="pi pi-pencil"></i>
                        </button>
                        {svc.url && (
                          <button
                            className="icon-btn primary"
                            title="Open in a new tab"
                            disabled={svc.status !== 'Ready'}
                            onClick={() => openService(svc)}
                          >
                            <i className="pi pi-external-link"></i>
                          </button>
                        )}
                        <button
                          className="icon-btn danger"
                          title="Delete"
                          disabled={deleting}
                          onClick={() => confirmDelete(svc)}
                        >
                          <i className="pi pi-trash"></i>
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}
