// src/shared/components/dynamic-schema-form.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useRef, useState } from 'react';
import { InputText } from 'primereact/inputtext';
import { InputNumber } from 'primereact/inputnumber';
import { InputTextarea } from 'primereact/inputtextarea';
import { Dropdown } from 'primereact/dropdown';
import { InputSwitch } from 'primereact/inputswitch';
import { Password } from 'primereact/password';
import { Button } from 'primereact/button';
import { connectionApi, type SelectableConnection } from '../../core/api/connection-api';
import { formatLabel } from '../utils/format-label';

/* The dsf-root class scopes the .field-invalid PrimeReact-input override in
   the PrimeReact overrides section of styles.css. */
const FIELD_CLASS = 'mb-5 flex flex-col gap-1.5';
const FIELD_LABEL_CLASS = 'block text-[13px] font-medium tracking-[-0.005em] text-fg-secondary';

export interface SchemaField {
  name: string;
  type: string;
  default: any;
  description?: string;
  title?: string;
  enum?: any[];
  required?: boolean;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  multipleOf?: number;
  /** Kept for structured values: the shape of an array's items, and whether an
   *  object accepts free keys. Without them a mapping and a datasource list are
   *  indistinguishable. */
  items?: any;
  additionalProperties?: any;
  properties?: any;
  'x-kubocd-connection-ref'?: { contract: string };
  'x-ui-order'?: number;
  'x-ui-group'?: string;
  'x-ui-widget'?: string;
  'x-ui-condition'?: { field: string; value: any };
  'x-ui-advanced'?: boolean;
  'x-ui-columns'?: number;
  'x-ui-col-span'?: number;
  'x-ui-placeholder'?: string;
}

export interface FieldGroup {
  name: string;
  columns: number;
  fields: SchemaField[];
  advancedFields: SchemaField[];
}

export interface DynamicSchemaFormProps {
  schema: any;
  /** Needed to offer the project's connections on nested connectionRef fields
   *  (a datasource naming a trino connection). Omitted, those stay text. */
  projectId?: string;
  initialValues?: Record<string, any>;
  onParametersChange: (params: Record<string, any>) => void;
  /**
   * Called with true when every field passes local validation (currently K8s
   * quantity format on CPU/memory fields). Parent components can wire this
   * to disable the Save/Deploy button.
   */
  onValidityChange?: (valid: boolean) => void;
}

const GROUP_ICONS: Record<string, string> = {
  General: 'pi-sliders-h',
  Networking: 'pi-globe',
  Storage: 'pi-database',
  Security: 'pi-shield',
  Resources: 'pi-server',
  Authentication: 'pi-lock',
};

function getGroupIcon(groupName: string): string {
  return GROUP_ICONS[groupName] || 'pi-cog';
}

/** Structured parameters (a role mapping, a list of datasources) edited as
 *  JSON. The text being typed is kept locally, otherwise every keystroke would
 *  have to parse: a half-written object is not valid JSON. The parsed value is
 *  only pushed up when it parses, so a typo never replaces the structure. */
function JsonField({
  field,
  value,
  invalid,
  onChange,
}: {
  field: SchemaField;
  value: unknown;
  invalid: boolean;
  onChange: (parsed: unknown) => void;
}) {
  const serialize = (v: unknown) =>
    v === undefined ||
    v === null ||
    v === '' ||
    (typeof v === 'object' && Object.keys(v).length === 0)
      ? ''
      : JSON.stringify(v, null, 2);

  const [text, setText] = useState(() => serialize(value));
  const [badJson, setBadJson] = useState(false);
  // Follow the value while the user is not the one changing it (version switch,
  // schema reload), without fighting their cursor.
  const focused = useRef(false);
  useEffect(() => {
    if (!focused.current) setText(serialize(value));
     
  }, [value]);

  const commit = (next: string) => {
    setText(next);
    if (next.trim() === '') {
      setBadJson(false);
      onChange(field.type === 'array' ? [] : {});
      return;
    }
    try {
      onChange(JSON.parse(next));
      setBadJson(false);
    } catch {
      setBadJson(true);
    }
  };

  return (
    <>
      <InputTextarea
        id={field.name}
        value={text}
        rows={4}
        spellCheck={false}
        placeholder={field.type === 'array' ? '[]' : '{}'}
        className={`w-full mono${invalid || badJson ? ' field-invalid' : ''}`}
        onFocus={() => (focused.current = true)}
        onBlur={() => {
          focused.current = false;
          if (!badJson) setText(serialize(value));
        }}
        onChange={(e) => commit(e.target.value)}
      />
      {badJson && <small className="field-hint err">Invalid JSON, the value is not saved.</small>}
    </>
  );
}

/** A free-form map, edited as pairs. This is what a role mapping is: a claim
 *  value on the left, the roles it grants on the right. Several roles are
 *  comma-separated, and the value keeps the shape it had, list or plain string. */
function KeyValueField({
  value,
  onChange,
}: {
  value: Record<string, unknown>;
  onChange: (next: Record<string, unknown>) => void;
}) {
  const asText = (v: unknown) => (Array.isArray(v) ? v.join(', ') : String(v ?? ''));
  const asValue = (text: string, previous: unknown) => {
    const parts = text.split(',').map((p) => p.trim()).filter(Boolean);
    return Array.isArray(previous) || parts.length > 1 ? parts : text.trim();
  };

  // The rows are held here rather than derived from the object, because a row
  // being typed is not yet a valid entry: a blank key, or a key that duplicates
  // another until the typing is finished, has nowhere to live in an object.
  const [rows, setRows] = useState<[string, unknown][]>(() => Object.entries(value));
  const emittedRef = useRef(value);

  useEffect(() => {
    if (value !== emittedRef.current) {
      setRows(Object.entries(value));
      emittedRef.current = value;
    }
  }, [value]);

  const emit = (next: [string, unknown][]) => {
    setRows(next);
    const object: Record<string, unknown> = {};
    next.forEach(([k, v]) => {
      if (k) object[k] = v;
    });
    emittedRef.current = object;
    onChange(object);
  };

  const replace = (index: number, key: string, raw: string) => {
    emit(rows.map(([k, v], i) => (i === index ? [key, asValue(raw, v)] : [k, v])));
  };

  return (
    <div className="flex flex-col gap-2">
      {rows.map(([key, val], index) => (
        <div key={index} className="flex items-center gap-2">
          <InputText
            className="w-full mono"
            value={key}
            placeholder="OIDC role"
            onChange={(e) => replace(index, e.target.value, asText(val))}
          />
          <span className="text-fg-secondary">&rarr;</span>
          <InputText
            className="w-full mono"
            value={asText(val)}
            placeholder="granted roles, comma-separated"
            onChange={(e) => replace(index, key, e.target.value)}
          />
          <Button
            type="button"
            icon="pi pi-times"
            text
            aria-label={`Remove ${key || 'the empty entry'}`}
            onClick={() => emit(rows.filter((_, i) => i !== index))}
          />
        </div>
      ))}
      <div>
        <Button
          type="button"
          label="Add an entry"
          icon="pi pi-plus"
          text
          onClick={() => emit([...rows, ['', '']])}
        />
      </div>
    </div>
  );
}

/** A list of objects whose shape the schema knows: one row per entry, one
 *  column per property. A property carrying a connection marker gets the
 *  project's connections of that contract rather than a free-text field, which
 *  is the only way to name one without copying it by hand. */
function ObjectListField({
  field,
  value,
  projectId,
  onChange,
}: {
  field: SchemaField;
  value: any[];
  projectId?: string;
  onChange: (next: any[]) => void;
}) {
  const props: Record<string, any> = field.items?.properties || {};
  const columns = Object.keys(props);
  const [connections, setConnections] = useState<Record<string, SelectableConnection[]>>({});

  // One lookup per contract used by the row, not per row.
  useEffect(() => {
    if (!projectId) return;
    const contracts = columns
      .map((c) => props[c]?.['x-kubocd-connection-ref']?.contract)
      .filter((i): i is string => !!i);
    [...new Set(contracts)].forEach((contract) => {
      connectionApi
        .selectable(projectId, contract)
        .then((found) => setConnections((c) => ({ ...c, [contract]: found })))
        .catch(() => setConnections((c) => ({ ...c, [contract]: [] })));
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, field.name]);

  const patch = (index: number, column: string, columnValue: any) =>
    onChange(value.map((row, i) => (i === index ? { ...row, [column]: columnValue } : row)));

  return (
    <div className="flex flex-col gap-2">
      {value.map((row, index) => (
        <div key={index} className="flex items-end gap-2">
          {columns.map((column) => {
            const contract = props[column]?.['x-kubocd-connection-ref']?.contract;
            return (
              <div key={column} className="flex-1">
                <label className="text-[12px] text-fg-secondary">{formatLabel(column)}</label>
                {contract ? (
                  <Dropdown
                    value={row[column] ?? null}
                    options={(connections[contract] || []).map((c) => ({
                      label: c.name,
                      value: c.name,
                    }))}
                    optionLabel="label"
                    optionValue="value"
                    placeholder={`Select a ${contract} connection`}
                    appendTo={document.body}
                    className="w-full"
                    onChange={(e) => patch(index, column, e.value)}
                  />
                ) : (
                  <InputText
                    className="w-full"
                    value={row[column] ?? ''}
                    placeholder={props[column]?.default ?? ''}
                    onChange={(e) => patch(index, column, e.target.value)}
                  />
                )}
              </div>
            );
          })}
          <Button
            type="button"
            icon="pi pi-times"
            text
            aria-label="Retirer la ligne"
            onClick={() => onChange(value.filter((_, i) => i !== index))}
          />
        </div>
      ))}
      <div>
        <Button
          type="button"
          label="Add"
          icon="pi pi-plus"
          text
          onClick={() => onChange([...value, {}])}
        />
      </div>
    </div>
  );
}

function resolveWidget(field: SchemaField): string {
  const widget = field['x-ui-widget'];
  if (widget) return widget;

  if (field.enum && field.enum.length > 0) return 'select';
  if (field.type === 'boolean') return 'toggle';
  if (field.type === 'integer' || field.type === 'number') return 'number';
  // A structured value in a text input renders as [object Object], and editing
  // it would replace the structure by that string.
  if (field.type === 'array' && field.items?.properties) return 'object-list';
  if (field.type === 'object' && Object.keys(field.properties || {}).length === 0) return 'key-value';
  if (field.type === 'object' || field.type === 'array') return 'yaml';
  return 'text';
}

/** How a numeric field is displayed. Two things a general-purpose number input
 *  gets wrong here: thousands separators turn port 5432 into "5,432", and a
 *  forced decimal turns it into "5432.0". Neither is a number anyone typed.
 *  Decimals are allowed but never imposed, so a replica count stays whole and
 *  a CPU request can still be 0.5. */
function fractionProps(field: SchemaField) {
  return {
    useGrouping: false,
    minFractionDigits: undefined,
    maxFractionDigits: field.type === 'number' ? 3 : 0,
  };
}

function toOptions(enumValues: any[]): { label: string; value: any }[] {
  return enumValues.map((v) => ({ label: String(v), value: v }));
}

function buildFields(schema: any): SchemaField[] {
  const properties = schema?.properties || {};
  const required = new Set<string>(schema?.required || []);

  const fields: SchemaField[] = Object.entries(properties).map(([name, def]: [string, any]) => ({
    name,
    type: def.type || 'string',
    default: def.default,
    description: def.description,
    title: def.title,
    enum: def.enum,
    required: required.has(name),
    minimum: def.minimum,
    maximum: def.maximum,
    minLength: def.minLength,
    maxLength: def.maxLength,
    pattern: def.pattern,
    multipleOf: def.multipleOf,
    items: def.items,
    additionalProperties: def.additionalProperties,
    properties: def.properties,
    'x-kubocd-connection-ref': def['x-kubocd-connection-ref'],
    'x-ui-order': def['x-ui-order'] ?? 999,
    'x-ui-group': def['x-ui-group'] || 'General',
    'x-ui-widget': def['x-ui-widget'],
    'x-ui-condition': def['x-ui-condition'],
    'x-ui-advanced': def['x-ui-advanced'] || false,
    'x-ui-columns': def['x-ui-columns'],
    'x-ui-col-span': def['x-ui-col-span'],
    'x-ui-placeholder': def['x-ui-placeholder'],
  }));

  const visibleFields = fields.filter((f) => f['x-ui-widget'] !== 'profile-editor');
  visibleFields.sort((a, b) => a['x-ui-order']! - b['x-ui-order']!);
  return visibleFields;
}

function buildGroups(visibleFields: SchemaField[]): FieldGroup[] {
  const groupMap = new Map<string, FieldGroup>();
  const groupOrder: string[] = [];

  for (const field of visibleFields) {
    const groupName = field['x-ui-group']!;
    if (!groupMap.has(groupName)) {
      groupMap.set(groupName, {
        name: groupName,
        columns: field['x-ui-columns'] || 1,
        fields: [],
        advancedFields: [],
      });
      groupOrder.push(groupName);
    }
    const group = groupMap.get(groupName)!;
    if (field['x-ui-columns'] && field['x-ui-columns'] > group.columns) {
      group.columns = field['x-ui-columns'];
    }
    if (field['x-ui-advanced']) {
      group.advancedFields.push(field);
    } else {
      group.fields.push(field);
    }
  }

  return groupOrder.map((name) => groupMap.get(name)!);
}

function initialFormValues(
  fields: SchemaField[],
  initialValues: Record<string, any>,
): Record<string, any> {
  const values: Record<string, any> = {};
  for (const f of fields) {
    if (initialValues[f.name] !== undefined) {
      values[f.name] = initialValues[f.name];
    } else if (f.type === 'array') {
      values[f.name] = Array.isArray(f.default) ? [...f.default] : [];
    } else {
      values[f.name] =
        f.default ??
        (f.type === 'boolean' ? false : f.type === 'number' || f.type === 'integer' ? 0 : '');
    }
  }
  return values;
}

// A K8s resource.Quantity accepts:
//   - a bare decimal: "1", "1.5"
//   - decimal + binary SI suffix: "500Mi", "2Gi", "10Ki"
//   - decimal + metric SI suffix: "500m" (milli for CPU), "1k", "1G"
//   - scientific notation: "1.5e3"
// Empty values are allowed — a missing optional parameter falls back to
// the schema default server-side.
const K8S_QUANTITY_RE = /^[0-9]+(\.[0-9]+)?(m|n|u|[kKMGTPE]i?|e[-+]?[0-9]+)?$/;

function isQuantityField(field: SchemaField): boolean {
  if (field.type !== 'string') return false;
  // Enum values are server-chosen, never free-form quantities.
  if (field.enum && field.enum.length > 0) return false;
  // formatLabel splits camelCase/underscores so \bmemory\b matches "driverMemory".
  const hay =
    `${formatLabel(field.name)} ${field.description ?? ''} ${field.title ?? ''}`.toLowerCase();
  return /\b(cpu|memory|mem)\b/.test(hay) || /request|limit/.test(field.name.toLowerCase());
}

function validateField(field: SchemaField, value: unknown): string {
  if (value === undefined || value === null || value === '') return '';
  if (!isQuantityField(field)) return '';
  const v = String(value).trim();
  if (!K8S_QUANTITY_RE.test(v)) {
    return `Invalid Kubernetes quantity. Use a number with an optional suffix (e.g. "500Mi", "2Gi", "500m", "1").`;
  }
  return '';
}

// A bare digit is a VALID quantity (bytes for memory, cores for CPU) but is
// often a unit slip, and schema defaults such as "1" core are legitimate:
// this nudges without blocking the deploy.
function warnField(field: SchemaField, value: unknown): string {
  if (value === undefined || value === null || value === '') return '';
  if (!isQuantityField(field)) return '';
  const v = String(value).trim();
  if (!K8S_QUANTITY_RE.test(v)) return '';
  if (/^[0-9]+(\.[0-9]+)?$/.test(v)) {
    const lower = field.name.toLowerCase();
    if (lower.includes('memory') || lower.includes('mem')) {
      return `"${v}" is read as ${v} byte(s). Did you mean "${v}Mi" or "${v}Gi"?`;
    }
    if (lower.includes('cpu')) {
      return `"${v}" is read as ${v} core(s). Add an "m" suffix for milli-cores if that is not intended.`;
    }
  }
  return '';
}

// One-level (non-transitive) x-ui-condition semantics, shared by render,
// validation and emission so a hidden field can neither block submission
// nor leak its stale value into the emitted params.
function isVisible(field: SchemaField, values: Record<string, any>): boolean {
  const cond = field['x-ui-condition'];
  if (!cond) return true;
  return values[cond.field] === cond.value;
}

// Stable default — an inline `{}` default would change identity on every
// parent render and re-trigger the values-rebuild effect in a loop.
const EMPTY_VALUES: Record<string, any> = {};

export function DynamicSchemaForm({
  schema,
  projectId,
  initialValues = EMPTY_VALUES,
  onParametersChange,
  onValidityChange,
}: DynamicSchemaFormProps) {
  const fields = useMemo(() => (schema ? buildFields(schema) : []), [schema]);
  const groups = useMemo(() => buildGroups(fields), [fields]);

  const [values, setValues] = useState<Record<string, any>>({});
  const [advancedOpen, setAdvancedOpen] = useState<Record<string, boolean>>({});

  // Rebuild values when the schema or the initial values change
  useEffect(() => {
    if (schema) {
      setValues(initialFormValues(fields, initialValues));
    }
  }, [schema, fields, initialValues]);

  const fieldsByName = useMemo(() => new Map(fields.map((f) => [f.name, f])), [fields]);

  const fieldErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    for (const field of fields) {
      if (!isVisible(field, values)) continue;
      const msg = validateField(field, values[field.name]);
      if (msg) errors[field.name] = msg;
    }
    return errors;
  }, [fields, values]);

  const fieldWarnings = useMemo(() => {
    const warnings: Record<string, string> = {};
    for (const field of fields) {
      if (!isVisible(field, values)) continue;
      const msg = warnField(field, values[field.name]);
      if (msg) warnings[field.name] = msg;
    }
    return warnings;
  }, [fields, values]);

  // Emit on every change, including initialization (legacy behavior).
  // Refs keep parent re-renders from re-triggering the effect.
  const onParametersChangeRef = useRef(onParametersChange);
  onParametersChangeRef.current = onParametersChange;
  const onValidityChangeRef = useRef(onValidityChange);
  onValidityChangeRef.current = onValidityChange;

  useEffect(() => {
    onValidityChangeRef.current?.(Object.keys(fieldErrors).length === 0);

    const filtered: Record<string, any> = {};
    for (const [key, val] of Object.entries(values)) {
      // Unknown keys (no matching field) are treated as visible.
      const field = fieldsByName.get(key);
      if (field && !isVisible(field, values)) continue;
      if (Array.isArray(val) || (val !== '' && val !== null && val !== undefined)) {
        filtered[key] = val;
      }
    }
    onParametersChangeRef.current(filtered);
  }, [values, fieldErrors, fieldsByName]);

  const setValue = (name: string, value: any) => {
    setValues((v) => ({ ...v, [name]: value }));
  };

  const isFieldVisible = (field: SchemaField): boolean => isVisible(field, values);

  const toggleAdvanced = (groupName: string) => {
    setAdvancedOpen((open) => ({ ...open, [groupName]: !open[groupName] }));
  };

  const renderWidget = (field: SchemaField) => {
    const value = values[field.name];
    // The field-invalid CSS targets the element carrying the class, so it is
    // passed into each widget rather than set on a wrapper.
    const invalid = fieldErrors[field.name] ? ' field-invalid' : '';
    switch (resolveWidget(field)) {
      case 'password':
        return (
          <Password
            inputId={field.name}
            value={value ?? ''}
            placeholder={field['x-ui-placeholder'] || ''}
            feedback={false}
            toggleMask
            className="w-full"
            inputClassName={invalid ? 'field-invalid' : undefined}
            onChange={(e) => setValue(field.name, e.target.value)}
          />
        );
      case 'object-list':
        return (
          <ObjectListField
            field={field}
            value={Array.isArray(value) ? value : []}
            projectId={projectId}
            onChange={(next) => setValue(field.name, next)}
          />
        );
      case 'key-value':
        return (
          <KeyValueField
            value={value && typeof value === 'object' ? (value as Record<string, unknown>) : {}}
            onChange={(next) => setValue(field.name, next)}
          />
        );
      case 'yaml':
        return (
          <JsonField
            field={field}
            value={value}
            invalid={!!fieldErrors[field.name]}
            onChange={(parsed) => setValue(field.name, parsed)}
          />
        );
      case 'textarea':
        return (
          <InputTextarea
            id={field.name}
            value={value ?? ''}
            placeholder={field['x-ui-placeholder'] || ''}
            rows={3}
            className={`w-full${invalid}`}
            onChange={(e) => setValue(field.name, e.target.value)}
          />
        );
      case 'select':
        return (
          <Dropdown
            inputId={field.name}
            value={value}
            options={toOptions(field.enum!)}
            optionLabel="label"
            optionValue="value"
            placeholder={field['x-ui-placeholder'] || 'Select...'}
            className={`w-full${invalid}`}
            onChange={(e) => setValue(field.name, e.value)}
          />
        );
      case 'stepper':
        return (
          <InputNumber
            inputId={field.name}
            value={value ?? null}
            showButtons
            buttonLayout="horizontal"
            step={field.multipleOf || 1}
            min={field.minimum}
            max={field.maximum}
            {...fractionProps(field)}
            incrementButtonIcon="pi pi-plus"
            decrementButtonIcon="pi pi-minus"
            className="w-full"
            onValueChange={(e) => setValue(field.name, e.value)}
          />
        );
      case 'number':
        return (
          <InputNumber
            inputId={field.name}
            value={value ?? null}
            min={field.minimum}
            max={field.maximum}
            step={field.multipleOf || 1}
            {...fractionProps(field)}
            className="w-full"
            onValueChange={(e) => setValue(field.name, e.value)}
          />
        );
      case 'toggle':
        return <InputSwitch checked={!!value} onChange={(e) => setValue(field.name, e.value)} />;
      case 'url':
        return (
          <InputText
            id={field.name}
            type="url"
            value={value ?? ''}
            placeholder={field['x-ui-placeholder'] || ''}
            className={`w-full${invalid}`}
            onChange={(e) => setValue(field.name, e.target.value)}
          />
        );
      default:
        return (
          <InputText
            id={field.name}
            type="text"
            value={value ?? ''}
            placeholder={field['x-ui-placeholder'] || ''}
            className={`w-full${invalid}`}
            onChange={(e) => setValue(field.name, e.target.value)}
          />
        );
    }
  };

  const renderFieldGrid = (group: FieldGroup, groupFields: SchemaField[]) => (
    <div
      className="grid gap-x-5 gap-y-5"
      style={{ gridTemplateColumns: group.columns === 2 ? '1fr 1fr' : '1fr' }}
    >
      {groupFields.map(
        (field) =>
          isFieldVisible(field) && (
            <div
              key={field.name}
              className={FIELD_CLASS}
              style={{
                gridColumn:
                  (field['x-ui-col-span'] || 1) > 1
                    ? `span ${field['x-ui-col-span'] || 1}`
                    : undefined,
              }}
            >
              <label htmlFor={field.name} className={FIELD_LABEL_CLASS}>
                {field.title || formatLabel(field.name)}
                {/* Without this the only sign a field is mandatory is a Save
                    button that stays grey, with nothing saying which one. */}
                {field.required && (
                  <span className="text-danger" aria-hidden="true">
                    {' *'}
                  </span>
                )}
              </label>
              {renderWidget(field)}
              {fieldErrors[field.name] && (
                <small className="mt-1.5 flex items-center gap-1.5 text-[12px] font-medium text-danger">
                  <i className="pi pi-exclamation-triangle text-[13px]"></i>
                  {fieldErrors[field.name]}
                </small>
              )}
              {!fieldErrors[field.name] && fieldWarnings[field.name] && (
                <small className="mt-1.5 flex items-center gap-1.5 text-[12px] font-medium text-amber-600">
                  <i className="pi pi-exclamation-triangle text-[13px]"></i>
                  {fieldWarnings[field.name]}
                </small>
              )}
              {field.description && <small className="field-help">{field.description}</small>}
            </div>
          ),
      )}
    </div>
  );

  if (groups.length === 0) {
    return (
      <div className="dsf-root">
        <div className="flex items-center gap-3 rounded-lg border border-dashed border-border-light bg-surface-secondary p-5 text-[14px] text-fg-secondary">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-accent-blue-light">
            <i className="pi pi-info-circle text-[1rem] text-accent-blue"></i>
          </div>
          <span>This service has no configurable parameters.</span>
        </div>
      </div>
    );
  }

  return (
    <div className="dsf-root">
      <div className="flex flex-col gap-0">
        {groups.map((group, i) => (
          <div
            key={group.name}
            className="animate-[fadeInUp_0.4s_cubic-bezier(0.22,1,0.36,1)_backwards] pb-7 not-last:mb-7 not-last:border-b not-last:border-b-border-light"
            style={{ animationDelay: `${i * 0.06}s` }}
          >
            {(groups.length > 1 || group.name !== 'General') && (
              <div className="mb-5 flex items-center gap-2.5">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-primary-50">
                  <i className={`pi ${getGroupIcon(group.name)} text-[0.85rem] text-primary`}></i>
                </div>
                <h4 className="m-0 text-[15px] font-semibold tracking-[-0.01em] text-fg">
                  {group.name}
                </h4>
              </div>
            )}

            <div className="flex flex-col gap-3">
              {renderFieldGrid(group, group.fields)}

              {group.advancedFields.length > 0 && (
                <>
                  <button
                    type="button"
                    className="group mt-5 mb-2 flex w-full cursor-pointer items-center gap-3 border-none bg-transparent p-0"
                    onClick={() => toggleAdvanced(group.name)}
                  >
                    <span className="h-px flex-1 bg-border-light"></span>
                    <span className="flex items-center gap-1.5 rounded-full bg-primary-50 px-3 py-1 text-[12px] font-medium whitespace-nowrap text-primary transition-colors duration-250 ease-smooth group-hover:bg-primary-100">
                      <i
                        className={`pi ${
                          advancedOpen[group.name] ? 'pi-chevron-up' : 'pi-chevron-down'
                        } text-[10px]`}
                      ></i>
                      {advancedOpen[group.name] ? 'Hide' : 'Show'} advanced options
                    </span>
                    <span className="h-px flex-1 bg-border-light"></span>
                  </button>
                  {advancedOpen[group.name] && (
                    <div className="animate-[fadeInUp_0.3s_cubic-bezier(0.22,1,0.36,1)] pt-2">
                      {renderFieldGrid(group, group.advancedFields)}
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/app/shared/components/dynamic-schema-form.component.ts
import {
    Component,
    Input,
    Output,
    EventEmitter,
    OnChanges,
    SimpleChanges,
    signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { InputTextModule } from 'primeng/inputtext';
import { InputNumberModule } from 'primeng/inputnumber';
import { TextareaModule } from 'primeng/textarea';
import { SelectModule } from 'primeng/select';
import { ToggleSwitchModule } from 'primeng/toggleswitch';
import { PasswordModule } from 'primeng/password';
import { ButtonModule } from 'primeng/button';

export interface SchemaField {
    name: string;
    type: string;
    default: any;
    description?: string;
    title?: string;
    enum?: any[];
    required?: boolean;
    minimum?: number;
    maximum?: number;
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    multipleOf?: number;
    'x-ui-order'?: number;
    'x-ui-group'?: string;
    'x-ui-widget'?: string;
    'x-ui-condition'?: { field: string; value: any };
    'x-ui-advanced'?: boolean;
    'x-ui-columns'?: number;
    'x-ui-col-span'?: number;
    'x-ui-placeholder'?: string;
}

export interface FieldGroup {
    name: string;
    columns: number;
    fields: SchemaField[];
    advancedFields: SchemaField[];
}

@Component({
    selector: 'app-dynamic-schema-form',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        InputTextModule,
        InputNumberModule,
        TextareaModule,
        SelectModule,
        ToggleSwitchModule,
        PasswordModule,
        ButtonModule,
    ],
    template: `
        @if (groups().length === 0) {
            <div class="no-params">
                <div class="no-params-icon">
                    <i class="pi pi-info-circle"></i>
                </div>
                <span>This service has no configurable parameters.</span>
            </div>
        } @else {
            <div class="dynamic-form">
                @for (group of groups(); track group.name; let i = $index) {
                    <div class="form-section-card" [style.animation-delay]="(i * 0.06) + 's'">
                        @if (groups().length > 1 || group.name !== 'General') {
                            <div class="section-card-header">
                                <div class="section-icon-badge">
                                    <i [class]="'pi ' + getGroupIcon(group.name)"></i>
                                </div>
                                <h4 class="section-card-title">{{ group.name }}</h4>
                            </div>
                        }

                        <div class="section-card-body">
                            <ng-container
                                *ngTemplateOutlet="groupContent; context: { $implicit: group }">
                            </ng-container>
                        </div>
                    </div>
                }
            </div>
        }

        <ng-template #groupContent let-group>
            <div class="field-grid" [style.grid-template-columns]="group.columns === 2 ? '1fr 1fr' : '1fr'">
                @for (field of group.fields; track field.name) {
                    @if (isFieldVisible(field)) {
                        <div class="field" [style.grid-column]="(field['x-ui-col-span'] || 1) > 1 ? 'span ' + (field['x-ui-col-span'] || 1) : ''">
                            <label [for]="field.name">{{ field.title || formatLabel(field.name) }}</label>
                            <ng-container *ngTemplateOutlet="fieldWidget; context: { $implicit: field }">
                            </ng-container>
                            @if (field.description) {
                                <small class="field-help">{{ field.description }}</small>
                            }
                        </div>
                    }
                }
            </div>

            @if (group.advancedFields.length > 0) {
                <button class="advanced-toggle" (click)="toggleAdvanced(group.name)">
                    <span class="advanced-toggle-line"></span>
                    <span class="advanced-toggle-label">
                        <i [class]="'pi ' + (advancedOpen()[group.name] ? 'pi-chevron-up' : 'pi-chevron-down')"></i>
                        {{ advancedOpen()[group.name] ? 'Hide' : 'Show' }} advanced options
                    </span>
                    <span class="advanced-toggle-line"></span>
                </button>
                @if (advancedOpen()[group.name]) {
                    <div class="advanced-fields-container">
                        <div class="field-grid" [style.grid-template-columns]="group.columns === 2 ? '1fr 1fr' : '1fr'">
                            @for (field of group.advancedFields; track field.name) {
                                @if (isFieldVisible(field)) {
                                    <div class="field" [style.grid-column]="(field['x-ui-col-span'] || 1) > 1 ? 'span ' + (field['x-ui-col-span'] || 1) : ''">
                                        <label [for]="field.name">{{ field.title || formatLabel(field.name) }}</label>
                                        <ng-container *ngTemplateOutlet="fieldWidget; context: { $implicit: field }">
                                        </ng-container>
                                        @if (field.description) {
                                            <small class="field-help">{{ field.description }}</small>
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                }
            }
        </ng-template>

        <ng-template #fieldWidget let-field>
            @switch (resolveWidget(field)) {
                @case ('password') {
                    <p-password [inputId]="field.name" [(ngModel)]="values[field.name]"
                        [placeholder]="field['x-ui-placeholder'] || ''"
                        [feedback]="false" [toggleMask]="true" styleClass="w-full"
                        (ngModelChange)="emitChange()"></p-password>
                }
                @case ('textarea') {
                    <textarea pTextarea [id]="field.name" [(ngModel)]="values[field.name]"
                        [placeholder]="field['x-ui-placeholder'] || ''"
                        [rows]="3" class="w-full"
                        (ngModelChange)="emitChange()"></textarea>
                }
                @case ('select') {
                    <p-select [inputId]="field.name" [(ngModel)]="values[field.name]"
                        [options]="toOptions(field.enum!)"
                        optionLabel="label" optionValue="value"
                        [placeholder]="field['x-ui-placeholder'] || 'Select...'"
                        styleClass="w-full"
                        (ngModelChange)="emitChange()"></p-select>
                }
                @case ('stepper') {
                    <p-inputNumber [inputId]="field.name" [(ngModel)]="values[field.name]"
                        [showButtons]="true" buttonLayout="horizontal"
                        [step]="field.multipleOf || 1"
                        [min]="field.minimum" [max]="field.maximum"
                        [minFractionDigits]="field.type === 'number' ? 1 : 0"
                        [maxFractionDigits]="field.type === 'number' ? 2 : 0"
                        incrementButtonIcon="pi pi-plus" decrementButtonIcon="pi pi-minus"
                        styleClass="w-full"
                        (ngModelChange)="emitChange()"></p-inputNumber>
                }
                @case ('number') {
                    <p-inputNumber [inputId]="field.name" [(ngModel)]="values[field.name]"
                        [min]="field.minimum" [max]="field.maximum"
                        [step]="field.multipleOf || 1"
                        [minFractionDigits]="field.type === 'number' ? 1 : 0"
                        [maxFractionDigits]="field.type === 'number' ? 2 : 0"
                        styleClass="w-full"
                        (ngModelChange)="emitChange()"></p-inputNumber>
                }
                @case ('toggle') {
                    <p-toggleSwitch [(ngModel)]="values[field.name]"
                        (ngModelChange)="emitChange()"></p-toggleSwitch>
                }
                @case ('url') {
                    <input [id]="field.name" type="url" pInputText [(ngModel)]="values[field.name]"
                        [placeholder]="field['x-ui-placeholder'] || ''"
                        class="w-full"
                        (ngModelChange)="emitChange()" />
                }
                @default {
                    <input [id]="field.name" type="text" pInputText [(ngModel)]="values[field.name]"
                        [placeholder]="field['x-ui-placeholder'] || ''"
                        class="w-full"
                        [class.field-invalid]="!!fieldErrors()[field.name]"
                        (ngModelChange)="emitChange()" />
                    @if (fieldErrors()[field.name]) {
                        <small class="field-error-msg">
                            <i class="pi pi-exclamation-triangle"></i>
                            {{ fieldErrors()[field.name] }}
                        </small>
                    }
                }
            }
        </ng-template>
    `,
    styles: [`
        .dynamic-form {
            display: flex;
            flex-direction: column;
            gap: 0;
        }
        .field-invalid {
            border-color: var(--db-danger, #dc2626) !important;
            background-color: rgba(220, 38, 38, 0.04);
        }
        .field-error-msg {
            display: flex;
            align-items: center;
            gap: 6px;
            margin-top: 6px;
            color: var(--db-danger, #dc2626);
            font-size: 12px;
            font-weight: 500;
        }
        .field-error-msg i { font-size: 13px; }
        .form-section-card {
            animation: fadeInUp 0.4s cubic-bezier(0.22, 1, 0.36, 1) backwards;
            padding-bottom: var(--db-space-xl);
        }
        .form-section-card:not(:last-child) {
            border-bottom: 1px solid var(--db-border-light);
            margin-bottom: var(--db-space-xl);
        }
        .section-card-header {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: var(--db-space-lg);
        }
        .section-icon-badge {
            width: 32px;
            height: 32px;
            border-radius: var(--db-radius-md);
            background: var(--db-primary-50);
            display: flex;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
        }
        .section-icon-badge i {
            font-size: 0.85rem;
            color: var(--db-primary);
        }
        .section-card-title {
            margin: 0;
            font-size: 15px;
            font-weight: 600;
            color: var(--db-text-primary);
            letter-spacing: -0.01em;
        }
        .section-card-body {
            display: flex;
            flex-direction: column;
            gap: var(--db-space-md);
        }
        .field-grid {
            display: grid;
            gap: var(--db-space-lg) 20px;
        }
        .field {
            display: flex;
            flex-direction: column;
            gap: 6px;
        }
        .field label {
            font-weight: 500;
            font-size: 13px;
            color: var(--db-text-secondary);
            letter-spacing: -0.005em;
        }
        .advanced-toggle {
            display: flex;
            align-items: center;
            gap: 12px;
            width: 100%;
            margin: var(--db-space-lg) 0 var(--db-space-sm);
            padding: 0;
            background: none;
            border: none;
            cursor: pointer;
        }
        .advanced-toggle-line {
            flex: 1;
            height: 1px;
            background: var(--db-border-light);
        }
        .advanced-toggle-label {
            display: flex;
            align-items: center;
            gap: 6px;
            font-size: 12px;
            font-weight: 500;
            color: var(--db-primary);
            white-space: nowrap;
            padding: 4px 12px;
            border-radius: var(--db-radius-full);
            background: var(--db-primary-50);
            transition: background var(--db-transition-base);
        }
        .advanced-toggle:hover .advanced-toggle-label {
            background: var(--db-primary-100);
        }
        .advanced-toggle-label i {
            font-size: 10px;
        }
        .advanced-fields-container {
            animation: fadeInUp 0.3s cubic-bezier(0.22, 1, 0.36, 1);
            padding-top: var(--db-space-sm);
        }
        .no-params {
            display: flex;
            align-items: center;
            gap: var(--db-space-md);
            padding: var(--db-space-lg);
            color: var(--db-text-secondary);
            font-size: 14px;
            background: var(--db-bg-secondary);
            border-radius: var(--db-radius-lg);
            border: 1px dashed var(--db-border-light);
        }
        .no-params-icon {
            width: 36px;
            height: 36px;
            border-radius: var(--db-radius-md);
            background: var(--db-accent-blue-light);
            display: flex;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
        }
        .no-params-icon i {
            color: var(--db-accent-blue);
            font-size: 1rem;
        }
    `]
})
export class DynamicSchemaFormComponent implements OnChanges {
    @Input() schema: any = null;
    @Input() initialValues: Record<string, any> = {};
    @Output() parametersChange = new EventEmitter<Record<string, any>>();
    // Emits true when every field passes local validation (currently K8s
    // quantity format on CPU/memory fields). Parent components can wire this
    // to disable the Save/Deploy button.
    @Output() validityChange = new EventEmitter<boolean>();
    fieldErrors = signal<Record<string, string>>({});

    values: Record<string, any> = {};
    groups = signal<FieldGroup[]>([]);
    advancedOpen = signal<Record<string, boolean>>({});

    ngOnChanges(changes: SimpleChanges) {
        if ((changes['schema'] || changes['initialValues']) && this.schema) {
            this.buildForm();
        }
    }

    private buildForm() {
        const properties = this.schema?.properties || {};
        const required = new Set<string>(this.schema?.required || []);

        const fields: SchemaField[] = Object.entries(properties).map(
            ([name, def]: [string, any]) => ({
                name,
                type: def.type || 'string',
                default: def.default,
                description: def.description,
                title: def.title,
                enum: def.enum,
                required: required.has(name),
                minimum: def.minimum,
                maximum: def.maximum,
                minLength: def.minLength,
                maxLength: def.maxLength,
                pattern: def.pattern,
                multipleOf: def.multipleOf,
                'x-ui-order': def['x-ui-order'] ?? 999,
                'x-ui-group': def['x-ui-group'] || 'General',
                'x-ui-widget': def['x-ui-widget'],
                'x-ui-condition': def['x-ui-condition'],
                'x-ui-advanced': def['x-ui-advanced'] || false,
                'x-ui-columns': def['x-ui-columns'],
                'x-ui-col-span': def['x-ui-col-span'],
                'x-ui-placeholder': def['x-ui-placeholder'],
            })
        );

        const visibleFields = fields.filter(f => f['x-ui-widget'] !== 'profile-editor');
        visibleFields.sort((a, b) => (a['x-ui-order']! - b['x-ui-order']!));

        const newValues: Record<string, any> = {};
        for (const f of visibleFields) {
            if (this.initialValues[f.name] !== undefined) {
                newValues[f.name] = this.initialValues[f.name];
            } else if (f.type === 'array') {
                newValues[f.name] = Array.isArray(f.default) ? [...f.default] : [];
            } else {
                newValues[f.name] = f.default ?? (f.type === 'boolean' ? false : f.type === 'number' || f.type === 'integer' ? 0 : '');
            }
        }
        this.values = newValues;

        const groupMap = new Map<string, FieldGroup>();
        const groupOrder: string[] = [];

        for (const field of visibleFields) {
            const groupName = field['x-ui-group']!;
            if (!groupMap.has(groupName)) {
                groupMap.set(groupName, {
                    name: groupName,
                    columns: field['x-ui-columns'] || 1,
                    fields: [],
                    advancedFields: [],
                });
                groupOrder.push(groupName);
            }
            const group = groupMap.get(groupName)!;
            if (field['x-ui-columns'] && field['x-ui-columns'] > group.columns) {
                group.columns = field['x-ui-columns'];
            }
            if (field['x-ui-advanced']) {
                group.advancedFields.push(field);
            } else {
                group.fields.push(field);
            }
        }

        this.groups.set(groupOrder.map(name => groupMap.get(name)!));
        this.emitChange();
    }

    isFieldVisible(field: SchemaField): boolean {
        const cond = field['x-ui-condition'];
        if (!cond) return true;
        return this.values[cond.field] === cond.value;
    }

    resolveWidget(field: SchemaField): string {
        const widget = field['x-ui-widget'];
        if (widget) return widget;

        if (field.enum && field.enum.length > 0) return 'select';
        if (field.type === 'boolean') return 'toggle';
        if (field.type === 'integer' || field.type === 'number') return 'number';
        return 'text';
    }

    formatLabel(name: string): string {
        return name
            .replace(/([A-Z])/g, ' $1')
            .replace(/_/g, ' ')
            .replace(/^./, s => s.toUpperCase())
            .trim();
    }

    toOptions(enumValues: any[]): { label: string; value: any }[] {
        return enumValues.map(v => ({ label: String(v), value: v }));
    }

    private readonly groupIcons: Record<string, string> = {
        General: 'pi-sliders-h',
        Networking: 'pi-globe',
        Storage: 'pi-database',
        Security: 'pi-shield',
        Resources: 'pi-server',
        Authentication: 'pi-lock',
    };

    getGroupIcon(groupName: string): string {
        return this.groupIcons[groupName] || 'pi-cog';
    }

    toggleAdvanced(groupName: string) {
        const current = { ...this.advancedOpen() };
        current[groupName] = !current[groupName];
        this.advancedOpen.set(current);
    }

    emitChange() {
        // Revalidate every field so errors clear as soon as the user fixes them.
        const errors: Record<string, string> = {};
        for (const group of this.groups()) {
            for (const field of [...group.fields, ...group.advancedFields]) {
                const msg = this.validateField(field, this.values[field.name]);
                if (msg) errors[field.name] = msg;
            }
        }
        this.fieldErrors.set(errors);
        this.validityChange.emit(Object.keys(errors).length === 0);

        const filtered: Record<string, any> = {};
        for (const [key, val] of Object.entries(this.values)) {
            if (Array.isArray(val) || (val !== '' && val !== null && val !== undefined)) {
                filtered[key] = val;
            }
        }
        this.parametersChange.emit(filtered);
    }

    // A K8s resource.Quantity accepts:
    //   - a bare decimal: "1", "1.5"
    //   - decimal + binary SI suffix: "500Mi", "2Gi", "10Ki"
    //   - decimal + metric SI suffix: "500m" (milli for CPU), "1k", "1G"
    //   - scientific notation: "1.5e3"
    // Empty values are allowed — a missing optional parameter falls back to
    // the schema default server-side.
    private static readonly K8S_QUANTITY_RE =
        /^[0-9]+(\.[0-9]+)?(m|n|u|[kKMGTPE]i?|e[-+]?[0-9]+)?$/;

    private isQuantityField(field: SchemaField): boolean {
        if (field.type !== 'string') return false;
        const hay = `${field.name} ${field.description ?? ''} ${field.title ?? ''}`.toLowerCase();
        return /\b(cpu|memory|mem)\b/.test(hay) || /request|limit/.test(field.name.toLowerCase());
    }

    validateField(field: SchemaField, value: unknown): string {
        if (value === undefined || value === null || value === '') return '';
        if (!this.isQuantityField(field)) return '';
        const v = String(value).trim();
        if (!DynamicSchemaFormComponent.K8S_QUANTITY_RE.test(v)) {
            return `Invalid Kubernetes quantity. Use a number with an optional suffix (e.g. "500Mi", "2Gi", "500m", "1").`;
        }
        // A bare digit means BYTES for memory or CORES for CPU — almost never
        // what the user wants. "1" for memory = 1 byte, "1" for CPU = 1 core.
        // Catch the ambiguous case and nudge towards an explicit suffix.
        if (/^[0-9]+(\.[0-9]+)?$/.test(v)) {
            const lower = field.name.toLowerCase();
            if (lower.includes('memory') || lower.includes('mem')) {
                return `"${v}" would be interpreted as ${v} byte(s). Did you mean "${v}Mi" or "${v}Gi"?`;
            }
            if (lower.includes('cpu')) {
                return `"${v}" would be interpreted as ${v} core(s). Add an "m" suffix for milli-cores if that is not intended.`;
            }
        }
        return '';
    }
}
